translate Spanish style main_menu_title:
    xalign .5 yoffset -700 size gui.title_text_size font gui.main_font
translate Spanish python:
    gui.main_font = "gui/fonts/Edo.ttf"
    gui.text_font = "gui/fonts/Merienda-Regular.ttf"
    gui.name_text_font = "gui/fonts/Merienda-Bold.ttf"
    gui.interface_text_font = "gui/fonts/Merienda-Regular.ttf"
    gui.button_text_font  = "gui/fonts/Merienda-Regular.ttf"
    config.name = "Trabajadores desanimados"
    config.window_title = u"Trabajadores desanimados"
    config.translations['Automatic saves'] = u'Grabación automática'
    config.translations['Quick saves'] = u'Grabación rápid'
    build_date = "18 Dic. 2017"
    copyright = "©2017 YGGDRASIL STUDIO"
    gui.attention = "Advertencia"
    gui.start = "Empieza a leer"
    gui.bookmarks = "Marcadores"
    gui.load = "Cargar"
    gui.archives = "Archivo"
    gui.arcq = "Archivo"
    gui.dlc = "DLC y MOD"
    gui.conf = "Configuración"
    gui.conq = "Config"
    gui.play = "Auto"
    gui.stop = "Pausa"
    gui.skip = "Saltar"
    gui.history = "Historial"
    gui.hisq = "Historial"
    gui.hide = "Esconder"
    gui.save = "Guardar"
    gui.quit = "Salir"
    gui.credits = "Créditos"
    gui.unlocked = "Desbloqueado"
    gui.heal = "Curación"
    gui.judge = "Mirando"
    gui.left = "De vuelta a casa"
    gui.right = "Camino no tomado"
    gui.choice = "You can make a choice here. Listen to the following explanation and choose what you want."
    gui.teddy = "Encuentra a Teddy"
    gui.part01 = "¿Estás bien?"
    gui.part02 = "Monólogo"
    gui.part03 = "¿Recuerdas el primero amor?"
    gui.part04 = "Calle Shin-Chon"
    gui.part05 = "Almuerzo triste"
    gui.part06 = "Monólogo"
    gui.part07 = "Tarde tranquila"
    gui.part08 = "Sentimientos cuestionables"
    gui.part09 = "Circunstancias"
    gui.part10 = "Distorsión"
    gui.part11 = "Monólogo"
    gui.part12 = "Mente rota"
    gui.part13 = "¿Cuán vivo estas?"
    gui.part14 = "Agarrar la realidad"
    gui.part15 = "Autoinfligido"
    gui.part16 = "Q.E.P.D"
    gui.part17 = "Locura"
    gui.part18 = "Vista de Yunwoo"
    gui.part19 = "Vista de Ga-yeon"
    gui.part20 = "Ga-yeon y Yunwoo"
    gui.part21 = "Puente de la vida"
    gui.part22 = "Borde del mundo"
    gui.part23 = "Accidente"
    gui.part24 = "Epílogo"
    gui.part25 = "Mañanas floridas y noches iluminadas por la luna"
    gui.the_end = "El fin"
    gui.game_over = "Juego terminado"
    gui.bgm01 = "01. Pandemia"
    gui.bgm02 = "02. El día de la tristeza"
    gui.bgm03 = "03. El mar de la calma"
    gui.bgm04 = "04. CCCanon"
    gui.bgm05 = "05. ¡Vamos a jugar!"
    gui.bgm06 = "06. Paz"
    gui.bgm07 = "07. Niebla desconocida"
    gui.bgm08 = "08. Exuberante jardín"
    gui.bgm09 = "09. Jörmungandr"
    gui.bgm10 = "10. Nix"
    gui.bgm11 = "11. Cumbre enfrentamiento"
    gui.bgm12 = "12. Canción de amor"
    gui.bgm13 = "13. El mar de néctar"
    gui.about = "Discouraged Workers ©2017 YGGDRASIL STUDIO Co, Pte. All Rights Reserved. All literary works/trademarks are property of their respective owners. Do not distribute our program or any alterations of our program files. For the End User License Agreement, please view the EULA.txt file in the licenses directory, or visit {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/blob/gh-pages/EULA.txt}here{/a}."
    code.license = "The source code of Discouraged Workers is covered by the terms of the GNU Lesser General Public License v3.0. The source code can be found {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/tree/source-codes}here{/a}."
    font.license = "This program contains free font software under a number of licenses, including the SIL Open Font License. A complete list of font software, including links to download can be found {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}here{/a}, or please view the fonts-LICENSE.txt file in the licenses directory."
    renpy.license = "Este programa contiene software libre sujeto a diversas licencias que incluyen la licencia MIT y la {i}GNU Lesser General Public License{/i} (Licencia Pública General Reducida de GNU). Puedes encontrar la lista completa de software, con enlaces al código fuente completo, {a=https://www.renpy.org/l/license}aquí (en inglés){/a}."
    valve.license = "©2017 Valve Corporation. Steam y el logo de Steam son marcas y/o marcas registradas de Valve Corporation en los E.E.U.U. y/u otros países.\n\n©2017 Valve Corporation. Steamworks y el logo de Steamworks son marcas y/o marcas registradas de Valve Corporation en los E.E.U.U. y/u otros países."
    xbox.license = "This program contains Xbox 360 Controller/Button images. The asset pack can be found {a=http://xbox.create.msdn.com/en-us/education/catalog/utility/controller_buttons}here{/a}."
    cc.license = "This program contains a number of assets that are covered by the terms of the Creative Commons License. For a list of assets, and a location where the original assets can be downloaded from, please view the assets-LICENSE.txt file in the licenses directory or visit {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}here{/a}."