translate Korean strings:
    old "Image [index] of [count] locked."
    new "[count]번 삽화 [index]는 잠겨있습니다."
    old "Saved screenshot as %s."
    new "%s 삽화를 저장했습니다."
    old "Are you sure?"
    new "정말로 이럴 거예요?"
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new "책갈피되지 않은 내용은 찾을 수 없게 됩니다.\n정말로 그 쪽을 읽으시겠어요?"
    old "Are you sure you want to quit?"
    new "책장을 덮으시려고요?"
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new "목차로 돌아갈까요?\n책갈피되지 않은 내용은 찾을 수 없게 됩니다."
    old "Are you sure you want to overwrite your save?"
    new "정말로 여기에 책갈피를 하시겠습니까?"
    old "Are you sure you want to delete this save?"
    new "정말로 책갈피를 빼시렵니까?"