translate Korean strings:
    old "{font=fontawesome.ttf}{/font} Bookmark"
    new "{font=fontawesome.ttf}{/font} 책갈피"
    old "{font=fontawesome.ttf}{/font} Auto"
    new "{font=fontawesome.ttf}{/font} 자동저장"
    old "{font=fontawesome.ttf}{/font} Previous"
    new "{font=fontawesome.ttf}{/font} 이전"
    old "{font=fontawesome.ttf}{/font} Next"
    new "{font=fontawesome.ttf}{/font} 다음"
    old "{font=fontawesome.ttf}{/font} Language"
    new "{font=fontawesome.ttf}{/font} 언어설정"
    old "{font=fontawesome.ttf}{/font} Volume"
    new "{font=fontawesome.ttf}{/font} 음량조절"
    old "{font=fontawesome.ttf}{/font} Mute"
    new "{font=fontawesome.ttf}{/font} 끄기"
    old "{font=fontawesome.ttf}{/font} Min"
    new "{font=fontawesome.ttf}{/font} 최소"
    old "{font=fontawesome.ttf}{/font} Medium"
    new "{font=fontawesome.ttf}{/font} 중간"
    old "{font=fontawesome.ttf}{/font} Big"
    new "{font=fontawesome.ttf}{/font} 크게"
    old "{font=fontawesome.ttf}{/font} Max"
    new "{font=fontawesome.ttf}{/font} 최대"
    old "{font=fontawesome.ttf}{/font} Vibrate Control"
    new "{font=fontawesome.ttf}{/font} 진동 제어"
    old "{font=fontawesome.ttf}{/font} On"
    new "{font=fontawesome.ttf}{/font} 켜기"
    old "{font=fontawesome.ttf}{/font} Off"
    new "{font=fontawesome.ttf}{/font} 끄기"
    old "{font=fontawesome.ttf}{/font} Help"
    new "{font=fontawesome.ttf}{/font} 도움말"
    old "{font=fontawesome.ttf}{/font} Main"
    new "{font=fontawesome.ttf}{/font} 목차로"
    old "{font=fontawesome.ttf}{/font} Return"
    new "{font=fontawesome.ttf}{/font} 돌아가기"
    old "{font=fontawesome.ttf}{/font} Quit"
    new "{font=fontawesome.ttf}{/font} 종료하기"
    old "{font=fontawesome.ttf}{/font} Yes"
    new "{font=fontawesome.ttf}{/font} 네"
    old "{font=fontawesome.ttf}{/font} No"
    new "{font=fontawesome.ttf}{/font} 아니오"
    old "{font=fontawesome.ttf}{/font} Archives alarm"
    new "{font=fontawesome.ttf}{/font} 기록 알람"
    old "Empty Slot."
    new "책갈피 가능"
    old "{font=fontawesome.ttf}{/font} Select your language."
    new "{font=fontawesome.ttf}{/font} 읽을 언어를 선택해주세요."
    old "{font=fontawesome.ttf}{/font} Complete Select Language."
    new "{font=fontawesome.ttf}{/font} 언어 설정을 마칩니다."
    old "{font=fontawesome.ttf}{/font} Characters"
    new "{font=fontawesome.ttf}{/font} 등장인물"
    old "{font=fontawesome.ttf}{/font} Concept"
    new "{font=fontawesome.ttf}{/font} 해설모음"
    old "{font=fontawesome.ttf}{/font} Diary"
    new "{font=fontawesome.ttf}{/font} 가연의 일기"
    old "{font=fontawesome.ttf}{/font} Gallery"
    new "{font=fontawesome.ttf}{/font} 미술 전시관"
    old "{font=fontawesome.ttf}{/font} Music"
    new "{font=fontawesome.ttf}{/font} 음악 감상관"
    old "{font=fontawesome.ttf}{/font} Unknown the information."
    new "{font=fontawesome.ttf}{/font} 알고 있는 정보가 없습니다."
    old "{font=fontawesome.ttf}{/font} Select the character."
    new "{font=fontawesome.ttf}{/font} 등장인물의 이름을 선택하세요."
    old "{font=fontawesome.ttf}{/font} Select Your Want."
    new "{font=fontawesome.ttf}{/font} 원하는 것을 선택하세요."
    old "{font=fontawesome.ttf}{/font} Please wait for the next update."
    new "{font=fontawesome.ttf}{/font} 다음 업데이트를 기다려주세요."
    old "{font=fontawesome.ttf}{/font} Not available on the demo."
    new "{font=fontawesome.ttf}{/font} 체험판에서는 확인할 수 없습니다."
    old "{font=fontawesome.ttf}{/font} Ga-Yeon"
    new "{font=fontawesome.ttf}{/font} 최가연"
    old "{font=fontawesome.ttf}{/font} Yun-Woo"
    new "{font=fontawesome.ttf}{/font} 김윤우"
    old "{font=fontawesome.ttf}{/font} Hye-Na"
    new "{font=fontawesome.ttf}{/font} 최혜나"
    old "{font=fontawesome.ttf}{/font} Staff"
    new "{font=fontawesome.ttf}{/font} 직원"
    old "{font=fontawesome.ttf}{/font} Interviewer"
    new "{font=fontawesome.ttf}{/font} 면접관"
    old "{b}Choi Ga-Yeon{/b}"
    new "{b}최가연(最佳娟){/b}"
    old "{b}Birth:{/b} April 19th, 1986"
    new "{b}생년월일:{/b} 1986년 4월 19일"
    old "{b}Blood Type:{/b} A(RH+)"
    new "{b}혈액형:{/b} A(RH+)"
    old "{b}Height / Weight:{/b} 165cm / 48kg"
    new "{b}키 / 몸무게:{/b} 165cm / 48kg"
    old "{b}Bio:{/b} Discouraged worker / Leave of absence from\nHealth Administration of ○○ University"
    new "{b}전기:{/b} 무직 / ○○대학교 보건과학대학 보건행정학과 휴학"
    old "{b}Certificates:{/b} 1st class hospital coordinator / Hospital administrator"
    new "{b}보유자격:{/b} 1급 병원코디네이터 / 병원행정사"
    old "{b}Favorite:{/b} Begel, Margherita pizza, Sweet rice bun"
    new "{b}좋아하는 것:{/b} 깨찰빵, 마르게리타 피자, 베이글"
    old "{b}Dislike:{/b} Capitalism, Doctor, Member of parliament"
    new "{b}싫어하는 것:{/b} 국회의원, 의사, 자본주의"
    old "{b}Choi Hye-Na{/b}"
    new "{b}최혜나(最暳拏){/b}"
    old "{b}Birth:{/b} June 17th, 1989"
    new "{b}생년월일:{/b} 1989년 6월 17일"
    old "{b}Blood Type:{/b} O(RH+)"
    new "{b}혈액형:{/b} O(RH+)"
    old "{b}Height / Weight:{/b} 168cm / 48kg"
    new "{b}키 / 몸무게:{/b} 168cm / 48kg"
    old "{b}Bio:{/b} Karaoke helper / Graduated in Tourism Food & Beverage of ○○"
    new "{b}전기:{/b} 노래방 도우미 / ○○ 관광식음료과 졸업"
    old "{b}Certificates:{/b} 2nd class Barista"
    new "{b}보유자격:{/b} 2급 바리스타"
    old "{b}Favorite:{/b} Money, Photography, Older sister, Drinking"
    new "{b}좋아하는 것:{/b} 돈, 사진찍기, 언니, 음주가무"
    old "{b}Dislike:{/b} Oryide, Sweet rice bun, Nightclub"
    new "{b}싫어하는 것:{/b} 깨찰빵, 나이트클럽, 주정뱅이"
    old "{b}Kim Yun-Woo{/b}"
    new "{b}김윤우(金允友){/b}"
    old "{b}Birth:{/b} January 19th, 1986"
    new "{b}생년월일:{/b} 1986년 1월 19일"
    old "{b}Blood Type:{/b} AB(RH+)"
    new "{b}혈액형:{/b} AB(RH+)"
    old "{b}Height / Weight:{/b} 172cm / 58kg"
    new "{b}키 / 몸무게:{/b} 172cm / 58kg"
    old "{b}Bio:{/b} Bassist of ○○"
    new "{b}전기:{/b} ○○밴드 베이시스트"
    old "{b}Favorite:{/b} Bob Dylan, Choi Ga-Yeon, Yu Jae-Ha"
    new "{b}좋아하는 것:{/b} 밥 딜런, 유재하, 최가연"
    old "{b}Dislike:{/b} Audition, Management, Soju"
    new "{b}싫어하는 것:{/b} 매니지먼트, 소주, 오디션"
    old "{b}Staff{/b}"
    new "{b}직원{/b}"
    old "{b}Interviewer{/b}"
    new "{b}면접관{/b}"
    old "{b}Birth:{/b} Top Secret"
    new "{b}생년월일:{/b} 일급기밀"
    old "{b}Height / Weight:{/b} Top Secret"
    new "{b}키 / 몸무게:{/b} 일급기밀"
    old "{b}BWH:{/b} Top Secret"
    new "{b}BWH:{/b} 일급기밀"
    old "Not available on the demo."
    new "체험판에서는 확인할 수 없습니다."
    old "{font=fontawesome.ttf}{/font} Credits"
    new "{font=fontawesome.ttf}{/font} 만든이"
    old "{font=fontawesome.ttf}{/font} Authorship"
    new "{font=fontawesome.ttf}{/font} 저작권자"
    old "{font=fontawesome.ttf}{/font} Sponsor"
    new "{font=fontawesome.ttf}{/font} 후원자"
    old "{font=fontawesome.ttf}{/font} Supporter"
    new "{font=fontawesome.ttf}{/font} 도우미"
    old "{font=fontawesome.ttf}{/font} Authorship by"
    new "{font=fontawesome.ttf}{/font} 저작권자"
    old "{font=fontawesome.ttf}{/font} Actual Photos by"
    new "{font=fontawesome.ttf}{/font} 사진가"
    old "{font=fontawesome.ttf}{/font} You can check detail, please view the Help-Credits."
    new "{font=fontawesome.ttf}{/font} 당신은 도움말-만든사람에서 자세한 내용을 확인할 수 있습니다."
    old "Track 1. Pandemic"
    new "1번 트랙. 전염병"
    old "Track 2. Sigh day"
    new "2번 트랙. 탄식의 나날"
    old "Track 3. Mare tranquillitatis"
    new "3번 트랙. 고요의 바다"
    old "Track 4. CCCanon"
    new "4번 트랙. 트리플 캐논"
    old "Track 5. Let's game"
    new "5번 트랙. 게임을 시작하지"
    old "Track 6. Peace"
    new "6번 트랙. 평화"
    old "Track 7. Unknown mist"
    new "7번 트랙. 본 적 없는 안개"
    old "Track 8. Lush garden"
    new "8번 트랙. 푸른 정원"
    old "Track 9. Jormungandr"
    new "9번 트랙. 요르문간드"
    old "Track 10. Nyx"
    new "10번 트랙. 밤의 여신"
    old "Track 11. Summit showdown"
    new "11번 트랙. 정상결전"
    old "Track 12. Love song"
    new "12번 트랙. 연가"
    old "Track 13. Sea of nectar"
    new "13번 트랙. 넥타르의 평원"
    old "{font=fontawesome.ttf}{/font} Stop"
    new "{font=fontawesome.ttf}{/font} 재생 중지"
    old "{font=fontawesome.ttf}{/font} Shuffle"
    new "{font=fontawesome.ttf}{/font} 순서 섞기"
    old "{font=fontawesome.ttf}{/font} Loop"
    new "{font=fontawesome.ttf}{/font} 반복 재생"
    old "Discouraged worker"
    new "실망실업자"
    old "Reclusive outsider"
    new "은둔형 외톨이"
    old "Medical referral"
    new "진료의뢰서"
    old "Anxiety disorder"
    new "불안 장애"
    old "Depressive disorder"
    new "우울 장애"
    old "Bridge of the life"
    new "생명의 다리"
    old "IMF Crisis"
    new "IMF 경제위기"
    old "Prologue"
    new "프롤로그"
    old "Epilogue"
    new "에필로그"
    old "Flowery mornings and moonlit nights"
    new "꽃이 핀 아침과 달 밝은 저녁"
    old "Mahalath leannoth"
    new "마할랏르안놋"
    old "Seohae grand bridge"
    new "서해대교 29중 추돌사고"
    old "Red dialogue window"
    new "붉은색 지문창"
    old "{b}Discouraged worker{/b}"
    new "{b}실망실업자{/b}"
    old "{b}Reclusive outsider{/b}"
    new "{b}은둔형 외톨이{/b}"
    old "{b}Medical referral{/b}"
    new "{b}진료의뢰서{/b}"
    old "{b}Anxiety disorder{/b}"
    new "{b}불안 장애{/b}"
    old "{b}Depressive disorder{/b}"
    new "{b}우울 장애{/b}"
    old "{b}Bridge of the life{/b}"
    new "{b}생명의 다리{/b}"
    old "{b}IMF Crisis{/b}"
    new "{b}IMF 경제위기{/b}"
    old "{b}Prologue{/b}"
    new "{b}프롤로그{/b}"
    old "{b}Epilogue{/b}"
    new "{b}에필로그{/b}"
    old "{b}Accident{/b}"
    new "{b}사건발생{/b}"
    old "{b}Flowery mornings and moonlit nights{/b}"
    new "{b}꽃이 핀 아침과 달 밝은 저녁{/b}"
    old "{b}Mahalath leannoth{/b}"
    new "{b}마할랏르안놋{/b}"
    old "{b}Seohae grand bridge{/b}"
    new "{b}서해대교 29중 추돌사고{/b}"
    old "{b}Red dialogue window{/b}"
    new "{b}붉은색 지문 창{/b}"
    old " discouraged worker is a person of legal employment age who is not actively seeking employment or who does not find employment after long-term unemployment. This is usually because an individual has given up looking or has had no success in finding a job, hence the term \"discouraged\"."
    new " 실망실업자의 사전적인 의미는 취업을 원하지만, 일자리를 구하지 못해 구직을 단념한 사람을 말한다. 실망실업자는 사실상 실업자이지만 비경제활동인구로 분류돼 실업자 통계에 포함되지 않는다. 이 때문에 체감 실업률이 높아져도 실업자 통계에서는 실업률이 하락하는 현상이 나타난다. 한국은 2014년 11월에 숨은 실업자를 포함한 보조고용지표를 처음 발표했고 한국의 고용률과 실망실업자에 대한 문제가 표면에 드러났다."
    old "https://en.wikipedia.org/wiki/Discouraged_worker"
    new "이윤석 -YGGDRASIL STUDIO"
    old " A hospital coordinator, Ga-Yeon, fell in love with a doctor at the hospital she was working in and they had an affair even though the doctor was a married man. But when the director found out, she was fired. For over a year she tried to find another job, but her mental uneasiness eventually made her give up and she became a recluse."
    new " 병원 코디네이터라는 직업을 가지고 있던 가연은 자신이 근무하는 병원의 의사와 사랑을 하게 되었다. 하지만 의사에게는 아내가 있었고, 둘의 사랑은 불륜이었다. 사실을 알게 된 원장에 의해 해고된 후 다른 직장을 찾아다니지만, 그녀의 정신적인 불안과 현실의 벽으로 1년 동안 직장을 구하지 못하고 결국 취업을 포기한다."
    old " A year later, in the spring of 2013, her younger sister, Hye-Na, and her first love Yun-Woo come to her."
    new " 그로부터 다시 1년이 지난 2013년 봄의 대한민국, 은둔형 외톨이가 되어버린 그녀에게 찾아온 여동생 혜나와 첫사랑 윤우."
    old " A story about the dark side of today’s youth and pretty serious everyday life happening around Ga-Yeon."
    new " 이 시대를 살아가는 청춘들의 어두운 단면과 가연을 중심으로 벌어지는 가볍지 않은 일상."
    old " Discouraged Workers"
    new " 실망실업자"