translate Korean strings:
    old "Me"
    new "나"
    old "Hye-Na"
    new "혜나"
    old "Yun-Woo"
    new "윤우"
    old "Staff"
    new "직원"
    old "Interviewer"
    new "면접관"
    old "WARNING"
    new "경       고"
    old "This game contains Suggestive Themes, Alcohol Reference"
    new "이 프로그램은 12세 미만의 청소년이 시청하기에 부적절하므로\n보호자의 시청지도가 필요한 프로그램입니다.\n이 프로그램은 다음과 같은 내용을 포함하고 있습니다.\n성적인 풍자"
    old "I never wanna be born human again, ever."
    new "다시는 인간으로 태어나고 싶지 않아."
    old "{color=#ff9000}{size=+64}A{/size}{/color}re you alright?"
    new "{color=#ff9000}{size=+64}혜{/size}{/color}나의 방문"
    old "{color=#776e6e}{size=+64}M{/size}{/color}onologue"
    new "{color=#776e6e}{size=+64}가{/size}{/color}연의 독백"
    old "A year ago…."
    new "일 년 전…."
    old "{color=#c938ff}{size=+64}D{/size}{/color}o you remember first love?"
    new "{color=#c938ff}{size=+64}윤{/size}{/color}우와 만남"
    old "{color=#c938ff}{size=+64}S{/size}{/color}hin-Chon Street"
    new "{color=#c938ff}{size=+64}윤{/size}{/color}우와 신촌거리"
    old "{color=#c938ff}{size=+64}S{/size}{/color}ad lunch"
    new "{color=#c938ff}{size=+64}윤{/size}{/color}우와 점심식사"
    old "{color=#c938ff}{size=+64}C{/size}{/color}alm afternoon"
    new "{color=#c938ff}{size=+64}윤{/size}{/color}우와 담소"
    old "{color=#c938ff}{size=+64}Q{/size}{/color}uestionable {color=#ff9000}{size=+64}F{/size}{/color}{color=#fdc56c}eelings{/color}"
    new "{color=#c938ff}{size=+64}윤{/size}{/color}우가 들려준 {color=#ff9000}{size=+64}혜{/size}{/color}{color=#fdc56c}나의 이야기{/color}"
    old "{color=#ff9000}{size=+64}C{/size}{/color}ircumstances"
    new "{color=#ff9000}{size=+64}혜{/size}{/color}나의 사정"
    old "Choi Hye-Na"
    new "혜나야"
    old "{color=#776e6e}{size=+64}G{/size}{/color}ame {color=#776e6e}{size=+64}O{/size}{/color}ver"
    new "{color=#776e6e}{size=+64}끝{/size}{/color}"
    old "{b}Characters +1{/b}"
    new "{b}등장인물 +1{/b}"
    old "{b}Music +1{/b}"
    new "{b}음악 감상관 +1{/b}"
    old "{b}Concept +1{/b}"
    new "{b}해설 모음 +1{/b}"