translate Russian strings:
    old "{#weekday}Monday"
    new "{#weekday}Понедельник"
    old "{#weekday}Tuesday"
    new "{#weekday}Вторник"
    old "{#weekday}Wednesday"
    new "{#weekday}Среда"
    old "{#weekday}Thursday"
    new "{#weekday}Четверг"
    old "{#weekday}Friday"
    new "{#weekday}Пятница"
    old "{#weekday}Saturday"
    new "{#weekday}Суббота"
    old "{#weekday}Sunday"
    new "{#weekday}Воскресенье"
    old "{#weekday_short}Mon"
    new "{#weekday_short}Пн"
    old "{#weekday_short}Tue"
    new "{#weekday_short}Вт"
    old "{#weekday_short}Wed"
    new "{#weekday_short}Ср"
    old "{#weekday_short}Thu"
    new "{#weekday_short}Чт"
    old "{#weekday_short}Fri"
    new "{#weekday_short}Пт"
    old "{#weekday_short}Sat"
    new "{#weekday_short}Сб"
    old "{#weekday_short}Sun"
    new "{#weekday_short}Вс"
    old "{#month}January"
    new "{#month}Января"
    old "{#month}February"
    new "{#month}Февраля"
    old "{#month}March"
    new "{#month}Марта"
    old "{#month}April"
    new "{#month}Апреля"
    old "{#month}May"
    new "{#month}Мая"
    old "{#month}June"
    new "{#month}Июня"
    old "{#month}July"
    new "{#month}Июля"
    old "{#month}August"
    new "{#month}Августа"
    old "{#month}September"
    new "{#month}Сентября"
    old "{#month}October"
    new "{#month}Октября"
    old "{#month}November"
    new "{#month}Ноября"
    old "{#month}December"
    new "{#month}Декабря"
    old "{#month_short}Jan"
    new "{#month_short}Янв"
    old "{#month_short}Feb"
    new "{#month_short}Фев"
    old "{#month_short}Mar"
    new "{#month_short}Мар"
    old "{#month_short}Apr"
    new "{#month_short}Апр"
    old "{#month_short}May"
    new "{#month_short}Мая"
    old "{#month_short}Jun"
    new "{#month_short}Июн"
    old "{#month_short}Jul"
    new "{#month_short}Июл"
    old "{#month_short}Aug"
    new "{#month_short}Авг"
    old "{#month_short}Sep"
    new "{#month_short}Сен"
    old "{#month_short}Oct"
    new "{#month_short}Окт"
    old "{#month_short}Nov"
    new "{#month_short}Ноя"
    old "{#month_short}Dec"
    new "{#month_short}Дек"
    old "%b %d, %H:%M"
    new "%d %b, %H:%M"
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new "{#file_time}%A, %d %B %Y, %H:%M"
    old "Quick save complete."
    new "Быстрое сохранение завершено."
    old "Image [index] of [count] locked."
    new "Изображение [index] из [count] закрыто."
    old "Graphics Acceleration"
    new "Графическое Ускорение"
    old "Automatically Choose"
    new "Выбирать Автоматически"
    old "Force Angle/DirectX Renderer"
    new "Насильно Отображать Через Angle/DirectX"
    old "Force OpenGL Renderer"
    new "Насильно Отображать Через OpenGL"
    old "Force Software Renderer"
    new "Насильно Отображать Программно"
    old "Changes will take effect the next time this program is run."
    new "Изменения вступят в силу при следующем запуске программы."
    old "Performance Warning"
    new "Предупреждение Производительности"
    old "This computer is using software rendering."
    new "Этот компьютер использует программный рендеринг."
    old "This computer is not using shaders."
    new "Этот компьютер не использует шейдеры."
    old "This computer is displaying graphics slowly."
    new "Этот компьютер медленно отображает графику."
    old "This computer has a problem displaying graphics: [problem]."
    new "У этого компьютера проблема с отображением графики: [problem]"
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display. Updating DirectX could fix this problem."
    new "Графические драйвера устарели или работают неверно. Это может привести к медленному или неверному отображению графики. Обновление DirectX может решить эту проблему."
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new "Графические драйвера устарели или работают неверно. Это может привести к медленному или неверному отображению графики."
    old "Update DirectX"
    new "Обновить DirectX"
    old "Continue, Show this warning again"
    new "Продолжить, Показать это предупреждение снова"
    old "Continue, Don't show warning again"
    new "Продолжить, Не показывать это предупреждение снова."
    old "Updating DirectX."
    new "Обновляю DirectX."
    old "DirectX web setup has been started. It may start minimized in the taskbar. Please follow the prompts to install DirectX."
    new "Установщик DirectX был запущен. Возможно, что он запустился в свёрнутом состоянии. Пожалуйста, следуйте инструкциям для установки DirectX."
    old "{b}Note:{/b} Microsoft's DirectX web setup program will, by default, install the Bing toolbar. If you do not want this toolbar, uncheck the appropriate box."
    new "{b}Предупреждение:{/b} Установщик DirectX по умолчанию пытается установить панель инструментов Bing. Если вы этого не хотите, снимите соответствующую галочку."
    old "When setup finishes, please click below to restart this program."
    new "По завершению установки, щёлкните, чтобы перезапустить программу."
    old "Restart"
    new "Перезапустить"
    old "Saved screenshot as %s."
    new "Скриншот сохранён как %s."
    old "Are you sure?"
    new "Вы уверены?"
    old "Are you sure you want to delete this save?"
    new "Вы уверены, что хотите удалить это сохранение?"
    old "Are you sure you want to overwrite your save?"
    new "Вы уверены, что хотите перезаписать ваше сохранение?"
    old "The next step is an important scene. Do you want to save here?"
    new "Следующая​ сцена является важной. Хотите сохраниться?"
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new "Загрузка игры приведёт к потере несохранённого прогресса.\nВы уверены, что хотите это сделать?"
    old "Are you sure you want to quit?"
    new "Вы уверены, что хотите выйти?"
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new "Вы уверены, что хотите вернуться в главное меню?\nЭто приведёт к потере несохранённого прогресса."
    old "Are you sure you want to skip to unseen dialogue or the next choice?"
    new "Вы уверены, что хотите пропустить непрочитанные диалоги до следующего выбора?"
    old "Are you sure you want to end the replay?"
    new "Вы уверены, что хотите завершить повтор?"
    old "Skip Mode"
    new "Режим Пропуска"
    old "Fast Skip Mode"
    new "Режим Б.Пропуск"
    old "An exception has occurred."
    new "Возникло исключение."
    old "Rollback"
    new "Назад"
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new "Пытается вернуться назад, позволяя вам сохраниться или принять другой выбор."
    old "Ignore"
    new "Игнорировать"
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new "Игнорирует это исключение, позволяя вам продолжить. Зачастую это ведёт к дополнительным ошибкам."
    old "Reload"
    new "Перезагрузить"
    old "Reloads the game from disk, saving and restoring game state if possible."
    new "Перезагружает игру с диска, сохраняя и восстанавливая её состояние, если это возможно."
    old "Open Traceback"
    new "Открывает файл traceback.txt"
    old "Opens the traceback.txt file in a text editor."
    new "Открывает файл traceback.txt в текстовом редакторе."
    old "Quits the game."
    new "Выходит из игры."
    old "Parsing the script failed."
    new "Обработка сценария завершилась неудачно."
    old "Open Parse Errors"
    new "Открывает файл errors.txt"
    old "Opens the errors.txt file in a text editor."
    new "Открывает файл errors.txt в текстовом редакторе."
    old "Self-voicing enabled. Press 'v' to disable."
    new "Синтезатор речи включён. Нажмите 'v', чтобы отключить его."
    old "Self-voicing disabled."
    new "Синтезатор речи отключён."