translate Russian style main_menu_title:
    xalign .5 yoffset -700 size gui.title_text_size - 10 font gui.main_font
translate Russian python:
    gui.main_font = "gui/fonts/Intro Cond Black Free.otf"
    gui.text_font = "gui/fonts/DejaVuSans.ttf"
    gui.name_text_font = "gui/fonts/DejaVuSans-Bold.ttf"
    gui.interface_text_font = "gui/fonts/DejaVuSans.ttf"
    gui.button_text_font = "gui/fonts/DejaVuSans.ttf"
    config.name = "Отчаявшиеся работники"
    config.window_title = u"Отчаявшиеся работники"
    config.translations['Automatic saves'] = u'Автосохранения'
    config.translations['Quick saves'] = u'Быстрые сохранения'
    build_date = "18 Дек 2017"
    copyright = "©2017 YGGDRASIL STUDIO"
    gui.attention = "ВНИМАНИЕ"
    gui.language = "В соответствии с Федеральным законом № 436-ФЗ от 29.12.2010 данная игра содержит сцены:\n\nСамоубийства, употребления алкоголя и табачных изделий, нецензурной лексики, порнографии"
    gui.start = "Начать"
    gui.bookmarks = "Закладки"
    gui.load = "Загрузить"
    gui.archives = "Архив"
    gui.arcq = "Архив"
    gui.dlc = "DLC и MOD"
    gui.conf = "Настройки"
    gui.conq = "Настройки"
    gui.play = "Авто"
    gui.stop = "Стоп"
    gui.skip = "Пропуск"
    gui.history = "История"
    gui.hisq = "История"
    gui.hide = "Спрятать"
    gui.save = "Сохранить"
    gui.quit = "Выход"
    gui.credits = "Кредиты"
    gui.unlocked = "Открывать"
    gui.heal = "целебный"
    gui.judge = "смотрящий"
    gui.left = "восвояси"
    gui.right = "Дорога не Взятые"
    gui.choice = "Здесь вы можете сделать выбор. Прослушайте описание и выберите понравившийся вас вариант."
    gui.teddy = "Найдите Тедди"
    gui.part01 = "Ты в порядке?"
    gui.part02 = "Монолог"
    gui.part03 = "А ты помнишь свою первую любовь?"
    gui.part04 = "Улица Шин-Хон"
    gui.part05 = "Грустный ланч"
    gui.part06 = "Монолог"
    gui.part07 = "Спокойный полдень"
    gui.part08 = "Интуиции"
    gui.part09 = "Обстоятельства"
    gui.part10 = "Искажение"
    gui.part11 = "Монолог"
    gui.part12 = "Разбитый разум"
    gui.part13 = "История жизни"
    gui.part14 = "Захватывающая реальность"
    gui.part15 = "Самобичевание"
    gui.part16 = "R.I.P"
    gui.part17 = "Безумие"
    gui.part18 = "Взгляд Янву"
    gui.part19 = "Взгляд Га-Йан"
    gui.part20 = "Га-Йан и Янву"
    gui.part21 = "Мост жизни"
    gui.part22 = "Край света"
    gui.part23 = "Несчастный случай"
    gui.part24 = "Эпилог"
    gui.part25 = "Утра, полные цветов, и ночи, залитые лунным светом"
    gui.the_end = "Конец"
    gui.game_over = "Игра окончена"
    gui.bgm01 = "Track 1. Pandemic"
    gui.bgm02 = "Track 2. Sigh day"
    gui.bgm03 = "Track 3. Mare tranquillitatis"
    gui.bgm04 = "Track 4. CCCanon"
    gui.bgm05 = "Track 5. Let's game"
    gui.bgm06 = "Track 6. Peace"
    gui.bgm07 = "Track 7. Unknown mist"
    gui.bgm08 = "Track 8. Lush garden"
    gui.bgm09 = "Track 9. Jormungandr"
    gui.bgm10 = "Track 10. Nyx"
    gui.bgm11 = "Track 11. Summit showdown"
    gui.bgm12 = "Track 12. Love song"
    gui.bgm13 = "Track 13. Sea of nectar"
    gui.about = "Discouraged Workers ©2017 YGGDRASIL STUDIO Co, Pte. Все права защищены. Все литературные произведения/товарные знаки являются собственностью соответствующих владельцев. Не распространяйте нашу программу или какие-либо изменения в программных файлах. Для Лицензионного соглашения с конечным пользователем, пожалуйста, просмотрите файл EULA.txt в каталоге лицензий или посетите {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/blob/gh-pages/EULA.txt}данную страницу{/a}."
    code.license = "Исходный код Disouraged Workers распространяется на условия GNU Lesser General Public License v3.0. Исходный код можно найти {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/tree/source-codes}здесь{/a}."
    font.license = "Эта программа содержит бесплатное программное обеспечение для шрифтов по ряду лицензий, включая SIL Open Font License. Полный список программного обеспечения для шрифтов, включая ссылки для загрузки, можно найти{a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}здесь{/a} или в файле fonts-LICENSE.txt из каталога лицензий."
    renpy.license = "Эта программа содержит свободное и открытое программное обеспечение под несколькими лицензиями, включая лицензию MIT и GNU Lesser General Public. Полный список лицензий, включая ссылки на полный исходный код, можно найти {a=https://www.renpy.org/l/license}здесь{/a}."
    valve.license = "©2017 Valve Corporation. Название и логотип Steam являются торговыми знаками и/или зарегистрированными торговыми знаками Valve Corporation в США и/или других странах.\n \n©2017 Valve Corporation. Название и логотип Steamworks являются торговыми знаками и/или зарегистрированными торговыми знаками Valve Corporation в США и/или других странах."
    xbox.license = "Эта программа содержит изображения контроллера Xbox 360 и его кнопок. Пакет изображений можно найти {a=http://xbox.create.msdn.com/en-us/education/catalog/utility/controller_buttons}здесь{/a}."
    cc.license = "Эта программа содержит ряд активов, которые охватываются условиями Creative Commons License. Для получения списка активов и ссылок для загрузки просмотрите файл assets-LICENSE.txt в каталоге лицензий или посетите{a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}данную страницу{/a}."