translate Russian strings:
    old "Load"
    new "Загрузить"
    old "Left arrow key: Yes, Right arrow key: No."
    new "Левая клавиша: Да, Правая клавиша: Нет"
    old "Left arrow key: Previous, Right arrow key: Next."
    new "Левая клавиша: Пред, Правая клавиша: След."
    old "Left arrow key: Healing, Right arrow key: Onlooking"
    new "Левая клавиша: целебный, Правая клавиша: смотрящий"
    old "Left arrow key: Back home, Right arrow key: Road not taken"
    new "Левая клавиша: восвояси, Правая клавиша: Дорога не Взятые"
    old "You can make a choice here. Listen to the following explanation and choose what you want."
    new "Здесь вы можете сделать выбор. Прослушайте описание и выберите понравившийся вас вариант."
    old "©2020 YGGDRASIL STUDIO"
    new "©2020 YGGDRASIL STUDIO"
    old "June 06, 2020 - V[config.version]"
    new "06 Июн 2020 - V[config.version]"
    old "{size=86}Start Reading{/size}"
    new "Начать"
    old "{size=86}Bookmarks{/size}"
    new "Закладки"
    old "{size=86}Load{/size}"
    new "Загрузить"
    old "{size=86}Archives{/size}"
    new "Архив"
    old "{size=86}DLC&MOD{/size}"
    new "DLC и MOD"
    old "{size=86}Configuration{/size}"
    new "Настройки"
    old "{size=86}Characters{/size}"
    new "Персонажи"
    old "{size=86}Concept{/size}"
    new "Концепция"
    old "{size=86}Diary{/size}"
    new "Дневник"
    old "{size=86}Quit{/size}"
    new "Выход"
    old '{size=[gui.quick_button_text_size]}Config{/size}'
    new '{size=[gui.quick_button_text_size]}Настройки{/size}'
    old '{size=[gui.quick_button_text_size]}Play{/size}'
    new '{size=[gui.quick_button_text_size]}Авто{/size}'
    old "{font=[gui.fontawesome]}{/font} Play"
    new "{font=[gui.fontawesome]}{/font} Авто"
    old '{size=[gui.quick_button_text_size]}Skip{/size}'
    new '{size=[gui.quick_button_text_size]}Пропуск{/size}'
    old "{font=[gui.fontawesome]}{/font} Archives"
    new "{font=[gui.fontawesome]}{/font} Архив"
    old '{size=[gui.quick_button_text_size]}Archives{/size}'
    new '{size=[gui.quick_button_text_size]}Архив{/size}'
    old "{font=[gui.fontawesome]}{/font} History"
    new "{font=[gui.fontawesome]}{/font} История"
    old '{size=[gui.quick_button_text_size]}History{/size}'
    new '{size=[gui.quick_button_text_size]}История{/size}'
    old '{size=[gui.quick_button_text_size]}Hide{/size}'
    new '{size=[gui.quick_button_text_size]}Спрятать{/size}'
    old '{size=[gui.quick_button_text_size]}Save{/size}'
    new '{size=[gui.quick_button_text_size]}Сохранить{/size}'
    old "{font=[gui.fontawesome]}{/font} Credits"
    new "{font=[gui.fontawesome]}{/font} Кредиты"
    old "{font=[gui.fontawesome]}{/font} Unlocked"
    new "{font=[gui.fontawesome]}{/font} Открывать"
    old '{size=[gui.interface_text_size]}Healing{/size}'
    new '{size=[gui.interface_text_size]}целебный{/size}'
    old '{size=[gui.interface_text_size]}Onlooking{/size}'
    new '{size=[gui.interface_text_size]}смотрящий{/size}'
    old '{size=[gui.interface_text_size]}Back home{/size}'
    new '{size=[gui.interface_text_size]}восвояси{/size}'
    old '{size=[gui.interface_text_size]}Road not taken{/size}'
    new '{size=[gui.interface_text_size]}Дорога не Взятые{/size}'
    old "{image=gui/controllers/[persistent.controllers]/grip_r.webp} {size=86}Start Reading{/size}"
    new "{image=gui/controllers/[persistent.controllers]/grip_r.webp} Начать"
    old "{image=gui/controllers/[persistent.controllers]/guide.webp} {size=86}Start Reading{/size}"
    new "{image=gui/controllers/[persistent.controllers]/guide.webp} Начать"
    old "{image=gui/controllers/[persistent.controllers]/shoulder_r.webp} {size=86}Load{/size}"
    new "{image=gui/controllers/[persistent.controllers]/shoulder_r.webp} Загрузить"
    old "{image=gui/controllers/[persistent.controllers]/button_start.webp} {size=86}Load{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_start.webp} Загрузить"
    old "{image=gui/controllers/[persistent.controllers]/shoulder_r.webp} {size=86}Bookmarks{/size}"
    new "{image=gui/controllers/[persistent.controllers]/shoulder_r.webp} Закладки"
    old "{image=gui/controllers/[persistent.controllers]/button_start.webp} {size=86}Bookmarks{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_start.webp} Закладки"
    old "{image=gui/controllers/[persistent.controllers]/button_b.webp} {size=86}Archives{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_b.webp} Архив"
    old "{image=gui/controllers/[persistent.controllers]/button_b.webp} {size=86}Characters{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_b.webp} Персонажи"
    old "{image=gui/controllers/[persistent.controllers]/button_x.webp} {size=86}Concept{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_x.webp} Концепция"
    old "{image=gui/controllers/[persistent.controllers]/button_y.webp} {size=86}Diary{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_y.webp} Дневник"
    old "{image=gui/controllers/[persistent.controllers]/button_x.webp} {size=86}DLC&MOD{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_x.webp} DLC и MOD"
    old "{image=gui/controllers/[persistent.controllers]/button_y.webp} {size=86}Configuration{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_y.webp} Настройки"
    old "{image=gui/controllers/[persistent.controllers]/shoulder_l.webp} {size=86}Quit{/size}"
    new "{image=gui/controllers/[persistent.controllers]/shoulder_l.webp} Выход"
    old "{image=gui/controllers/[persistent.controllers]/button_select.webp} {size=86}Quit{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_select.webp} Выход"
    old "Credits"
    new "Кредиты"
    old "Discouraged Workers ©2020 YGGDRASIL STUDIO Co, Pte. All Rights Reserved. All literary works/trademarks are property of their respective owners. Do not distribute our program or any alterations of our program files. For the End User License Agreement, please view the EULA.txt file in the licenses directory, or visit {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/blob/gh-pages/EULA.txt}here{/a}.\n\nThe source code of Discouraged Workers is covered by the terms of the GNU Lesser General Public License v3.0. The source code can be found {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/tree/source-codes}here{/a}.\n"
    new "Discouraged Workers ©2020 YGGDRASIL STUDIO Co, Pte. Все права защищены. Все литературные произведения/товарные знаки являются собственностью соответствующих владельцев. Не распространяйте нашу программу или какие-либо изменения в программных файлах. Для Лицензионного соглашения с конечным пользователем, пожалуйста, просмотрите файл EULA.txt в каталоге лицензий или посетите {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/blob/gh-pages/EULA.txt}данную страницу{/a}.\n\nИсходный код Disouraged Workers распространяется на условия GNU Lesser General Public License v3.0. Исходный код можно найти {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/tree/source-codes}здесь{/a}.\n"
    old "This program contains free font software under a number of licenses, including the SIL Open Font License. A complete list of font software, including links to download can be found {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}here{/a}, or please view the fonts-LICENSE.txt file in the licenses directory.\n\nThis program contains a number of assets that are covered by the terms of the Creative Commons License. For a list of assets, and a location where the original assets can be downloaded from, please view the assets-LICENSE.txt file in the licenses directory or visit {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}here{/a}.\n"
    new "Эта программа содержит бесплатное программное обеспечение для шрифтов по ряду лицензий, включая SIL Open Font License. Полный список программного обеспечения для шрифтов, включая ссылки для загрузки, можно найти{a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}здесь{/a} или в файле fonts-LICENSE.txt из каталога лицензий.\n\nЭта программа содержит ряд активов, которые охватываются условиями Creative Commons License. Для получения списка активов и ссылок для загрузки просмотрите файл assets-LICENSE.txt в каталоге лицензий или посетите{a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}данную страницу{/a}.\n"
    old "This program contains Xbox 360 Controller/Button images. The asset pack can be found {a=http://xbox.create.msdn.com/en-us/education/catalog/utility/controller_buttons}here{/a}.\n"
    new "Эта программа содержит изображения контроллера Xbox 360 и его кнопок. Пакет изображений можно найти {a=http://xbox.create.msdn.com/en-us/education/catalog/utility/controller_buttons}здесь{/a}.\n"
    old "©2020 Valve Corporation. Steam and the Steam logo are trademarks and/or registered trademarks of Valve Corporation in the U.S. and/or other countries.\n\n©2020 Valve Corporation. Steamworks and the Steamworks logo are trademarks and/or registered trademarks of Valve Corporation in the U.S. and/or other countries."
    new "©2020 Valve Corporation. Название и логотип Steam являются торговыми знаками и/или зарегистрированными торговыми знаками Valve Corporation в США и/или других странах.\n\n©2020 Valve Corporation. Название и логотип Steamworks являются торговыми знаками и/или зарегистрированными торговыми знаками Valve Corporation в США и/или других странах."
    old "{font=[gui.fontawesome]}{/font} Basic Settings"
    new "{font=[gui.fontawesome]}{/font} Базовые настройки"
    old "{font=[gui.fontawesome]}{/font} About"
    new "{font=[gui.fontawesome]}{/font} Об игре"
    old "{font=[gui.fontawesome]}{/font} Help"
    new "{font=[gui.fontawesome]}{/font} Помощь"
    old "{font=[gui.fontawesome]}{/font} Characters"
    new "{font=[gui.fontawesome]}{/font} Персонажи"
    old "{font=[gui.fontawesome]}{/font} Concept"
    new "{font=[gui.fontawesome]}{/font} Концепция"
    old "{font=[gui.fontawesome]}{/font} Diary"
    new "{font=[gui.fontawesome]}{/font} Дневник"
    old "{font=[gui.fontawesome]}{/font} Gallery"
    new "{font=[gui.fontawesome]}{/font} Галерея"
    old "{font=[gui.fontawesome]}{/font} Music"
    new "{font=[gui.fontawesome]}{/font} Музыка"
    old "{font=[gui.fontawesome]}{/font} Replay"
    new "{font=[gui.fontawesome]}{/font} Повтор"
    old "{font=[gui.fontawesome]}{/font} Medals"
    new "{font=[gui.fontawesome]}{/font} Медали"
    old "{font=[gui.fontawesome]}{/font} Refresh"
    new "{font=[gui.fontawesome]}{/font} Обновление"
    old "{font=[gui.fontawesome]}{/font} Window"
    new "{font=[gui.fontawesome]}{/font} Оконный"
    old "{font=[gui.fontawesome]}{/font} Fullscreen"
    new "{font=[gui.fontawesome]}{/font} Полный"
    old "{font=[gui.fontawesome]}{/font} Save"
    new "{font=[gui.fontawesome]}{/font} Сохранить"
    old "{font=[gui.fontawesome]}{/font} Start Reading"
    new "{font=[gui.fontawesome]}{/font} Начать"
    old "{font=[gui.fontawesome]}{/font} Load"
    new "{font=[gui.fontawesome]}{/font} Загрузить"
    old "{font=[gui.fontawesome]}{/font} Configuration"
    new "{font=[gui.fontawesome]}{/font} Настройки"
    old "{font=[gui.fontawesome]}{/font} DLC&MOD"
    new "{font=[gui.fontawesome]}{/font} DLC и MOD"
    old "{font=[gui.fontawesome]}{/font} End Replay"
    new "{font=[gui.fontawesome]}{/font} Завершить повтор"
    old "{font=[gui.fontawesome]}{/font} Main Menu"
    new "{font=[gui.fontawesome]}{/font} Главное меню"
    old "{font=[gui.fontawesome]}{/font} Quit"
    new "{font=[gui.fontawesome]}{/font} Выход"
    old "{font=[gui.fontawesome]}{/font} Done"
    new "{font=[gui.fontawesome]}{/font} Готово"
    old "{font=[gui.fontawesome]}{/font} Return"
    new "{font=[gui.fontawesome]}{/font} Вернуться"
    old "{font=[gui.fontawesome]}{/font} Yes"
    new "{font=[gui.fontawesome]}{/font} Да"
    old "{font=[gui.fontawesome]}{/font} No"
    new "{font=[gui.fontawesome]}{/font} Нет"
    old "Version [config.version!t]\n"
    new "Версия [config.version!t]\n"
    old "Created with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\nThis program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license/}here{/a}.\n"
    new "Созданный с {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\nЭта программа содержит свободное и открытое программное обеспечение под несколькими лицензиями, включая лицензию MIT и GNU Lesser General Public. Полный список лицензий, включая ссылки на полный исходный код, можно найти {a=https://www.renpy.org/l/license}здесь{/a}.\n"
    old "empty slot"
    new "Пустой слот"
    old "{#auto_page}A"
    new "{#auto_page}А"
    old "{#quick_page}Q"
    new "{#quick_page}Б"
    old "Page {}"
    new "{} страница"
    old "Automatic saves"
    new "Автосохранения"
    old "Quick saves"
    new "Быстрые сохранения"
    old "{font=[gui.fontawesome]}{/font} Display"
    new "{font=[gui.fontawesome]}{/font} Режим экрана"
    old "{font=[gui.fontawesome]}{/font} Rollback Side"
    new "{font=[gui.fontawesome]}{/font} Сторона отката"
    old "{font=[gui.fontawesome]}{/font} Enable"
    new "{font=[gui.fontawesome]}{/font} Включить"
    old "{font=[gui.fontawesome]}{/font} Disable"
    new "{font=[gui.fontawesome]}{/font} Отключить"
    old "{font=[gui.fontawesome]}{/font} Left"
    new "{font=[gui.fontawesome]}{/font} Левая"
    old "{font=[gui.fontawesome]}{/font} Right"
    new "{font=[gui.fontawesome]}{/font} Правая"
    old "{font=[gui.fontawesome]}{/font} Skip"
    new "{font=[gui.fontawesome]}{/font} Пропуск"
    old "{font=[gui.fontawesome]}{/font} Seen Text"
    new "{font=[gui.fontawesome]}{/font} Прочтённых сообщений"
    old "{font=[gui.fontawesome]}{/font} After Choices"
    new "{font=[gui.fontawesome]}{/font} После выборов"
    old "{font=[gui.fontawesome]}{/font} Transitions"
    new "{font=[gui.fontawesome]}{/font} Переходов"
    old "{font=[gui.fontawesome]}{/font} Text Speed"
    new "{font=[gui.fontawesome]}{/font} Скорость текста"
    old "{font=[gui.fontawesome]}{/font} Auto-Forward Time"
    new "{font=[gui.fontawesome]}{/font} Скорость авточтения"
    old "{font=[gui.fontawesome]}{/font} Music Volume"
    new "{font=[gui.fontawesome]}{/font} Громкость музыки"
    old "{font=[gui.fontawesome]}{/font} Sound Volume"
    new "{font=[gui.fontawesome]}{/font} Громкость звуков"
    old "{font=[gui.fontawesome]}{/font} Test"
    new "{font=[gui.fontawesome]}{/font} Тест"
    old "{font=[gui.fontawesome]}{/font} Voice Volume"
    new "{font=[gui.fontawesome]}{/font} Громкость голоса"
    old "{font=[gui.fontawesome]}{/font} Mute All"
    new "{font=[gui.fontawesome]}{/font} Без звука"
    old "The dialogue history is empty."
    new "История диалогов пуста."
    old "{font=[gui.fontawesome]}{/font} Total"
    new "{font=[gui.fontawesome]}{/font} Всего"
    old "{font=[gui.fontawesome]}{/font} Characters +2"
    new "{font=[gui.fontawesome]}{/font} Персонажи +2"
    old "{font=[gui.fontawesome]}{/font} Music +1"
    new "{font=[gui.fontawesome]}{/font} Музыка +1"
    old "{font=[gui.fontawesome]}{/font} Replay +1"
    new "{font=[gui.fontawesome]}{/font} Повтор +1"
    old "{font=[gui.fontawesome]}{/font} Replay +3"
    new "{font=[gui.fontawesome]}{/font} Повтор +3"
    old "{font=[gui.fontawesome]}{/font} Characters +1"
    new "{font=[gui.fontawesome]}{/font} Персонажи +1"
    old "{font=[gui.fontawesome]}{/font} Concept +1"
    new "{font=[gui.fontawesome]}{/font} Концепция +1"
    old "{font=[gui.fontawesome]}{/font} Gallery +3"
    new "{font=[gui.fontawesome]}{/font} Галерея +3"
    old "{font=[gui.fontawesome]}{/font} Gallery +2"
    new "{font=[gui.fontawesome]}{/font} Галерея +2"
    old "{font=[gui.fontawesome]}{/font} Music +2"
    new "{font=[gui.fontawesome]}{/font} Музыка +2"
    old "{font=[gui.fontawesome]}{/font} Gallery +1"
    new "{font=[gui.fontawesome]}{/font} Галерея +1"
    old "{font=[gui.fontawesome]}{/font} Gallery +5"
    new "{font=[gui.fontawesome]}{/font} Галерея +5"
    old "{font=[gui.fontawesome]}{/font} Concept +2"
    new "{font=[gui.fontawesome]}{/font} Концепция +2"
    old "{font=[gui.fontawesome]}{/font} Diary +15"
    new "{font=[gui.fontawesome]}{/font} Дневник +15"
    old "{font=[gui.fontawesome]}{/font} Diary +1"
    new "{font=[gui.fontawesome]}{/font} Дневник +1"
    old "Back to the bridge!"
    new "Назад к мосту!"
    old "Extras"
    new "Дополнительно"
    old "{font=[gui.fontawesome]}{/font} Open"
    new "{font=[gui.fontawesome]}{/font} Открыть"
    old "{font=[gui.fontawesome]}{/font} Gift"
    new "{font=[gui.fontawesome]}{/font} Подарок"
    old "{font=[gui.fontawesome]}{/font} Delete"
    new "{font=[gui.fontawesome]}{/font} Удалить"
    old "{font=[gui.fontawesome]}{/font} Install"
    new "{font=[gui.fontawesome]}{/font} Устанавливать"
    old "{font=[gui.fontawesome]}{/font} Add to cart"
    new "{font=[gui.fontawesome]}{/font} Добавить в корзину"
    old "{font=[gui.fontawesome]}{/font} Start"
    new "{font=[gui.fontawesome]}{/font} Начать"
    old "Original Sound Track"
    new "Оригинальный саундтрек"
    old "{font=[gui.fontawesome]}{/font} Manual"
    new "{font=[gui.fontawesome]}{/font} руководство"
    old "Digital Art Book"
    new "Цифровая художественная книга"
    old "{font=[gui.fontawesome]}{/font} View"
    new "{font=[gui.fontawesome]}{/font} вид"
    old "Digital Concept Book"
    new "Цифровая концепция книга"
    old "MOD Creator Development Kit"
    new "Комплект разработчика для разработчиков MOD"
    old "Back to the Basic"
    new "Вернуться к основной"
    old "Tarot PNP Pack"
    new "Таро PNP пак"
    old "Please wait for more update."
    new "Пожалуйста, ждать больше обновлений."
    old "Skipping"
    new "Пропускаю"
    old "{font=[gui.fontawesome]}{/font} Language"
    new "{font=[gui.fontawesome]}{/font} Язык"
    old "{font=[gui.fontawesome]}{/font} Vibrate"
    new "{font=[gui.fontawesome]}{/font} Вибрировать"
    old "{font=[gui.fontawesome]}{/font} Controller"
    new "{font=[gui.fontawesome]}{/font} Контроллер"
    old "{font=[gui.fontawesome]}{/font} Disable"
    new "{font=[gui.fontawesome]}{/font} Отключить"
    old "Do not display any Controller images."
    new "Не показывать иконки контроллера."
    old "{font=[gui.fontawesome]}{/font} Steam Controller"
    new "{font=[gui.fontawesome]}{/font} Контроллер Steam"
    old "Display the Steam Controller images."
    new "Показывать иконки контроллера Steam."
    old "{font=[gui.fontawesome]}{/font} General Gamepad"
    new "{font=[gui.fontawesome]}{/font} Обычный геймпад"
    old "{font=[gui.fontawesome]}{/font} {s}OUYA Controller{/s}"
    new "{font=[gui.fontawesome]}{/font} {s}Контроллер OUYA{/s}"
    old "Display the Xbox Controller images."
    new "Показывать иконки контроллера Xbox."
    old "Display the OUYA Controller images."
    new "Показывать иконки контроллера OUYA."
    old "{font=[gui.fontawesome]}{/font} Tic disorder"
    new "{font=[gui.fontawesome]}{/font} Тик-расстройство"
    old "This will activate Ga-yeon's tic disorder."
    new "Эта опция включает нервный тик у Га-Йан."
    old "This will deactivate Ga-yeon's tic disorder."
    new "Эта опция выключает нервный тик у Га-Йан."
    old "{font=[gui.fontawesome]}{/font} Epilepsy-friendly"
    new "{font=[gui.fontawesome]}{/font} Режим для эпилептиков"
    old "This will disable some screen effects for people who have epilepsy or similar photosensitive disorders."
    new "Эта опция выключает некоторые эффекты, способные вызвать приступ эпилепсии или других светочувствительных расстройств."
    old "{font=[gui.fontawesome]}{/font} Blind-friendly"
    new "{font=[gui.fontawesome]}{/font} Режим для слепых"
    old "This will activate the blind-friendly features with the self-voicing feature."
    new "Активация режима для слепых."
    old "This will disable the blind-friendly features."
    new "Деактивация режима для слепых."
    old "Reset"
    new "Сброс"
    old "Directing, Design, Programming, Music, Sound, Writing, UI Design, Background CG, Object Sprites, Packaging, Video, Website -From April 21, 2013"
    new "режиссура, дизайн, программирование, музыка, звук, сюжет, пользовательский интерфейс, бэкграунды и комьютерная графика, спрайты, упаковка файлов, видео, работа с сайтов - с 21 апреля 2013"
    old "Animation, Character Sprites, CG Sprites -From March 10, 2015"
    new "анимация, спрайты женских персонажей, компьютерная графика - с 10 марта 2015"
    old "English Translation Adviser -June 3, 2015~July 1, 2017"
    new "консультант по переводу - с 3 июня 2015 по 1 июля 2017"
    old "English Translator -April 11, 2015~June 10, 2016"
    new "английская локализация - с 11 апреля 2015 по 10 июнь 2016"
    old "Chinese Translator -July 25, 2016~February 10, 2018"
    new "Китайская локализация -с 25 июля2016 по 10 февраля 2018"
    old "Russian Translator -August 28, 2016~December 7, 2017"
    new "русская локализация -с 28 август 2016 по 7 декабря 2017"
    old "Epilepsy Adviser -November 15, 2015~November 20, 2015"
    new "консультант по вопросам эпилепсии - с 15 ноября 2015 по 20 ноября 2015"
    old "Project Leader in Spanish, Spanish Translator -From May 29, 2017"
    new "руководитель проекта на испанском языке, испанская локализация -с 29 май 2017"
    old "Spanish Editor -From May 29, 2017"
    new "испанский редактор -с 29 май 2017"
    old "Spanish Translator -From May 29, 2017"
    new "испанская локализация -с 29 май 2017"
    old "Male sprites, CG sprites -April 8, 2015~September 13, 2015"
    new "спрайты мужских персонажей, компьютерная графика - с 8 апреля 2015 по 13 сентября 2015"
    old "Unofficial Demo Sprites -January 5, 2015~February 25, 2015"
    new "неофициальные пробные спрайты - с 5 января 2015 по 25 февраля 2015"
    old "English Demo Translation Adviser -June 3, 2015~June 14, 2015"
    new "консультант по пробным локализациям - с 3 июня 2015 по 14 июня 2015"
    old '{font=[gui.fontawesome]}{/font} Old Version'
    new '{font=[gui.fontawesome]}{/font} Старая версия'
    old "{font=[gui.fontawesome]}{/font} Authors"
    new "{font=[gui.fontawesome]}{/font} Авторское право"
    old "{font=[gui.fontawesome]}{/font} Photographers"
    new "{font=[gui.fontawesome]}{/font} Фотографы"
    old "{font=[gui.fontawesome]}{/font} Contributors"
    new "{font=[gui.fontawesome]}{/font} Пожертвования"
    old "{font=[gui.fontawesome]}{/font} Rooters"
    new "{font=[gui.fontawesome]}{/font} Поддержка и помощь"
    old '{font=[gui.fontawesome]}{/font} Special Thanks To'
    new '{font=[gui.fontawesome]}{/font} Особая благодарность'
    old "ACOC, Aiman Sharul, Axel Mertes, Bgame, Brandon Tanimoto, Brian Connors, BRISAK Kim Doohyeon, cheif.choi, Choi Irang, Choi Jihye, cloture, Danielle Bell, Edward N Puckering, Gary King, Gwak Jaeryeol, Han Ihyeong, Hoe Namyoon, Hong Eunki, Hwang Daehoon, Hyojoon, James Emmerson, Jeong Dongwon, Jeong Wookjin, Jeong Yoonsoo, Jianmin Zhang,\nKarina Schulze, Keira Val\'Azr, Kim Hanseol, Kim Hyeoncheol, Kim Jaeseong, Kim Jeongwoong, Kim Myeongwook,\nLee Changki, Lee Eunji, Lee Gunhae, Lee Hyejin, Lee Jaewi, Light Twins, Lim Jisoo, Maddy Wootton,\nMarshall Proudfoot, Mirumu, Mojaeng, Oh Hyeonjun, Park Hyeonjun, Park JoonKoo, Rewind, Sander Tieleman, srwss, Sung Chanaul, YottaCho, Zerial.net"
    new "ACOC, Aiman Sharul, Axel Mertes, Bgame, Brandon Tanimoto, Brian Connors, BRISAK Kim Doohyeon, cheif.choi,\nChoi Irang, Choi Jihye, cloture, Danielle Bell, Edward N Puckering, Gary King, Gwak Jaeryeol, Han Ihyeong,\nHoe Namyoon, Hong Eunki, Hwang Daehoon, Hyojoon, James Emmerson, Jeong Dongwon, Jeong Wookjin,\nJeong Yoonsoo, Jianmin Zhang, Karina Schulze, Keira Val\'Azr, Kim Hanseol, Kim Hyeoncheol, Kim Jaeseong,\nKim Jeongwoong, Kim Myeongwook, Lee Changki, Lee Eunji, Lee Gunhae, Lee Hyejin, Lee Jaewi, Light Twins,\nLim Jisoo, Maddy Wootton, Marshall Proudfoot, Mirumu, Mojaeng, Oh Hyeonjun, Park Hyeonjun, Park JoonKoo, Rewind, Sander Tieleman, srwss, Sung Chanaul, YottaCho, Zerial.net"
    old "Caz Woolley, Game Dev Robot, Gamsadev, Indie GameDev Bot, Indie Game Lover, Indie Games Devel, IndieVideoGames, Joachim Dimitri Jensen, Kim Kyeongtae, Kim Younghwan, Kurt Simon, Linda Lee King, Peter Christiansen, Sakimichi, Sebastian Haba, Spero Mcgee, The Indie Sloth, Vrachos, Xin Liu, Yu Shinhyeon"
    new "Caz Woolley, Game Dev Robot, Gamsadev, Indie GameDev Bot, Indie Game Lover, Indie Games Devel, IndieVideoGames, Joachim Dimitri Jensen, Kim Kyeongtae, Kim Younghwan, Kurt Simon, Linda Lee King,\nPeter Christiansen, Sakimichi, Sebastian Haba, Spero Mcgee, The Indie Sloth, Vrachos, Xin Liu, Yu Shinhyeon"
    old "{font=[gui.fontawesome]}{/font} The information is unknown at this time."
    new "{font=[gui.fontawesome]}{/font} В настоящее время информация неизвестна."
    old "{b}Choi Ga-yeon{/b}"
    new "{b}Цуи Га-Йан{/b}"
    old "{b}Birth:{/b} April 19th, 1986"
    new "{b}Дата рождения:{/b} 19.04.1986"
    old "{b}Blood Type:{/b} A(RH+)"
    new "{b}Группа крови:{/b} II(+)"
    old "{b}Height / Weight:{/b} 165cm / 48kg"
    new "{b}Рост/Вес:{/b} 165 см / 48 кг"
    old "{b}BWH:{/b} 81cm / 58cm / 86cm"
    new "{b}Обхват груди/живота/талии, см:{/b} 81/58/86 "
    old "{b}Bio:{/b} Discouraged worker, Temporary absence from Health Administration of Yonsei University"
    new "{b}Биография:{/b} отчаявшийся работник, временно отстранена от работы в Администрации здравоохранения Университета Йонсей"
    old "{b}Bio:{/b} Discouraged worker, Temporary absence from Health Administration of ○○ University"
    new "{b}Биография:{/b} отчаявшийся работник, временно отстранена от работы в Администрации здравоохранения Университета ○○"
    old "{b}Certificates:{/b} 1st class Hospital Coordinator, Hospital Administrator"
    new "{b}Сертификаты:{/b} больничный координатор 1-го класса, Администратор больницы"
    old "{b}Likes:{/b} Bagels, Margherita pizza, Sweet rice bun"
    new "{b}Любит:{/b} бублики, пиццу \"Маргарита\", сладкие рисовые булочки"
    old "{b}Dislikes:{/b} Capitalism, Doctors, Members of Parliament"
    new "{b}Не любит:{/b} капитализм, членов парламента, докторов"
    old "{b}Choi Hye-na{/b}"
    new "{b}Цуи Хаи-На{/b}"
    old "{b}Birth:{/b} June 17th, 1989"
    new "{b}Дата рождения:{/b} 17.06.1989"
    old "{b}Blood Type:{/b} O(RH+)"
    new "{b}Группа крови:{/b} I(+)"
    old "{b}Height / Weight:{/b} 168cm / 48kg"
    new "{b}Рост/Вес:{/b} 168 см / 48 кг"
    old "{b}BWH:{/b} 92.5cm / 66cm / 92cm"
    new "{b}Обхват груди/живота/талии, см:{/b} 92,5/66/92"
    old "{b}Bio:{/b} Karaoke helper, Graduated in Tourism Food & Beverage of Korea Hotel Technical College"
    new "{b}Биография:{/b} ведущая в караоке, окончила факультет туризма и ресторанного дела в Korea Hotel Technical College"
    old "{b}Bio:{/b} Karaoke helper, Graduated in Tourism Food & Beverage of ○○"
    new "{b}Биография:{/b} ведущая в караоке, окончила факультет туризма и ресторанного дела в ○○"
    old "{b}Certificates:{/b} 2nd class Barista"
    new "{b}Сертификаты:{/b} бариста 2го класса"
    old "{b}Likes:{/b} Money, Photography, Ga-yeon, Drinking"
    new "{b}Любит:{/b} деньги, фотографию, Га-Йан, выпивку"
    old "{b}Dislikes:{/b} Oryide, Sweet rice bun, Nightclub"
    new "{b}Не любит:{/b} пьяных, сладкие рисовые пирожные, ночные клубы"
    old "{b}Lee Seol-ah{/b}"
    new "{b}Ли Сио-Ля{/b}"
    old "{b}Birth:{/b} December 7th, 1986"
    new "{b}Дата рождения:{/b} 07.12.1986"
    old "{b}Died:{/b} October 3rd, 2006"
    new "{b}Дата смерти:{/b} 03.10.2006"
    old "{b}Height / Weight:{/b} 158cm / 55kg"
    new "{b}Рост/Вес:{/b} 158 см / 55 кг"
    old "{b}BWH:{/b} 89cm / 68.5cm / 85cm"
    new "{b}Обхват груди/живота/талии, см:{/b} 89/68,5/85"
    old "{b}Bio:{/b} Maid of Lauah"
    new "{b}Биография:{/b} прислужница у Lauah"
    old "{b}Certificates:{/b} Craftsman Piano Tuner"
    new "{b}Сертификаты:{/b} настройщик пианино Craftsman"
    old "{b}Likes:{/b} Ga-yeon, Herself, Papa, Taejin"
    new "{b}Любит:{/b} Га-Йан, себя, отца, Та-Цина"
    old "{b}Dislikes:{/b} Kelial, Mother, Tobacco, Truck"
    new "{b}Не любит:{/b} Kelial, мать, табак, грузовики\n{b}{color=#ff0000}Примечание:{/color}{/b} Lauah и Kelial это имена ангелов, информацию о которых можно найти в книге \"Полная система магии Золотой Зари\" Израэля Регарди и в других источниках"
    old "{b}Staff{/b}"
    new "{b}Персонал{/b}"
    old "{b}Clerk{/b}"
    new "{b}Менеджер{/b}"
    old "{b}Park Misun{/b}"
    new "{b}Парк Ми-Сан{/b}"
    old "{b}Birth:{/b} April 28th, 1974"
    new "{b}Дата рождения:{/b} 28.04.1974"
    old "{b}Height / Weight:{/b} 168cm / 47kg"
    new "{b}Рост/Вес:{/b} 168 см / 47 кг"
    old "{b}BWH:{/b} 90cm / 63.8cm / 89cm"
    new "{b}Обхват груди/живота/талии, см:{/b} 90/63,8/89"
    old "{b}Bio:{/b} Conductor of Business Management in Arno Restaurant franchise, Essayist, Graduated in SNU Business School"
    new "{b}Биография:{/b} руководитель отдела управления персоналом сети ресторанов \"Арно\", пишет эссе, окончила Школу Бизнеса при НУС (Национальном университете Сеула)"
    old "{b}Bio:{/b} Conductor of Business Management in Arno Restaurant franchise"
    new "{b}Биография:{/b} руководитель отдела управления персоналом сети ресторанов \"Арно\""
    old "{b}Certificates:{/b} Doctor of Business Administration, Advanced level of TEPS, Special level of TESAT, Top level of MK TEST"
    new "{b}Сертификаты:{/b} доктор делового администрирования, продвинутый уровень английского по TEPS, особый уровень TESAT, наивысший уровень MK TEST (квалификационные тесты в Корее)"
    old "{b}Likes:{/b} Acoustic guitar, Challenge, Taejin, Writing"
    new "{b}Любит:{/b} акустические гитары, вызовы, Та-Цина, писать"
    old "{b}Dislikes:{/b} Electronic products, Game, Mantis, Sloth"
    new "{b}Не любит:{/b} электронику, игры, богомолов, лень"
    old "{b}Interviewer{/b}"
    new "{b}Рекрутер{/b}"
    old "{b}Birth:{/b} Top Secret"
    new "{b}Дата рождения:{/b} Секретные данные"
    old "{b}Height / Weight:{/b} Top Secret"
    new "{b}Рост/Вес:{/b} Секретные данные"
    old "{b}BWH:{/b} Top Secret"
    new "{b}BWH:{/b} Секретные данные"
    old "{b}Bio:{/b} Conductor of Business Management in ○○"
    new "{b}Биография:{/b} руководитель отдела управления персоналом сети ресторанов \"○○\""
    old "{b}Kim Yunwoo{/b}"
    new "{b}Ким Янву{/b}"
    old "{b}Birth:{/b} January 19th, 1986"
    new "{b}Дата рождения:{/b} 19.01.1986"
    old "{b}Blood Type:{/b} AB(RH+)"
    new "{b}Группа крови:{/b} IV(+)"
    old "{b}Height / Weight:{/b} 172cm / 58kg"
    new "{b}Рост/Вес:{/b} 172 см / 58 кг"
    old "{b}Bio:{/b} Bassist of The Ghost Crying"
    new "{b}Биография:{/b} бассист группы \"Плачущий призрак\""
    old "{b}Bio:{/b} Bassist of ○○"
    new "{b}Биография:{/b} бассист группы \"○○\""
    old "{b}Likes:{/b} Bob Dylan, Choi Ga-yeon, Yu Jaeha"
    new "{b}Любит:{/b} Боба Дилана, Цуи Га-Йан, Yu Jaeha"
    old "{b}Dislikes:{/b} Auditions, Management, Soju"
    new "{b}Не любит:{/b} проходить прослушивания, менеджмент, сою"
    old "{b}Choi Taejin{/b}"
    new "{b}Цуи Та-Цин{/b}"
    old "{b}Birth:{/b} March 28th, 1986"
    new "{b}Дата рождения:{/b} 28.03.1986"
    old "{b}Blood Type:{/b} B(RH+)"
    new "{b}Группа крови:{/b} II(+)"
    old "{b}Height / Weight:{/b} 182cm / 73kg"
    new "{b}Рост/Вес:{/b} 182см / 73 кг"
    old "{b}Bio:{/b} Lead Guitarist of The Ghost Crying, Graduated in Seoul Institute of the Arts"
    new "{b}Биография:{/b} ведущий гитарист группы \"Плачущий призрак\", окончил Сеульский институт искусства"
    old "{b}Bio:{/b} Lead Guitarist of ○○, Graduated in ○○"
    new "{b}Биография:{/b} ведущий гитарист группы \"○○\", окончил ○○"
    old "{b}Certificates:{/b} Bachelor of Arts Degree in Gebrauchsmusik"
    new "{b}Сертификаты:{/b} бакалавр искусств по прикладной музыке"
    old "{b}Likes:{/b} Marylin Manson, NIN, Rammstein, Shin Junghyeon,\nShin Haechul"
    new "{b}Любит:{/b} Marylin Manson, NIN, Rammstein, Shin Junghyeon,\nShin Haechul"
    old "{b}Dislikes:{/b} Eggplant, Ginger, Idol"
    new "{b}Не любит:{/b} баклажаны, рыжих, идолов"
    old "{b}Park Hyeongsik{/b}"
    new "{b}Парк Хьюгон-Щи{/b}"
    old "{b}Birth:{/b} December 17th, 1979"
    new "{b}Дата рождения:{/b} 17.01.1979"
    old "{b}Bio:{/b} Physician, Graduated in School of Medicine of Sungkyunkwan University"
    new "{b}Биография:{/b} врач-терапевт, окончил Школу медицины университета Сюнгюнгван"
    old "{b}Bio:{/b} Physician, Graduated in ○○"
    new "{b}Биография:{/b} врач-терапевт, окончил Школу ○○"
    old "{b}Certificates:{/b} Medical Licence"
    new "{b}Сертификаты:{/b} врачебная лицензия"
    old "{b}Likes:{/b} Fame, Money, Power"
    new "{b}Любит:{/b} славу, деньги, власть"
    old "{b}Dislikes:{/b} Capitalism, Members of Parliament, Soju"
    new "{b}Не любит:{/b} капитализм, членов парламента, сою"
    old "{b}Doctor{/b}"
    new "{b}Доктор{/b}"
    old "{b}Bio:{/b} Physician"
    new "{b}Биография:{/b} врач-терапевт"
    old "{font=[gui.fontawesome]}{/font} Stop"
    new "{font=[gui.fontawesome]}{/font} Стоп"
    old "{font=[gui.fontawesome]}{/font} Shuffle"
    new "{font=[gui.fontawesome]}{/font} Повтор"
    old "{font=[gui.fontawesome]}{/font} Loop"
    new "{font=[gui.fontawesome]}{/font} Петля"
    old "{font=[gui.fontawesome]}{/font} Previous"
    new "{font=[gui.fontawesome]}{/font} Пред"
    old "{font=[gui.fontawesome]}{/font} Next"
    new "{font=[gui.fontawesome]}{/font} След"
    old "{font=[gui.fontawesome]}{/font} Random"
    new "{font=[gui.fontawesome]}{/font} Случайная"
    old "{font=[gui.fontawesome]}{/font} Bandcamp"
    new "{font=[gui.fontawesome]}{/font} Bandcamp"
    old "{font=[gui.fontawesome]}{/font} Soundcloud"
    new "{font=[gui.fontawesome]}{/font} Soundcloud"
    old "{font=[gui.fontawesome]}{/font} Add to cart"
    new "{font=[gui.fontawesome]}{/font} Добавить в корзину"
    old '{size=[gui.quick_button_text_size]}Stop{/size}'
    new '{size=[gui.quick_button_text_size]}Стоп{/size}'
    old '{size=[gui.quick_button_text_size]}Previous{/size}'
    new '{size=[gui.quick_button_text_size]}Пред{/size}'
    old '{size=[gui.quick_button_text_size]}Next{/size}'
    new '{size=[gui.quick_button_text_size]}След{/size}'
    old '{size=[gui.quick_button_text_size]}Loop{/size}'
    new '{size=[gui.quick_button_text_size]}Петля{/size}'
    old '{size=[gui.quick_button_text_size]}Shuffle{/size}'
    new '{size=[gui.quick_button_text_size]}Повтор{/size}'
    old "Prologue"
    new "Пролог"
    old "Discouraged Worker"
    new "Отчаявшийся работник"
    old "Depressive Disorder"
    new "Депрессивное расстройство"
    old "Reclusive Outsider"
    new "Затворник"
    old "IMF Crisis"
    new "Азиатский экономический кризис"
    old "Anxiety Disorder"
    new "Тревожное расстройство"
    old "Medical Referral"
    new "Медицинское направление"
    old "Bridge of the Life"
    new "Мост жизни"
    old "Epilogue"
    new "Эпилог"
    old "Accident"
    new "Несчастный случай"
    old "Flowery Mornings and Moonlit Nights"
    new "Утра, полные цветов, и ночи, залитые лунным светом"
    old "Red Dialogue Window"
    new "Красное диалоговое окно"
    old "Seohae Grand Bridge"
    new "Мост Сойи"
    old " A discouraged worker is a person of legal employment age who is not actively seeking employment, or who can not find employment after long-term unemployment. This is usually because an individual has given up looking or has had no success in finding a job, hence the term \"discouraged\".\n\n{a=https://en.wikipedia.org/wiki/Discouraged_worker}Wikipedia{/a}\n\n Discouraged workers are classified as an economically inactive population and not included in the unemployment rate, although they are actually unemployed.\n\n And this artificially causes a decrease in the unemployment rate in official statistics, in spite of an actually higher unemployment rate. In the case of Korea, the Subsidiary Employment Index, which includes the not-calculated unemployed, was reported first in November, 2014, and accordingly, the hidden problems in Korea's employment-population ratio and discouraged workers have surfaced."
    new " Отчаявшийся работник это человек работоспособноного возраста, который не ищет или не может найти работу в течении длительного периода времени. Это происходит из-за того, что человек не достигает в этом никаких успехов и сдаётся. Отсюда и термин \"отчаявшийся\".\n\n Таких людей принято считать экономически неактивным населением и не вносить их в статистику безработных, хотя по факту они таковыми и являются.\n\n Этот шаг искусственно понижает уровень безработицы в официальной статистике. В Корее вспомогательный индекс занятости, который учитывает неучтённых безработных, впервые опубликовали в ноябре 2014. Благодаря этому стали заметны скрытые проблемы рынка труда \"всплыли\" отчаявшиеся."
    old " Reclusive outsider is the phenomenon of reclusive adolescents or adults who withdraw from social life, often seeking extreme degrees of isolation and confinement. The term reclusive outsider refers to both the sociological phenomenon in general as well as to people belonging to this societal group.\n\n{a=https://en.wikipedia.org/wiki/Hikikomori}Wikipedia{/a}\n\n Choi Ga-yeon, a heroine of \"Discouraged Workers\", suffered from depressive disorder because of the sudden firing from her job and breaking-up with her lover.\n\n In addition, with her continuous failure to get a job, her anxiety disorder symptoms only became worse. And she naturally has become a hikikomori(a person who becomes a recluse and gives up any social life) after she gave up trying to get a job."
    new " Феномен затворничества касается подростков и взрослых, которые намеренно вычёркивают себя из общественной жизни, иногда уходя в крайнюю изоляцию. Этот термин характеризует как явление в целом, так и принадлежащих к нему людей.\n\n Цуи Га-Йан, героиня \"Отчаявшихся работников\", страдает от депрессивного расстройства, вызванного внезапной потерей работы и расставанием с любимым.\n\n В дополнение к этому идут её неудачи в последующих поисках работы. В итоге можно сказать, что она практически стала \"хикикомори\", после того как бросила поиски работы."
    old " Generally, a medical referral is issued by a hospital when sending a patient to another hospital. Ga-yeon has received medical treatment from a psychiatrist since she was fired from the hospital where she was working as a coordinator. In spite of long treatment, her condition did not improve at all, and the hospital issued a medical referral to another hospital. But Ga-yeon refused the referral as she felt the psychiatrist gave up on her, and this made her fall into despair. So she didn't seek any more psychiatric treatment.\n\n Since many people still think negatively about seeking psychiatric treatment, and have unfavorable perceptions about those who seek it, often, people who need help with their problems, tend to avoid getting the help they need, both here in Korea and elsewhere in the world.\n\n Also in the case of Ga-yeon, she hasn't talked about it, regarding it as her embarrassing secret. The medical referral Yunwoo found in Ga-yeon's mailbox was actually a referral that Hye-na arranged for her.\n\n Actually, the description shown in the medical referral in the \"Ga-yeon and Yunwoo\" part of the story, is almost the same as the one commonly issued in a real hospital in Korea."
    new " Как правило, медицинское направление выдается одной больницей при отправке больного в другую. Га-Йан получала психиатрическую помощь с самого момента увольнения из госпиталя, где она работала координатором. Несмотря на длительное лечение ей не удалось полностью поправиться, из-за чего врач решил продолжить её лечение в другой клинике. Но она решила, что психиатр просто отмахнулся от неё, что так же негативно сказалось на ней. Поэтому она решила бросить лечение вообще.\n\n Многие люди относятся к психиатрической помощи скептически или даже негативно. Большинство людей, который необходима подобная помощь, стараются всеми силами её избегать, стараясь закрывать глаза на проблему, а не пытаться решить её. Данная тенденция характерна как для Кореи, так и для мира в общем.\n\n Га-Йан никому об этом не говорила, сделав это своим секретом. Направление в почтовом ящике нашёл Янву, а попало оно туда стараниями Хай-ны.\n\n На самом деле рецепт, указанный в направлении из главы \"Га-Йан и Янву\" практически полностью идентичен тому, который реально используется при лечении в корейских клиниках."
    old " Anxiety disorders are a category of mental disorders characterized by feelings of anxiety and fear, where anxiety is a worry about future events and fear is a reaction to current events. These feelings may cause physical symptoms, such as a racing heart and shakiness.\n\n{a=https://en.wikipedia.org/wiki/Anxiety_disorder}Wikipedia{/a}\n\n My mother had suffered from panic disorder for almost eight years, and she used to complain of pain and hyperpnea in certain and sometimes new and unexpected situations(Hyperpnea is the need to breathe more deeply because the person experiencing it feels light headed or otherwise feels they need more oxygen for various reasons.).\n\n And someone whom I know had anxiety disorder, and she suffered from a tic disorder including repetitive eye blinking and apnea when she feels anxiety in those same kinds of situations. She was even very dependent on alcohol and showed symptoms of caffeine addiction as well. Standing by my mother's and her side, and watching their pain and experiencing it with them, I hoped to help set them free from those painful days. But as time went by, I found I was getting numb with their pain, and at that moment, I felt extremely ashamed as a human being."
    new " Тревожное расстройство это один из водов душевных расстройств, характеризующееся чувством тревоги и страха, которые возникают из-за беспокойства перед будущими событиями и страхом перед событиями текущими. Расстройство может стать причиной учащенного сердцебиения и нервной дрожи.\n\n Моя мать страдала от панического расстройства почти 8 лет и жаловалась на боли и чрезмерно глубокое дыхание при самых разных ситуациях. Она должна была дышать глубже, чем обычные люди, так как ей требовалось больше кислорода. В противном случае её преследовали головокружение или любые другие симптомы, указывающие на недостаток кислорода.\n\n Так же ещё одна моя знакомая была подвержена тревожному расстройству, сопровождающемуся нервным тиком, повторяющимся морганием и апноэ (остановкой дыхательных путей). У неё была зависимость от алкоголя и кофеина. Стоя вместе с матерью и ней, наблюдая за их страданиями и разделяя их я надеялся, что помогаю им пережить эти болезненные дни. Но время шло и я осознал, как был парализован их болью. Это сильно потрясло меня."
    old " Depressive disorder is a mental disorder characterized by a pervasive and persistent low mood that is accompanied by low self-esteem and by a loss of interest or pleasure in normally enjoyable activities. The term \"depression\" is used in a number of different ways. It is often used to mean this syndrome but may refer to other mood disorders or simply to a low mood. Major depressive disorder is a disabling condition that adversely affects a person's family, work or school life, sleeping and eating habits, and general health.\n\n{a=https://en.wikipedia.org/wiki/Major_depressive_disorder}Wikipedia{/a}\n\n Choi Ga-yeon, a heroine of \"Discouraged Workers\", suffered from depressive disorder because of the sudden firing from her job and breaking-up with her lover. In addition, with her continuous failure to get a job, her anxiety disorder symptoms only became worse. And she naturally has become a hikikomori(a person who becomes a recluse and gives up any social life) after she gave up trying to get a job."
    new " Депрессивное расстройство это один из видов душевных расстройств, характеризующееся крайним подавлением самооценки и интересом к нормальной жизни. Термин \"депрессия\" используется в разных случаях: как для обозначения собственно этого синдрома, так и других аффективных расстройств. Большое депрессивное расстройство это более широкое понятие, препятствующее нормальной работе, учёбе и жизнедеятельности, отрицательно влияющее как на самого человека, так и на его окружающих.\n\n Цуи Га-Йан, героиня \"Отчаявшихся работников\", страдает от депрессивного расстройства, вызванного внезапной потерей работы и расставанием с любимым.\n\n В дополнение к этому идут её неудачи в последующих поисках работы. В итоге можно сказать, что она практически стала \"хикикомори\", после того как бросила поиски работы."
    old " \"Bridge of the life\" was actually a sort of attempt using advanced technological methods to prevent suicide. By trying to have a conversation with a pedestrian through hopeful words and changing their desperation into hope, the designers thought suicidal people might be encouraged not to end their lives, but, in the event that failed, there was still the traditional physical anti-suicide barrier. The sensors mounted on every section of the bridge detects the exact location of a pedestrian as she/he walks by and the bridge lights the hopeful word up in the right position for a pedestrian to read.\n\n The very first bridge of life opened on Mapo Bridge, Korea on September 26, 2012, and was sponsored by Seoul City and Samsung Life Insurance. Mapo Bridge was chosen as the first installation of this new technology because it has been notorious as the place with the highest suicide rate. And the second one opened on Hangang Bridge, Korea on November 5, 2013, sponsored by Korea Health Promotional Foundation.\n\n And the ad for \"Bridge of the life\" received 39 awards in the International Advertising Festival and obtained excellent advertising effects. But regardless of this successful record, the rate of suicides by death leap has steadily increased. According to statistics, installing closed circuit television on the public bridges was more helpful in preventing suicide jumps and rescuing suicide jumpers who actually did jump than the bridge of life technology.\n\n As a result of the Samsung Life Insurance's decision to discontinue their operational support for \"Bridge of the Life\" on Mapo Bridge in September 2015, the automatic detection sensor has not worked since December 1, 2015 and the website of Bridge of the Life was also closed.\n\n In fact, Hangang Bridge wasn't yet built at the time that the \"Discouraged workers\" story takes place. But in the game, it was set as a background to let Yunwoo try to think where Ga-yeon disappeared to."
    new " \"Мост жизни\" это своего рода попытка предотвращения самоубийств продвинутыми техническими методами. В данном случае это попытка завязать с пешеходом беседу, используя обнадёживающие слова, написанные на поручнях моста. Специальные датчики фиксируют местонахождение пешехода и подсвечивают эти слова по мере движения. По задумке проектировщиков это должно было вселить надежду в отчаявшиеся сердца, однако эксперимент провалился.\n\n Первый \"мост жизни\" был открыт на мосту Мапо в Сеуле 26 сентября 2012 года. Инвестором выступили компания Samsung Life Insurance и город Сеул. Мост Мапо стал первым экспериментальным объектом, использующим данную технологию, так как на нём был зафиксирован высокий уровень самоубийств. Вторым был мост Ханган, открытый 5 ноября 2013 года. Спонсором выступил Рекламный Фонд Корейском Организации Здравоохранения.\n\n Рекламой для проекта могут послужить 39 наград на Международном Фестивале Рекламы. Однако несмотря на количество призов число самоубийств только увеличивается. Согласно статистике, установка системы видеонаблюдения на мостах оказывает гораздо большее влияние на предотвращение прыжков, а так же помогают при спасении тех, кто всё же прыгнул.\n\n В результате этого компания Samsung Life Insurance решила прекратить поддержку проекта на мосту Мапо в сентябре 2015 года, а датчики местоположения прекратили свою работу 1 декабря того же года. Официальный сайт проекта так же закрыт.\n\n На самом деле мост Ханган ещё не был достроен во время событий \"Отчаявшихся работников\". Однако в игре его изображение вставлено в качестве задника во время размышлений Янву о местонахождении Га-Йан."
    old " The Asian financial crisis was a period of financial crisis that gripped much of East Asia beginning in July 1997 and raised fears of a worldwide economic meltdown due to financial contagion.\n\n The crisis started in Thailand with the financial collapse of the Thai baht after the Thai government was forced to float the baht due to lack of foreign currency to support its fixed exchange rate, cutting its peg to the U.S. dollar, after exhaustive efforts to support it in the face of a severe financial over-extension that was in part real estate driven.\n\n{a=https://en.wikipedia.org/wiki/1997_Asian_financial_crisis#South_Korea}Wikipedia{/a}\n\n At the time, Thailand had acquired a burden of foreign debt that made the country effectively bankrupt even before the collapse of its currency. As the crisis spread, most of Southeast Asia and Japan saw slumping currencies, devalued stock markets and other asset prices, and a precipitous rise in private debt.\n\n Indonesia, South Korea and Thailand were the countries most affected by the crisis. Hong Kong, Laos, Malaysia and the Philippines were also hurt by the slump. Brunei, China, Singapore, Taiwan and Vietnam were less affected, although all suffered from a loss of demand and confidence throughout the region."
    new " Азиатский экономический кризис охватил восточную Азию в июле 1997 и по мнению многих мог стать причиной глобального кризиса.\n\n Точкой старта для него был Тайланд в следствии краха тайской валюты (бата), который правительство было вынуждено отпустить из-за отсутствия иностранной валюты для поддержания фиксированного обменного курса. Нехватку валюты вызвал сильный экономический рост и бурное развитие рынка недвижимости.\n\n В тот момент Тайланд имел огромный внешний долг, который сделал страну банкротом ещё до полного обвала бата. Кризис распространился на большинство стран Юго-Восточной Азии и Японию и характеризовался резким падением курса национальных валют, девальвацией фондовых рынков и цен на других активы. И как следствие - сильным увеличением доли частного долга.\n\n Индонезия, Южная Корея и Тайланд стали главными жертвами кризиса.  Гонконг, Лаос, Малайзия и Филиппины так же пострадали от него. Бруней, Китай, Сингапур, Тайвань и Вьетнам были затронуты в меньшей степени, хотя так же пострадали от потери спроса и уверенности."
    old " \"Accident\" tells what happens after \"Epilogue\" which is the basic ending of \"Discouraged Workers\".\n\n Ga-yeon reached out her hand toward Yunwoo, but at that moment, she blacked out and fell off the bridge. And Yunwoo threw himself into the river to save her. A few days later, they rose to the surface, and one passerby's report told their deaths to the world.\n\n If Yunwoo hadn't found his wallet, Ga-yeon would die alone while he was haggling over the taxi fare."
    new " \"Несчастный случай\" описывает события, произошедшие после \"Эпилога\", основной концовки \"Отчаявшихся работников\".\n\n Га-Йан протянула руку Янву, но в тот же момент отключилась и всё-таки упала с моста. Янву прыгнул за ней, пытаясь спасти. Через несколько дней их тела всплыли, а благодаря прохожему, который это увидел, весь мир узнал об их кончине.\n\n Если Янву не нашел свой бумажник, Га-Йан погибает одна, в то время как Янву торгуется с таксистом."
    old " As a hospital coordinator, Ga-yeon fell in love with a doctor at the hospital she was working in and they had an affair even though the doctor was a married man. When the director found out, she was fired. For over a year she tried to find another job, but her mental uneasiness eventually made her give up and she became a recluse.\n\n A year later, in the spring of 2013, her younger sister, Hye-na, and her first love Yunwoo come to her.\n\n A story about the dark side of today's youth and serious life events happening around Ga-yeon."
    new " Будучи координатором больницы, Га-йан влюбилась в своего коллегу доктора. У них завязался бурный роман даже не смотря на то, что сам доктор был женат. Когда директор больницы узнал об этом - её уволили. В течение года она безуспешно пыталась найти другую работу, но ее психическое здоровье в конце концов не подкосилось, и она закрылась в себе.\n\n Годом позже, весной 2013, её навестили младшая сестра Хаи-на и её первая любовь Янву.\n\n Эта история повествует о тёмной стороне современной молодёжи и серьёзных жизненных происшествиях, которые имели место в жизни Га-йан."
    old " \"Flowery Mornings and Moonlit Nights\" is the true ending which assumes that Ga-yeon didn't faint and grabbed Yunwoo's hand in \"Epilogue\". Originally \"Discouraged Workers\" was intended to end with the \"Accident\" story as the true ending. But after deciding to release it in the market, this was chosen as the true ending.\n\n Ga-yeon finds the culprit who spread the video, with the help of Yunwoo, and reports him to the police. After that, she tries to find a job, but it's still not easy for her. Even some interviewers who know her, hurt her.\n\n Yunwoo just stays by her side and tries to protect her without saying anything, and Hye-na helps Ga-yeon to work part-time at the cafe where she's working. Ga-yeon works hard every day, grateful for being allowed to work there. One day, the cafe manager gives her a letter of recommendation from the general manager of the head office, and Ga-yeon gets an opportunity to have an interview for a large affiliated store run by the head office. And by chance, the interviewer she meets with for the job is her old boss, who during her schooldays, originally gave her the idea of her dream job being a restaurant manager. Ga-yeon passes the interview with ease, and finally, she starts to move towards her dream."
    new " \"Утра, полные цветов, и ночи, залитые лунным светом\" это подлинная концовка, которая предполагает, что Га-Йан не теряла сознание и схватила руку Янву в \"Эпилоге\". Изначально подлинной концовкой был \"Несчастный случай\". Но после того, как я решил издать игру, то изменил своё решение.\n\n С помощью Янву Га-Йан находит человека, который слил видео в сеть, и сдают его в полицию. После этого она опять выходит на поиски работы, но это по прежнему даётся ей нелегко. Даже некоторые интервьюеры, которые знают ее, причинить ей боль.\n\n Янву остаётся с ней, пытаясь защитить, а Хаи-на помогает ей получить место в кафе, в котором работает сама. Га-Йан благодарна за эту возможность и каждый день усердно работает. Однажды, менеджер кафе дает ей рекомендательное письмо от генерального менеджера головного офиса, и Га-Йан получает возможность пройти собеседование в большом аффилированном магазине. И неожиданно интервьювером оказывается её старый босс, на которого она работала ещё в школе. Она с лёгкостью прошла собеседование и начала движение к своей мечте - работе менеджером ресторана."
    old " A chain reaction collision, involving 29 vehicles, happened at 7:50am on October 3, 2006, Korean time, on Seohae Grand Bridge in South Korea. This collision happened due to a thick fog, and it left 12 people dead and about 50 injured. According to the investigation, the accident occurred not only because of bad weather, but also because some drivers were speeding as well as shoulder riding. But whatever the reason was, the damage was almost 4 billion won, which was the most awful and costly accident in Korean car insurance history.\n\n \"Lee Seol-ah\" is a fictitious character who died in this accident. This woman, who died at the age of 21, still in the flower of her youth, visits the world she used to live in after she died, and watches people whom she loved and shared friendships with. One day, she meets Ga-yeon who helped her in the past. To prevent her death, she decides to help Yunwoo."
    new " Транспортная авария, столкновение 29 автомобилей, произошедшее в 7:50 утра 3 октября 2006 года на мосту Сойи в Сеуле. Причиной аварии стал густой туман, из-за которого погибло 12 и получило ранения около 50 человек. Согласно информации следствия, авария произошла не только из-за погодных условий, но и из-за превышения скорости некоторыми водителями. Но каковы бы ни были причины, ущерб составил почти 4 миллиарда вон, из-за чего событие стало самой страшной автомобильной аварией в корейской истории.\n\n \"Ли Сио-Ля\" это вымышленный персонаж, который погиб в этой катастрофе. Это девушка 21 года, покинувшая этот мир в столь прекрасном возрасте, по прежнему наблюдает за людьми, которых она любила или просто дружила. Однажды она увидела Га-Йан, которая помогла ей в прошлом. Чтобы предотвратить её смерть Сола решает помочь Янву."
    old " In \"Discouraged Workers\", a word box in red color is used to show the words and thoughts of Ga-yeon and a clerk Because when the basic scenario was developed, they are actually not alive.\n\n But when Ga-yeon is talking with her mom on the phone, the black box is used out of consideration for her mother."
    new " В игре используется текстовое окно красного цвета, в котором отражаются слова и мысли Га-Йан и девушки-менеджера. Это сделано из-за того, что во время написания основного сценария их уже нет в живых.\n\n Но когда Га-Йан говорит с матерью по телефону текстовое окно черного цвета. Это сделано из уважения к ней."
    old "{font=[gui.fontawesome]}{/font} Find the diary in the room."
    new "{font=[gui.fontawesome]}{/font} Найдите дневник в комнате."
    old "My cool captain!"
    new "Мой крутой супервайзер!"
    old "My captain's tear"
    new "Чудо-женщина тоже плачет"
    old "Went to see Yunwoo"
    new "Пошла повидаться с Янву"
    old "I rejected him"
    new "Я отвергнула его"
    old "As a friend"
    new "Как друг"
    old "My days in hospital"
    new "Больничные будни"
    old "Observing a doctor"
    new "Красавчик в белом халате"
    old "His wife"
    new "жена"
    old "Farewell"
    new "Прощание"
    old "I miss him"
    new "Я скучаю за ним"
    old "Sign"
    new "Знак"
    old "A lunatic"
    new "Лунатик"
    old "My friend, Eunju"
    new "Моя подруга Юнцзю"
    old "Getting a job"
    new "Новая работа"
    old "Rubbish and rubbish can"
    new "Мусорное ведро"
    old "Dying message"
    new "Предсмертное послание"
    old " It's been more than a month since I started working in a family restaurant. In the beginning, it was really hard to carry a tray and I even broke a few dishes. But now, I feel like I'm getting better and better. Sometimes, customers tip me as well, and also the other staff often praises my work. I'm especially good at…. hmmm…. well, it's too many to write them all down here! Later!\n\n However, the captain looks really cool. She's beautiful, smart, and also good at her work. Oh, she seems to be strong as well, as she usually carries heavy things by herself!\n\n I saw her carrying two metal trays stacked with dishes with just her two hands. It is hard even for men, but she's such a superwoman. How the hell can she do that? I hope I can do work as well as her someday."
    new " Вот уже больше месяца я работаю в семейном ресторане. Сначала мне было трудно держать поднос, я даже разбила несколько блюд! Но я прямо таки чувствую, как становлюсь лучше и лучше! Иногда мне оставляют хорошие чаевые, и даже некоторые коллеги хвалят меня. У меня особенно хорошо получается ... эээ ... ну ... в общем для всего тут места не хватит, я потом напишу!\n\n Мой супервайзер очень хороша: она красива, умна, и к тому же прекрасно справляется со своими обязанностями. И ещё, видимо, сильная, раз сама носит все эти тяжёлые штуки на работе!\n\n Я как-то видела, как она несла в каждой руке по тяжёлому металлическому подносу с едой. С этим даже не каждый парень справится! Она настоящая чудо-женщина, надеюсь когда-нибудь​ и я смогу работать так же."
    old " Today the section chief of the head office visited the restaurant. I thought the chief would be a man, but she was a young woman. She came to our restaurant and called the captain to the locker room. She passed by me while I was working there, and I saw her nametag. And I found she has the same name as a famous comedian. Funny!\n\n As the captain was not in the hall, I tried to look for her, and when I opened the door of the locker room, she looked at me in surprise and turned her face hurriedly. And she said leave her alone for a while, forcing me out of the room. She was crying.\n\n Probably the section chief made her cry. That bitch! What did the captain do wrong? Hey, I'll get even with her!! Shit!"
    new " Сегодня в ресторан из главного офиса пришла проверка. Я думала проверяющим будет мужчина, но пришла молодая девушка. Вместе с супервайзером они направились в дальнюю комнату. Когда она проходила мимо меня, мне удалось прочесть её имя на бейджике. Оказывается её зовут так же, как известного комика, забавно!\n\n Через какое-то время я отправилась на поиски супервайзера и когда открыла дверь в подсобку, то наткнулась на удивленный взгляд своей начальницы. Она сказала, что ей ещё немного нужно побыть одной и вытолкала меня за дверь. Она плакала.\n\n Это все проверяющая. Стерва! Чем провинилась супервайзер? Я с ней ещё разберусь!"
    old " I went to Cheolwon, with Eunyoung to see Yunwoo today. I didn't realize it was that cold, but when I got off the bus, I was just shocked as it was literally freezing. It didn't snow, and the wind didn't blow, but cold air made even my eyes freeze. Eunyoung and I hurried into the visitor's room to wait for Yunwoo.\n\n A few minutes later, a soldier came in - actually I recognized that he was Yunwoo as soon as I saw him! And I got the giggles. His camouflage patterned muffler looked pretty cool, but his earmuffs reminded me of a once famous singer, and I couldn't stop laughing!\n\n I told him about that singer, and he got embarrassed. Eunyoung took his earmuffs away and danced, and all of us burst into laughter.\n\n However, since we said goodbye to Yunwoo, I've felt somewhat lonesome, and I still feel that way even as I'm writing this…. why do I feel this way?"
    new " Я пошла в Хёлвон вместе с Юн-Янг, чтобы увидеть Янву сегодня. Я не думала, что будет так холодно, но выйдя из автобуса я реально замёрзла. Ветра не было, снега тоже, но от холодного воздуха у меня заболели глаза. Мы с Юн-Янг быстро вбежали в комнату для гостей и стали ждать.\n\n Спустя пару минут внутрь вошёл солдат, но я сразу разглядела в нём Янву! Его камуфляжный шарф и тёплые наушники напомнили мне прикид одного певца, из-за чего я громко рассмеялась!\n\n Я рассказала ему об этом певце и он растерялся. Юн-Янг сняла с него наушники и начала танцевать, из-за чего мы все расхохотались.\n\n После того, как мы попрощались с Янву я почувствовала какую-то грусть, может даже одиночество. И даже сейчас, набирая эти строки, я до сих пор чувствую ... почему?"
    old " After I parted with him, and while I was coming home, I tried really hard to fight back tears. But when I arrived in my room, I just burst into tears. Why? Why was I so mean to him? I raged at him, and told him to quit music. Why the hell did I do that?\n\n Today he told me what I've really looked forward to hearing from him, but why…. why couldn't I accept him? And why did I hurt him? I can't stop crying…."
    new " После того, как мы гуляли вместе и за то время, пока я шла домой, я усиленно пыталась сдержать слёзы. Но стоило мне переступить порог и они так и хлынули. Почему? Что я для него значу? Я же накричала на него и попросила бросить . Нахрена я это сделала?\n\n Сегодня он сказал мне то, что я хотела услышать от него, но ... почему я не могу принять его? И зачем причиняю боль? Не могу перестать рыдать ..."
    old " I had a long conversation with Yunwoo today;\n\n You've just been discharged from the army, and I'm a student without a job. So what can we do now? You really think we can get married and start our home? Seriously? How?\n\n Besides, we're not romantically involved with each other. We're just friends. I think of you as my friend, and hope we could get along well with each other for a long time. That's all….\n\n I think I probably said it like that…. but of course it's not true that I think of him just as a friend, but…. To get back to our relationship as usual, I had to say it that way.\n\n I also said sorry that I hurt him.\n\n However, unexpectedly, it seemed he doesn't care about it. He said he was actually kidding when he asked me to marry him. And since I already refused his proposal anyway, there's nothing hard about getting along with me simply as a friend.\n\n What he said made me a little bit regretful, but anyway, we decided to leave as good friends as we've always been."
    new " Сегодня у меня был длинный разговор с Янву:\n\n \"Ты только что уволился в запас, а я безработная студентка. И что же мы будем делать? Ты всерьез думаешь, что можем пожениться и начать новую жизнь? Серьёзно? Тем не менее, между нами нет сильных чувств. Мы просто друзья. Я считаю тебя своим другом и надеюсь, что мы сможем поладить. Но это всё ... \"\n\n Думаю, я как-то так и сказала. Но, конечно же, это враньё, ведь я не считаю его просто другом. Но чтобы вернуть наши отношения в старое русло, я должна была так сказать.\n\n Я так же извинилась перед ним за причиненную боль.\n\n Но, к моему удивлению, его это всё не сильно заботило. Он сказал, что предложение мне сделал в шутку. И раз я уже отклонила его, то нам ничего не мешает снова быть друзьями. \n\n От этих слов мне даже стало немного грустно, но в любом случае мы решили оставить всё как прежде."
    old " It's been almost a year since I started working in this hospital. I work as a coordinator of the hospital. I had my salary raised, and also I'm pretty satisfied with my job. My savings account with the balance which gets bigger and bigger makes me feel really happy.\n\n When I had to quit the university temporarily, I was just stunned. But now that I think about it, it was rather smart to do that, actually. Because of that choice, I was able to pay Hye-na's university tuition, without a loan.\n\n I'll save more money to send Mom and Daddy to travel on, and also support Hye-na until she gets married someday. Jeez, why is time passing so fast today? Until tomorrow, I'm going to bed!\n\n Ga-yeon, just keep it up as you've done so far!"
    new " Вот прошел уже почти год моей работы в клинике. Работы больничным координатором. Зарплата у меня хорошая, да и вообще мне здесь нравится. Цифры на моем банковском счёте становятся все больше и больше (что меня безусловно радует :) ).\n\n Когда мне пришлось временно бросить университет я была буквально ошарашена. Но сейчас я понимаю, что это был правильный выбор. Ведь из-за него я могла оплачивать учебу сестре Хаи-не сама, а не брать кредит на обучение.\n\n У меня даже были деньги, чтобы дать возможность родителям попутешествовать и помогать сестре, пока она не выйдет замуж. Господи, почему время летит так быстро? Ну всё, я спать.\n\n Га-Йан, просто не сходи с намеченной тропы!"
    old " Oh, my god…. how could he look like him that much? His face, way of talking, character, and even that he can't hold liquor well…. everything is just like him. He reminds me of Yunwoo a lot. And it makes me feel sad. And this keeps bothering me so much. These days, I'm often trying to speak to him, or be around him. He also seems to be interested in me, and sometimes talks to me, or brings some snack or drink. He looks like a pretty good man."
    new " Боже мой ... как они могут быть настолько похожи? Его лицо, манера говорить, характер. Да они оба даже пьянеют быстро. Он ОЧЕНЬ напоминает мне Янву. Это меня беспокоит и печалит. В последние дни я часто пыталась с ним заговорить или просто быть рядом. Кажется, он тоже ищет моей компании: может заговорить первым или даже угостит снэками или выпивкой. В общем создаёт впечатление хорошего человека."
    old " His wife visited the hospital. Though the Director and my lover prefer a simple and plain style, she dressed up too much, with luxurious dress and accessories. She looked just full of vanity. When I saw she's coquetting with him arm in arm, she really looked like an old fox. I can't imagine she's the Director's sister, and my lover's wife. She really makes me feel sick.\n\n When he and I were left alone because of night duty. he talked to me as if he was just working, because he knew we were being recorded on a CCTV.\n\n After finishing work, I got out of the hospital, and sat alone on the bench in front of the building. After a while, all lights were off in the hospital except one—Light from his office, coming through the blinds."
    new " Его жена пришла в клинику. Хотя директор и мой возлюбленный предпочитают простой и одноцветный стиль одежды, она была одета в роскошное платье с подобающими аксессуарами. От неё так и пёрло суетой. Когда я увидела, как они кокетничают друг с другом, держась за руки, то она напомнила мне старую лису. Не могу поверить, что она сестра директора и жена моего возлюбленного. От этого просто тошнит.\n\n Как-то мы остались с ним вдвоем на ночной смене. Он заговорил со мной на разные рабочие темы, потому что знал, что повсюду в больнице стоят камеры.\n\n После конца работы я вышла из клиники и селатю на скамейку перед зданием. Спустя мгновение во всех окнах погас свет. Во всех, кроме его кабинета."
    old " The director seemed to be trying hard not to hurt me, controlling his feelings. I understand he would feel betrayed as he has trusted me a lot, but he never swore at me at all, and treated me human to human. And now, I've finally realized what the hell I did. I felt really sorry for his wife, as she has never thought about this, and also felt sorry for the director who has always truly taken care of me. At the request of the Director, I decided to quit the hospital. I also said to him I would definitely break off my affair with the Doctor.\n\n After I packed up my stuff and got out of the hospital, I saw him running after me, but I just came out of the building and got into a taxi. In the running taxi, I just cried and cried. I could never see my colleagues there and the Director anymore…. and also him…. whom I made love with…. goodbye, everyone…. My greed has screwed up everything. Thank you all, and sorry…."
    new " Директор, казалось, старался держать себя в руках и не ранить меня очень сильно. Я понимаю, что он чувствовал себя преданным, поскольку он мне много доверял, но он никогда не кричал на меня и не относился ко мне, как к человеку. И теперь я наконец поняла, что, черт возьми, я натворила. Мне очень жаль его жену, поскольку она никогда об этом не думала, а также жалела директора, который всегда по-настоящему заботился обо мне. По просьбе директора я покинула больницу. Я также сказала ему, что я обязательно оборву все отношения с доктором.\n\n После того, как я собрала свои вещи и вышла из здания, я увидела, как он бежит за мной. Но я просто ускорилась и села в такси.\n\n Машина неслась по городу, а я просто ревела внутри. Я могу больше никогда не увидеть своих коллег и директора ... и его ... того, кому отдалась ... прощайте. Всему виной моя жадность. Спасибо вам всем ... и прощайте."
    old " Every single day, I cry, sleep, and wake from sleep, remember my good old days, especially with him, and then, cry, and fall asleep again. Beginning with a few days ago, I sometimes burst into laughter, and sometimes, burst into a fit of anger. I feel like I can't breathe well from time to time.\n\n I miss him. I miss him looking at me with a gentle smile. Thinking this makes me weepy, and it becomes hard to breathe. Also at this moment I'm writing this, I'm feeling really suffocated."
    new " Каждый божий день я плачу, сплю и просыпаюсь, вспоминая былые деньки. Плачу и снова засыпаю. А несколько дней назад меня стали посещать внезапные приступы смеха или гнева, из-за чего временами мне трудно дышать.\n\n Я скучаю за ним. Я скучаю за этим взглядом, за этой улыбкой. Из-за этих воспоминаний я опять рыдаю. Даже сейчас, в момент написания этих строк мне трудно дышать."
    old " Even though I had no interview today, I sat in front of my dressing table to put on makeup. But as soon as I saw my face, I was frightened, as it suddenly looked awful and disgusting. I fell backward, and managed to crawl to the bed. And I trembled and trembled. Then, I called Hye-na and begged her to save me.\n\n Soon, Hye-na came to my home, and I said to her I was probably going crazy, crying loudly in her arms. After I cried for a good while, I told her everything and taking her suggestion, I decided to see a doctor tomorrow. Hye-na is drinking a can of beer now.\n\n When I'm glancing at her, I feel my wrist, wrapped with bandages, is stinging.\n\n Okay, I'll finish today's diary here and go to bed after having some more conversations with Hye-na. Good night."
    new " Несмотря на то, что сегодня я не ходила на собеседование, я села напротив зеркала и накрасилась. Но стоило мне увидеть своё лицо, я сразу испугалась. Оно выглядело ужасно и отвратительно. Я попыталась обратно и забралась на кровать. Я вся дрожала. Тогда я позвонила Хаи-не и умоляла спасти меня.\n\n  вскоре приехала и я сказала ей, что, наверное, схожу с ума, громко рыдая в её объятиях. Вдоволь наплакавшись я рассказала ей всё и заручившись её поддержкой я решила навестить доктора завтра. А Хаи-на тем временем пьет пиво.\n\n Когда я смотрю на неё, то чувствую кровоточит перевязанное запястье.\n\n Пожалуй закончу сегодняшную запись на этом месте и пойду спать, предварительно ещё немного поговорив а сестрой. Спокойной ночи."
    old " Today, I visited a neuropsychiatric clinic, with Hye-na. I was pretty afraid to go there, but as I was with my sister, I could do it. The doctor asked me a number of things, from trivial questions to what is happening to me now and what I don't want to tell others as well.\n\n He also asked whether I have some physical problems, and I told him I hurt myself several times, and especially when I looked at my face yesterday, I was really frightened, as my eyes continuously blinked. The doctor asked me to have a medical checkup. So I filled out the questionnaire and had a blood test as well.\n\n And the result said I had 'anxiety disorder' and 'depressive disorder'. I asked the doctor if I was going to be a mental patient. But he said no.\n\n He just told me my condition and tick disorder would get better soon, if I try hard to improve my life pattern and steadily get counseling."
    new " Сегодня была в нейропсихиатрической клинике с Хаи-ной. Я очень боялась идти туда, но, поскольку я была не одна, то смогла это сделать. Врач задал мне несколько вопросов: от тривиальных вопросов до того, что со мной происходит, и того, что я даже не хочу рассказывать.\n\n Он также спросил есть ли у меня какие-либо проблемы с психикой. Я ответила, что несколько раз причиняла вред самой себе, а особенно вчера, когда посмотрела в зеркало. Мне было очень страшно. Врач сказал, что мне нужно пройти обследование. После этого я заполнила анкету и сдала кровь на анализ.\n\n Моим диагнозом стало \"тревожное и депрессивное расстройство\". На мой вопрос \"Сошла ли я с ума?\" доктор ответил отрицательно.\n\n Он просто сказал, что мое состояние и нервный тик со временем исчезнут, если я всерьез начну спасать свою жизнь."
    old " Today, I met Eunju. It's been a really long time since I've seen her. She used to be my best friend when we were high school students, but she is not single anymore. She said she's really worried as she hasn't lost any weight in spite of her steady diet since she gave birth to her baby. So I told her that she still looks good. Eunju worried about me saying I'm so bony, and she said to take her fat from her, shaking her potbelly. It was hilarious.\n\n Eunju has become a master of a Japanese fencing school. I think she probably heard about my situation from Hye-na, because she has never asked me about my job or marriage.\n\n She just kept talking about our school days, or her travel. Like other mamas, her voice was louder than it used to be, and also she speaks so fast Anyway, I'm happy she is having a good life.\n\n Ga-yeon, no more negative thinking! Okay?"
    new " Сегодня я встретила Юнцзю. Мы не виделись с ней ооочень давно. В старшей школе мы были лучшими подружками. Она очень переживала из-за того, что не могла сбросить лишний вес после родов. Поэтому я сказала ей, что она все еще выглядит хорошо. Юнцзю беспокоилась обо мне, сказав, что я очень костлявая, и положив руки на живот предложила забрать у неё немного лишнего веса. Это было весело.\n\n  Сейчас она работает в Японской школе фехтования. Я думаю она слышала о моей ситуации с Хаи-ной, потому что она не задавала вопросов про мою работу или личную жизнь.\n\n Вместо этого она вспоминала про наши школьные приключения или свои путешествия. Как и другие мамаши она говорила громче, чем раньше, и заметно быстрее. В любом случае я рада за неё.\n\n Га-Йан, больше никакого негативного мышления. Идёт?"
    old " These days, I receive mental health treatment, and also try hard to get a job. I didn't want to close my installment savings account, but I did, to have some reserved money for myself and also give some of it to my parents. I can't stop sending money to my parents because I have to make them believe I live well without any problem as always.\n\n However, getting a new job is harder than I expected. Because I worked mostly in restaurants, I have failed several times already, although I had a number of interviews for general office jobs.\n\n Besides, I never wrote my mental health-related matter in the resume, but some interviewers seemed to recognize my problem, as my tick disorder appeared even during the interview.\n\n I'm trying really to keep the steam up, but…. I'm getting tired of living…."
    new " Сейчас я получаю психиатрическую помощь, а также стараюсь устроиться на работу. Мне не хотелось закрывать свой сберегательный счет, но я сделала это, чтобы иметь хоть какие-то деньги для себя, а также отдать часть родителям. Я не могу перестать отправлять им деньги, потому что я должна заставить их поверить, что у меня всё по прежнему хорошо.\n\n Однако поиски проходят тяжелее, чем я рассчитывала. Из-за того, что я в основном работала в ресторанах, я уже несколько раз провалилась, хотя у меня есть достаточно вариантов пойти работать в офис.\n\n Кроме того, я никогда не писала в резюме о своём психическом здоровье, но некоторые рекрутеры, похоже, всё поняли, поскольку мой нервный тик проявлялся даже во время собеседования.\n\n Я очень стараюсь вести себя нормально, но ... мне начинает надоедать жить."
    old " I gave up. I gave up finding a new job, meeting people, receiving medical treatment, and everything. All are just useless. What I have now is…. only this tiny space. Where nothing happens unless I stir it.\n\n In spite of heaps of attempts to get a job, what I had was only frustration and discouragement. The hospital where I've received the treatment suggested I transfer to another hospital. Sometimes, the nebulizer which Hye-na presented me to soothe myself didn't work at all.\n\n I feel like my room is a rubbish can, and I'm just rubbish."
    new " Я сдаюсь. Я не могу больше искать эту чёртову работу, видеться с людьми, получать медицинскую помощь и ещё много чего. Это все бесполезно. Всё, что у меня сейчас есть ... только это крохотное место, где никогда ничего не происходит, если я сама это не начну.\n\n Несмотря на кучу попыток найти работу я находила только разочарование и отчаяние. Клиника, в которой я проходила лечение, предложила мне поменять место лечения. Да и подаренный сестрой ингалятор вообще не работает.\n\n Моя комната - мусорное ведро, а я - мусор внутри него."
    old " Go die, you bitch. How dare you want to live on! You're such a hooker who tried to take another's husband! Why are you still alive? You know well what a useless thing you are. You're just a whore. Now are you going to cling to him, instead of your previous lover? You don't deserve to live anymore. Go away. Go away and die.\n\n Someone keeps whispering in my ears. Okay. Alright. Just stop it, please. Please. I'm sorry. I go and die now. So, please shut up!"
    new " Умри, стерва. Как ты вообще ещё смеешь находиться среди живых? Ты просто шлюха, пытавшаяся заполучить женатого парня. Почему ты ещё дышишь? Ты ведь хорошо знаешь, насколько ты бесполезна. Ты просто шлюха. А теперь ты нашла себе нового любовника? Ты не заслуживаешь жить. Просто иди. Иди и умри.\n\n  Кто-то шепчет мне на ухо. Остановись. Хорошо. Хватит, пожалуйста. Сейчас пойду и умру, а поэтому, пожалуйста, заткнись!"
    old 'STORY'
    new 'Сюжет'
    old 'SIZE'
    new 'Размер'
    old 'TIME'
    new 'Лимит времени'
    old 'TRICK'
    new 'Ловушка'
    old 'Help….'
    new 'Помогите….'
    old 'Hmm….'
    new 'Хм….'
    old 'My bed.'
    new 'Моя кровать.'
    old 'There is no plastic bag.'
    new 'Пакета здесь нет.'
    old 'There is no jam on the bookshelf.{w=.3} And toilet…?'
    new 'На книжной полке джема нет.{w=.3} Может в туалете?'
    old 'My room is very small.'
    new 'Моя комнатушка такая маленькая.'
    old "It seems to be around…."
    new "Он должен быть где-то здесь…."
    old "It seems to be around.{w=.3} But it's not in the refrigerator."
    new "Где-то здесь,{w=.3} но не в холодильнике."
    old 'I stare at my reflection in the mirror.{w=.3} Are you happy now?'
    new 'И вот я смотрю на своё отражение в зеркале.{w=.3} Теперь ты рад?'
    old "It's near."
    new "Уже близко."
    old 'The water coming out of well.'
    new 'Из крана течёт вода.'
    old "It's me."
    new "Это я."
    old 'Please….'
    new 'Пожалуйста….'
    old 'Somebody…, help me….'
    new 'Кто-нибудь, помогите же мне….'
    old 'Not there!'
    new 'Не здесь!'
    old "It's a washing machine,{w=.3} and a gas stove."
    new "Это посудомойка, а это плита."
    old 'Open it!'
    new 'Открой это!'
    old "I don't have any kitchen tools."
    new "У меня нет никаких кухонных приборов."
    old 'Take out it!'
    new 'Вытаскивай!'
    old "It's a cat plastic bag."
    new "Это кошачий пакет."
    old "Mouse"
    new "Мышь"
    old "Keyboard"
    new "Клавиатура"
    old "Gamepad"
    new "Геймпад"
    old "Left Click"
    new "Левый клик"
    old "Advances dialogue and activates the interface."
    new "Прохождение диалогов и активация интерфейса."
    old "Right Click"
    new "Правый клик"
    old "Accesses the game menu."
    new "Вход в игровое меню."
    old "Mouse Wheel Up\nClick Rollback Side"
    new "Колёсико вверх\nКлик на сторону отката"
    old "Rolls back to earlier dialogue."
    new "Откат назад по сюжету игры."
    old "Mouse Wheel Down"
    new "Колёсико вниз"
    old "Rolls forward to later dialogue."
    new "Откатывает предыдущее действие вперёд."
    old "Middle Click"
    new "Клик колёсиком"
    old "Hides the user interface."
    new "Скрывает интерфейс пользователя."
    old "Space"
    new "Пробел"
    old "Advances dialogue without selecting choices."
    new "Прохождение диалогов, но не позволяет делать выбор."
    old "Arrow Keys"
    new "Стрелки"
    old "Navigate the interface."
    new "Навигация по интерфейсу."
    old "Skips dialogue while held down."
    new "Пропускает диалоги, пока зажат."
    old "Toggles dialogue skipping."
    new "Включает режим пропуска."
    old "Escape"
    new "Esc"
    old "Takes a screenshot."
    new "Делает снимок экрана."
    old "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    new "Включает поддерживаемый {a=https://www.renpy.org/l/voicing}синтезатор речи{/a}."
    old "D-Pad, Sticks"
    new "Крестовина, Стики"
    old "A/Bottom Button"
    new "A/Нижняя кнопка"
    old "Left Bumper"
    new "Левый Бампер"
    old "Right Bumper"
    new "Правый бампер"
    old "Calibrate"
    new "Калибровка"
