translate Korean strings:
    old "{#weekday}Monday"
    new "{#weekday}월요일"
    old "{#weekday}Tuesday"
    new "{#weekday}화요일"
    old "{#weekday}Wednesday"
    new "{#weekday}수요일"
    old "{#weekday}Thursday"
    new "{#weekday}목요일"
    old "{#weekday}Friday"
    new "{#weekday}금요일"
    old "{#weekday}Saturday"
    new "{#weekday}토요일"
    old "{#weekday}Sunday"
    new "{#weekday}일요일"
    old "{#weekday_short}Mon"
    new "{#weekday_short}월"
    old "{#weekday_short}Tue"
    new "{#weekday_short}화"
    old "{#weekday_short}Wed"
    new "{#weekday_short}수"
    old "{#weekday_short}Thu"
    new "{#weekday_short}목"
    old "{#weekday_short}Fri"
    new "{#weekday_short}금"
    old "{#weekday_short}Sat"
    new "{#weekday_short}토"
    old "{#weekday_short}Sun"
    new "{#weekday_short}일"
    old "{#month}January"
    new "{#month}정월"
    old "{#month}February"
    new "{#month}이월"
    old "{#month}March"
    new "{#month}삼월"
    old "{#month}April"
    new "{#month}사월"
    old "{#month}May"
    new "{#month}오월"
    old "{#month}June"
    new "{#month}유월"
    old "{#month}July"
    new "{#month}칠월"
    old "{#month}August"
    new "{#month}팔월"
    old "{#month}September"
    new "{#month}구월"
    old "{#month}October"
    new "{#month}시월"
    old "{#month}November"
    new "{#month}동짓달"
    old "{#month}December"
    new "{#month}섣달"
    old "{#month_short}Jan"
    new "{#month_short}1월"
    old "{#month_short}Feb"
    new "{#month_short}2월"
    old "{#month_short}Mar"
    new "{#month_short}3월"
    old "{#month_short}Apr"
    new "{#month_short}4월"
    old "{#month_short}May"
    new "{#month_short}5월"
    old "{#month_short}Jun"
    new "{#month_short}6월"
    old "{#month_short}Jul"
    new "{#month_short}7월"
    old "{#month_short}Aug"
    new "{#month_short}8월"
    old "{#month_short}Sep"
    new "{#month_short}9월"
    old "{#month_short}Oct"
    new "{#month_short}10월"
    old "{#month_short}Nov"
    new "{#month_short}11월"
    old "{#month_short}Dec"
    new "{#month_short}12월"
    old "%b %d, %H:%M"
    new "%b %d %H:%M"
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new "{#file_time}%Y년 %B %d일, %A, %H:%M"
    old "Quick save complete."
    new "빠른 저장 완료."
    old "Image [index] of [count] locked."
    new "[count]의 [index]번째 삽화는 잠겨있습니다."
    old "Graphics Acceleration"
    new "그래픽 가속"
    old "Automatically Choose"
    new "자동으로 선택한다"
    old "Force Angle/DirectX Renderer"
    new "앵글/다이렉트X 렌더러를 강제한다"
    old "Force OpenGL Renderer"
    new "오픈GL 렌더러를 강제한다"
    old "Force Software Renderer"
    new "소프트웨어 렌더러를 강제한다"
    old "Changes will take effect the next time this program is run."
    new "변경사항은 프로그램을 재시작하면 적용됩니다."
    old "Performance Warning"
    new "성능 경고"
    old "This computer is using software rendering."
    new "이 컴퓨터에서는 소프트웨어 렌더링을 사용하고 있습니다."
    old "This computer is not using shaders."
    new "이 컴퓨터에서는 쉐이더를 사용하지 않습니다."
    old "This computer is displaying graphics slowly."
    new "이 컴퓨터에서는 그래픽을 느리게 표시합니다."
    old "This computer has a problem displaying graphics: [problem]."
    new "이 컴퓨터에는 그래픽 표시에 문제가 있습니다. [problem]."
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display. Updating DirectX could fix this problem."
    new "컴퓨터의 그래픽 드라비어가 구버전이거나 제대로 작동하지 않습니다. 그래픽을 느리게 표시하거나 제대로 표시하지 못할 수 있습니다. 다이렉트X를 업데이트하면 이 문제를 해결할 수 있습니다."
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new "컴퓨터의 그래픽 드라비어가 구버전이거나 제대로 작동하지 않습니다. 그래픽을 느리게 표시하거나 제대로 표시하지 못할 수 있습니다."
    old "Update DirectX"
    new "다이렉트X 업데이트하기"
    old "Continue, Show this warning again"
    new "계속한다. 이 경고를 다시 표시한다."
    old "Continue, Don't show warning again"
    new "계속한다. 이 경고를 다시 표시하지 않는다."
    old "Updating DirectX."
    new "다이렉트X를 업데이트하고 있습니다."
    old "DirectX web setup has been started. It may start minimized in the taskbar. Please follow the prompts to install DirectX."
    new "다이렉트X 웹 설치를 시작했습니다. 작업표시줄에 최소화 상태로 시작되었을 수도 있습니다. 설치 안내창에 따라 다이렉트X를 설치하세요."
    old "{b}Note:{/b} Microsoft's DirectX web setup program will, by default, install the Bing toolbar. If you do not want this toolbar, uncheck the appropriate box."
    new "{b}* 주의{/b}/n 마이크로소프트의 다이렉트X 웹 설치 프로그램은 기본적으로 Bing 툴바를 설치합니다. 이 툴바를 설치하고 싶지 않다면 체크 박스의 체크 표시를 해제하세요."
    old "When setup finishes, please click below to restart this program."
    new "설치가 완료되면 아래 버튼을 눌러 프로그램을 다시 시작하세요."
    old "Restart"
    new "다시 시작"
    old "Saved screenshot as %s."
    new "갈무리를 %s 에 저장했습니다."
    old "Are you sure?"
    new "정말로요?"
    old "Are you sure you want to delete this save?"
    new "이 책갈피를 빼시겠습니까?"
    old "Are you sure you want to overwrite your save?"
    new "이 책갈피를 바꾸시겠습니까?"
    old "The next step is an important scene. Do you want to save here?"
    new "중요한 장면이 이어집니다. 여기서 책갈피를 하시겠습니까?"
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new "불러오기를 하면 책갈피 하지 않은 쪽을 잊어버리게 됩니다.\n정말로 불러올까요?"
    old "Are you sure you want to quit?"
    new "책을 덮으시겠습니까?"
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new "처음으로 돌아가겠습니까?\n책갈피 하지 않은 쪽은 잊어버리게 됩니다."
    old "Are you sure you want to skip to unseen dialogue or the next choice?"
    new "읽지 않은 극본 또는 다음 선택지로 이동하시겠습니까?"
    old "Are you sure you want to end the replay?"
    new "다시보기를 종료하시겠습니까?"
    old "Skip Mode"
    new "넘기기 활성"
    old "Fast Skip Mode"
    new "빠른 넘기기 활성"
    old "An exception has occurred."
    new "예외가 발생했습니다."
    old "Rollback"
    new "롤백"
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new "게임을 저장하거나 다른 선택지를 선택할 수 있도록 이전으로 롤백합니다."
    old "Ignore"
    new "무시"
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new "예외를 무시하고 게임을 계속합니다. 간혹 오류가 추가 발생할 수 있습니다."
    old "Reload"
    new "다시 불러오기"
    old "Reloads the game from disk, saving and restoring game state if possible."
    new "현재 상태를 저장한 뒤 복원하여 게임을 디스크에서 다시 불러옵니다."
    old "Open Traceback"
    new "Traceback.txt 파일 열기"
    old "Opens the traceback.txt file in a text editor."
    new "traceback.txt 파일을 스크립트 에디터로 엽니다."
    old "Quits the game."
    new "게임을 종료합니다."
    old "Parsing the script failed."
    new "스크립트 해석 실패."
    old "Open Parse Errors"
    new "Error.txt 파일 열기"
    old "Opens the errors.txt file in a text editor."
    new "errors.txt 파일을 스크립트 에디터로 엽니다."
    old "Self-voicing enabled. Press 'v' to disable."
    new "음성 지원 기능이 활성화됐습니다. 'v'를 누르면 비활성화됩니다."
    old "Self-voicing disabled."
    new "음성 지원 기능이 비활성화됐습니다."