translate Korean python:
    gui.main_font = "gui/fonts/YiSunShinBold.ttf"
    gui.text_font = "gui/fonts/NanumBarunGothic.ttf"
    gui.name_text_font = "gui/fonts/NanumBarunGothicBold.ttf"
    gui.interface_text_font = "gui/fonts/NanumBarunGothic.ttf"
    gui.button_text_font = "gui/fonts/NanumBarunGothic.ttf"
    config.name = "실망실업자"
    config.window_title = u"실망실업자"
    config.translations['Automatic saves'] = u'자동 저장'
    config.translations['Quick saves'] = u'빠른 저장'
    if renpy.variant("small"):
        config.translations["{font=[gui.fontawesome]}{/font} Basic Settings"] = u"{font=[gui.fontawesome]}{/font} 기본설정"
        config.translations["{font=[gui.fontawesome]}{/font} Seen Text"] = u"{font=[gui.fontawesome]}{/font} 이미 읽은 지문"
        config.translations["{font=[gui.fontawesome]}{/font} Mute All"] = u"{font=[gui.fontawesome]}{/font} 모두 끄기"
        config.translations["{font=[gui.fontawesome]}{/font} Authors"] = u"{font=[gui.fontawesome]}{/font} 저작권자"
		config.translations["Doctor"] = u"의사"
        config.translations['ACOC, Aiman Sharul, Axel Mertes, Bgame, Brandon Tanimoto, Brian Connors, BRISAK Kim Doohyeon, cheif.choi, Choi Irang, Choi Jihye, cloture, Danielle Bell, Edward N Puckering, Gary King, Gwak Jaeryeol, Han Ihyeong, Hoe Namyoon, Hong Eunki, Hwang Daehoon, Hyojoon, James Emmerson, Jeong Dongwon, Jeong Wookjin, Jeong Yoonsoo, Jianmin Zhang,\nKarina Schulze, Keira Val\'Azr, Kim Hanseol, Kim Hyeoncheol, Kim Jaeseong, Kim Jeongwoong, Kim Myeongwook,\nLee Changki, Lee Eunji, Lee Gunhae, Lee Hyejin, Lee Jaewi, Light Twins, Lim Jisoo, Maddy Wootton,\nMarshall Proudfoot, Mirumu, Mojaeng, Oh Hyeonjun, Park Hyeonjun, Park JoonKoo, Rewind, Sander Tieleman, srwss, Sung Chanaul, YottaCho, Zerial.net'] = u'B게임, BRISAK김두현, srwss, 곽재렬, 게리 킹, 김명욱,\n김정웅, 김재성, 김한솔, 김현철, 다니엘 벨, 라이트트윈스,\n리와인드, 마샬 프라우드풋, 모쟁, 매디 우튼, 미루무, 박준구,\n박현준, 브라이언 코너스, 브랜든 타니모토, 성찬얼,\n샌더 디엘레만, 아이만 샤룰, 악셀 메르테스,\n애드워드 앤 퍼커링, 오현준, 요타초, 이건해, 이재위, 이은지,\n이창기, 이혜진, 임지수, 정동원, 정욱진, 정윤수, 제리얼넷,\n제임스 애머슨, 지안민 장, 창조도시, 최실장, 최이랑,\n최지혜, 카리나 슐츠, 클로튀르, 키이라 발 아즈르, 한이형,\n허남윤, 홍은기, 효준, 황대훈'
        config.translations['Caz Woolley, Game Dev Robot, Gamsadev, Indie GameDev Bot, Indie Game Lover, Indie Games Devel, IndieVideoGames, Joachim Dimitri Jensen, Kim Kyeongtae, Kim Younghwan, Kurt Simon, Linda Lee King, Peter Christiansen, Sakimichi, Sebastian Haba, Spero Mcgee, The Indie Sloth, Vrachos, Xin Liu, Yu Shinhyeon'] = u'카즈 울리, 게임 데브 로봇, 게임을 만드는 사람들,\n인디 게임데브 로봇, 인디 게임 러버, 인디 게임즈 디벨,\n인디비디오게임즈, 김경태, 김영환, 린다 리 킹,\n브라초스, 사키미지, 세바스찬 하바, 스페로 맥기, 신 리우,\n요아킴 디미트리 옌센, 유신현, 인디 나무늘보, 커트 사이먼,\n피터 크리스티안센'
        config.translations['Christopher Rice, George Winston, Kim Sooyoung, Lee Illseong, Pixabay, Shin Haechul, So Reyeon, Tom Rothamel,\nValve Corporation'] = u"김수영, 밸브 코퍼레이션, 소리연, 신해철, 이일성,\n조지 윈스턴, 크리스토퍼 라이스, 탐 로타멜, 픽사베이"
    build_date = "2018년 3월 8일"
    copyright = "©2018 익드라실 스튜디오"
    gui.attention = "주     의"
    gui.language = "이 프로그램은 청소년이용불가로 19세 미만의 어린이(혹은 청소년)가(이) 시청하기에\n부적절하므로 보호자의 시청지도가 필요한 프로그램입니다.\n이 프로그램은 다음과 같은 내용을 포함하고 있습니다.\n\n직접적인 선정적 표현, 저속어, 비속어 및 욕설 표현"
    gui.start = "처음부터 읽기"
    gui.bookmarks = "책갈피"
    gui.load = "불러오기"
    gui.archives = "기록 보관소"
    gui.arcq = "기록 보관소"
    gui.dlc = "DLC&MOD"
    gui.conf = "환경설정"
    gui.blind_char  = "등장인물"
    gui.blind_con  = "해설 모음"
    gui.blind_diary  = "가연의 일기"
    gui.conq = "환경설정"
    gui.play = "계속 읽기"
    gui.stop = "잠깐 멈추기"
    gui.skip = "넘기기"
    gui.history = "극본"
    gui.hisq = "극본 열기"
    gui.hide = "숨기기"
    gui.save = "책갈피 꽂기"
    gui.quit = "책장 덮기"
    gui.credits = "만든이"
    gui.unlocked = "잠금해제"
    gui.heal = "치료하기"
    gui.judge = "방관하기"
    gui.left = "집으로 돌아가기"
    gui.right = "가보지 않은 길"
    gui.choice = "여기서 선택을 할 수 있습니다. 다음 설명을 듣고 원하는 것을 선택하십시오."
    gui.teddy = "테디를 찾으시오"
    gui.part01 = "혜나의 방문"
    gui.part02 = "가연의 독백"
    gui.part03 = "윤우와 만남"
    gui.part04 = "윤우와 신촌거리"
    gui.part05 = "윤우와 점심식사"
    gui.part06 = "가연의 독백"
    gui.part07 = "윤우와 담소"
    gui.part08 = "윤우가 들려준 혜나의 이야기"
    gui.part09 = "혜나의 사정"
    gui.part10 = "뒤틀림"
    gui.part11 = "가연의 독백"
    gui.part12 = "병원의 이야기"
    gui.part13 = "인생토론"
    gui.part14 = "가연의 현실파악"
    gui.part15 = "자해"
    gui.part16 = "안식에 잠들다"
    gui.part17 = "광기"
    gui.part18 = "윤우의 시점"
    gui.part19 = "가연의 시점"
    gui.part20 = "가연과 윤우"
    gui.part21 = "생명의 다리"
    gui.part22 = "세상의 끝자락"
    gui.part23 = "사건발생"
    gui.part24 = "에필로그"
    gui.part25 = "꽃이 핀 아침과 달 밝은 저녁"
    gui.the_end = "끝"
    gui.game_over = "게임오버"
    gui.bgm01 = "트랙 01. 팬더믹"
    gui.bgm02 = "트랙 02. 탄식의 나날"
    gui.bgm03 = "트랙 03. 고요의 바다"
    gui.bgm04 = "트랙 04. 트리플 캐논"
    gui.bgm05 = "트랙 05. 게임하자!"
    gui.bgm06 = "트랙 06. 평화"
    gui.bgm07 = "트랙 07. 알 수 없는 안개"
    gui.bgm08 = "트랙 08. 푸른 정원"
    gui.bgm09 = "트랙 09. 요르문간드"
    gui.bgm10 = "트랙 10. 밤의 여신"
    gui.bgm11 = "트랙 11. 정상결전"
    gui.bgm12 = "트랙 12. 연가"
    gui.bgm13 = "트랙 13. 넥타르의 평원"
    gui.about = "Discouraged Workers ©2018 YGGDRASIL STUDIO Co, Pte. 모든 권리 보유. 실망실업자의 저작권은 익드라실 스튜디오에 있습니다. 모든 저작물/상표는 해당하는 소유자의 재산입니다. 우리의 프로그램이나 우리의 프로그램 파일의 변경을 배포하지 마십시오. 최종 사용자 사용권 계약은 licenses 디렉토리의 EULA_ko.txt 문서 또는 {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/blob/gh-pages/EULA_ko.txt}여기{/a}를 확인하세요."
    code.license = "실망실업자의 소스 코드는 GNU 약소 일반 공중 사용권 v3.0 조항에 따라 이용할 수 있습니다. 소스 코드의 다운로드 위치는 {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/tree/source-codes}여기{/a}를 확인하세요."
    font.license = "이 작품은 SIL 열린 글꼴 사용권을 포함한 여러 사용권하에 무료 글꼴 소프트웨어가 포함돼 있습니다. 사용한 프로젝트 목록과 다운로드 위치는 licenses 디렉토리의 fonts-LICENSE.txt 문서 또는 {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}여기{/a}를 확인하세요."
    renpy.license = "렌파이 엔진은 MIT 사용권 및 GNU 약소 일반 공중 사용권을 포함한 여러 사용권하에 무료 소프트웨어가 포함돼 있습니다. 사용한 프로젝트 목록과 다운로드 위치는 {a=https://www.renpy.org/l/license/}여기{/a}를 확인하세요."
    valve.license = "©2018 Valve Corporation. Steam과 Steam 로고는 미국 및 기타 국가에서 등록된 Valve Corporation의 상표들입니다.\n\n©2018 Valve Corporation. Steamworks와 Steamworks 로고는 미국 및 기타 국가에서 등록된 Valve Corporation의 상표들입니다."
    xbox.license = "이 작품은 Xbox 360 컨트롤러/버튼 이미지를 사용합니다. 다운로드 위치는 {a=http://xbox.create.msdn.com/en-us/education/catalog/utility/controller_buttons}여기{/a}를 확인하세요."
    cc.license = "이 작품은 창작 공유 사용권이 적용되는 다양한 자산을 사용합니다. 사용한 자산 목록과 다운로드 위치는 licenses 디렉토리의 assets-LICENSE.txt 문서 또는 {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}여기{/a}를 확인하세요."
translate None python:
    config.name = "Discouraged Workers"
    config.window_title = u"Discouraged Workers"
    config.translations['Automatic saves'] = 'Automatic saves'
    config.translations['Quick saves'] = 'Quick saves'
    if renpy.variant("small"):
        config.translations["{font=[gui.fontawesome]}{/font} Basic Settings"] = u"{font=[gui.fontawesome]}{/font} Basic Settings"
        config.translations["{font=[gui.fontawesome]}{/font} Seen Text"] = u"{font=[gui.fontawesome]}{/font} Seen Text"
        config.translations["{font=[gui.fontawesome]}{/font} Mute All"] = u"{font=[gui.fontawesome]}{/font} Mute All"
        config.translations["{font=[gui.fontawesome]}{/font} Authors"] = u"{font=[gui.fontawesome]}{/font} Authors"
        config.translations['ACOC, Aiman Sharul, Axel Mertes, Bgame, Brandon Tanimoto, Brian Connors, BRISAK Kim Doohyeon, cheif.choi, Choi Irang, Choi Jihye, cloture, Danielle Bell, Edward N Puckering, Gary King, Gwak Jaeryeol, Han Ihyeong, Hoe Namyoon, Hong Eunki, Hwang Daehoon, Hyojoon, James Emmerson, Jeong Dongwon, Jeong Wookjin, Jeong Yoonsoo, Jianmin Zhang,\nKarina Schulze, Keira Val\'Azr, Kim Hanseol, Kim Hyeoncheol, Kim Jaeseong, Kim Jeongwoong, Kim Myeongwook,\nLee Changki, Lee Eunji, Lee Gunhae, Lee Hyejin, Lee Jaewi, Light Twins, Lim Jisoo, Maddy Wootton,\nMarshall Proudfoot, Mirumu, Mojaeng, Oh Hyeonjun, Park Hyeonjun, Park JoonKoo, Rewind, Sander Tieleman, srwss, Sung Chanaul, YottaCho, Zerial.net'] = u'ACOC, Aiman Sharul, Axel Mertes, Bgame,\nBrandon Tanimoto, Brian Connors,\nBRISAK Kim Doohyeon, cheif.choi, Choi Irang,\nChoi Jihye, cloture, Danielle Bell,\nEdward N Puckering, Gary King, Gwak Jaeryeol,\nHan Ihyeong, Hoe Namyoon, Hong Eunki,\nHwang Daehoon, Hyojoon, James Emmerson,\nJeong Dongwon, Jeong Wookjin, Jeong Yoonsoo,\nJianmin Zhang, Karina Schulze, Keira Val\'Azr,\nKim Hanseol, Kim Hyeoncheol, Kim Jaeseong,\nKim Jeongwoong, Kim Myeongwook, Lee Changki,\nLee Eunji, Lee Gunhae, Lee Hyejin, Lee Jaewi,\nLight Twins, Lim Jisoo, Maddy Wootton,\nMarshall Proudfoot, Mirumu, Mojaeng,\nOh Hyeonjun, Park Hyeonjun, Park JoonKoo, Rewind, Sander Tieleman, srwss, Sung Chanaul, YottaCho, Zerial.net'
        config.translations['Caz Woolley, Game Dev Robot, Gamsadev, Indie GameDev Bot, Indie Game Lover, Indie Games Devel, IndieVideoGames, Joachim Dimitri Jensen, Kim Kyeongtae, Kim Younghwan, Kurt Simon, Linda Lee King, Peter Christiansen, Sakimichi, Sebastian Haba, Spero Mcgee, The Indie Sloth, Vrachos, Xin Liu, Yu Shinhyeon'] = u'Caz Woolley, Game Dev Robot, Gamsadev,\nIndie GameDev Bot, Indie Game Lover,\nIndie Games Devel, IndieVideoGames,\nJoachim Dimitri Jensen, Kim Kyeongtae,\nKim Younghwan, Kurt Simon, Linda Lee King,\nPeter Christiansen, Sakimichi, Sebastian Haba,\nSpero Mcgee, The Indie Sloth, Vrachos, Xin Liu,\nYu Shinhyeon'
        config.translations['Christopher Rice, George Winston, Kim Sooyoung, Lee Illseong, Pixabay, Shin Haechul, So Reyeon, Tom Rothamel,\nValve Corporation'] = u'Christopher Rice, George Winston, Kim Sooyoung, Lee Illseong, Pixabay, Shin Haechul, So Reyeon, Tom Rothamel, Valve Corporation'
    build_date = "Mar 08, 2018"
    copyright = "©2018 YGGDRASIL STUDIO"
    gui.part01 = "Are you alright?"
    gui.part02 = "Monologue"
    gui.part03 = "Do you remember first love?"
    gui.part04 = "Shin-Chon Street"
    gui.part05 = "Sad lunch"
    gui.part06 = "Monologue"
    gui.part07 = "Calm afternoon"
    gui.part08 = "Questionable feelings"
    gui.part09 = "Circumstances"
    gui.part10 = "Distortion"
    gui.part11 = "Monologue"
    gui.part12 = "Broken heart"
    gui.part13 = "How alive are you?"
    gui.part14 = "Grasping reality"
    gui.part15 = "Self-inflicted"
    gui.part16 = "R.I.P"
    gui.part17 = "Madness"
    gui.part18 = "Yunwoo\'s view"
    gui.part19 = "Ga-yeon\'s view"
    gui.part20 = "Ga-yeon and Yunwoo"
    gui.part21 = "Bridge of the life"
    gui.part22 = "Edge of the world"
    gui.part23 = "Accident"
    gui.part24 = "Epilogue"
    gui.part25 = "Flowery mornings and moonlit nights"
    gui.the_end = "The End"
    gui.game_over = "Game Over"
    gui.bgm01 = "Track 1. Pandemic"
    gui.bgm02 = "Track 2. Sigh day"
    gui.bgm03 = "Track 3. Mare tranquillitatis"
    gui.bgm04 = "Track 4. CCCanon"
    gui.bgm05 = "Track 5. Let's game"
    gui.bgm06 = "Track 6. Peace"
    gui.bgm07 = "Track 7. Unknown mist"
    gui.bgm08 = "Track 8. Lush garden"
    gui.bgm09 = "Track 9. Jormungandr"
    gui.bgm10 = "Track 10. Nyx"
    gui.bgm11 = "Track 11. Summit showdown"
    gui.bgm12 = "Track 12. Love song"
    gui.bgm13 = "Track 13. Sea of nectar"
    gui.about = "Discouraged Workers ©2018 YGGDRASIL STUDIO Co, Pte. All Rights Reserved. All literary works/trademarks are property of their respective owners. Do not distribute our program or any alterations of our program files. For the End User License Agreement, please view the EULA.txt file in the licenses directory, or visit {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/blob/gh-pages/EULA.txt}here{/a}."
    code.license = "The source code of Discouraged Workers is covered by the terms of the GNU Lesser General Public License v3.0. The source code can be found {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/tree/source-codes}here{/a}."
    font.license = "This program contains free font software under a number of licenses, including the SIL Open Font License. A complete list of font software, including links to download can be found {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}here{/a}, or please view the fonts-LICENSE.txt file in the licenses directory."
    renpy.license = "This program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license/}here{/a}."
    valve.license = "©2018 Valve Corporation. Steam and the Steam logo are trademarks and/or registered trademarks of Valve Corporation in the U.S. and/or other countries.\n\n©2018 Valve Corporation. Steamworks and the Steamworks logo are trademarks and/or registered trademarks of Valve Corporation in the U.S. and/or other countries."
    xbox.license = "This program contains Xbox 360 Controller/Button images. The asset pack can be found {a=http://xbox.create.msdn.com/en-us/education/catalog/utility/controller_buttons}here{/a}."
    cc.license = "This program contains a number of assets that are covered by the terms of the Creative Commons License. For a list of assets, and a location where the original assets can be downloaded from, please view the assets-LICENSE.txt file in the licenses directory or visit {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}here{/a}."
