translate Korean strings:
    old "Load"
    new "불러오기"
    old "Left arrow key: Yes, Right arrow key: No."
    new "왼쪽 방향쇠: 네, 오른쪽 방향쇠: 아니오."
    old "Left arrow key: Previous, Right arrow key: Next."
    new "왼쪽 방향쇠: 이전, 오른쪽 방향쇠: 다음."
    old "Left arrow key: Healing, Right arrow key: Onlooking"
    new "왼쪽 방향쇠: 치료하기, 오른쪽 방향쇠: 방관하기"
    old "Left arrow key: Back home, Right arrow key: Road not taken"
    new "왼쪽 방향쇠: 집으로 돌아가기, 오른쪽 방향쇠: 가보지 않은 길"
    old "You can make a choice here. Listen to the following explanation and choose what you want."
    new "여기서 선택을 할 수 있습니다. 다음 설명을 듣고 원하는 것을 선택하십시오."
    old "©2020 YGGDRASIL STUDIO"
    new "©2020 익드라실 스튜디오"
    old "June 06, 2020 - V[config.version]"
    new "2020년 06월 06일 - V[config.version]"
    old "{size=86}Start Reading{/size}"
    new "처음부터 읽기"
    old "{size=86}Bookmarks{/size}"
    new "책갈피"
    old "{size=86}Load{/size}"
    new "불러오기"
    old "{size=86}Archives{/size}"
    new "기록 보관소"
    old "{size=86}DLC&MOD{/size}"
    new "DLC&MOD"
    old "{size=86}Configuration{/size}"
    new "환경설정"
    old "{size=86}Characters{/size}"
    new "등장인물"
    old "{size=86}Concept{/size}"
    new "해설 모음"
    old "{size=86}Diary{/size}"
    new "가연의 일기"
    old "{size=86}Quit{/size}"
    new "책장 덮기"
    old '{size=[gui.quick_button_text_size]}Config{/size}'
    new '{size=[gui.quick_button_text_size]}환경설정{/size}'
    old '{size=[gui.quick_button_text_size]}Play{/size}'
    new '{size=[gui.quick_button_text_size]}계속 읽기{/size}'
    old "{font=[gui.fontawesome]}{/font} Play"
    new "{font=[gui.fontawesome]}{/font} 계속 읽기"
    old '{size=[gui.quick_button_text_size]}Stop{/size}'
    new '{size=[gui.quick_button_text_size]}일시정지{/size}'
    old '{size=[gui.quick_button_text_size]}Skip{/size}'
    new '{size=[gui.quick_button_text_size]}넘기기{/size}'
    old "{font=[gui.fontawesome]}{/font} Archives"
    new "{font=[gui.fontawesome]}{/font} 기록 보관소"
    old '{size=[gui.quick_button_text_size]}Archives{/size}'
    new '{size=[gui.quick_button_text_size]}기록 보관소{/size}'
    old "{font=[gui.fontawesome]}{/font} History"
    new "{font=[gui.fontawesome]}{/font} 극본"
    old '{size=[gui.quick_button_text_size]}History{/size}'
    new '{size=[gui.quick_button_text_size]}극본 열기{/size}'
    old '{size=[gui.quick_button_text_size]}Hide{/size}'
    new '{size=[gui.quick_button_text_size]}숨기기{/size}'
    old '{size=[gui.quick_button_text_size]}Save{/size}'
    new '{size=[gui.quick_button_text_size]}책갈피 꽂기{/size}'
    old "{font=[gui.fontawesome]}{/font} Credits"
    new "{font=[gui.fontawesome]}{/font} 만든이"
    old "{font=[gui.fontawesome]}{/font} Unlocked"
    new "{font=[gui.fontawesome]}{/font} 잠금해제"
    old '{size=[gui.interface_text_size]}Healing{/size}'
    new '{size=[gui.interface_text_size]}치료하기{/size}'
    old '{size=[gui.interface_text_size]}Onlooking{/size}'
    new '{size=[gui.interface_text_size]}방관하기{/size}'
    old '{size=[gui.interface_text_size]}Back home{/size}'
    new '{size=[gui.interface_text_size]}집으로 돌아가기{/size}'
    old '{size=[gui.interface_text_size]}Road not taken{/size}'
    new '{size=[gui.interface_text_size]}가보지 않은 길{/size}'
    old "{image=gui/controllers/[persistent.controllers]/grip_r.webp} {size=86}Start Reading{/size}"
    new "{image=gui/controllers/[persistent.controllers]/grip_r.webp} 처음부터 읽기"
    old "{image=gui/controllers/[persistent.controllers]/guide.webp} {size=86}Start Reading{/size}"
    new "{image=gui/controllers/[persistent.controllers]/guide.webp} 처음부터 읽기"
    old "{image=gui/controllers/[persistent.controllers]/shoulder_r.webp} {size=86}Load{/size}"
    new "{image=gui/controllers/[persistent.controllers]/shoulder_r.webp} 불러오기"
    old "{image=gui/controllers/[persistent.controllers]/button_start.webp} {size=86}Load{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_start.webp} 불러오기"
    old "{image=gui/controllers/[persistent.controllers]/shoulder_r.webp} {size=86}Bookmarks{/size}"
    new "{image=gui/controllers/[persistent.controllers]/shoulder_r.webp} 책갈피"
    old "{image=gui/controllers/[persistent.controllers]/button_start.webp} {size=86}Bookmarks{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_start.webp} 책갈피"
    old "{image=gui/controllers/[persistent.controllers]/button_b.webp} {size=86}Archives{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_b.webp} 기록 보관소"
    old "{image=gui/controllers/[persistent.controllers]/button_b.webp} {size=86}Characters{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_b.webp} 등장인물"
    old "{image=gui/controllers/[persistent.controllers]/button_x.webp} {size=86}Concept{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_x.webp} 해설 모음"
    old "{image=gui/controllers/[persistent.controllers]/button_y.webp} {size=86}Diary{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_y.webp} 가연의 일기"
    old "{image=gui/controllers/[persistent.controllers]/button_x.webp} {size=86}DLC&MOD{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_x.webp} DLC&MOD"
    old "{image=gui/controllers/[persistent.controllers]/button_y.webp} {size=86}Configuration{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_y.webp} 환경설정"
    old "{image=gui/controllers/[persistent.controllers]/shoulder_l.webp} {size=86}Quit{/size}"
    new "{image=gui/controllers/[persistent.controllers]/shoulder_l.webp} 책장 덮기"
    old "{image=gui/controllers/[persistent.controllers]/button_select.webp} {size=86}Quit{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_select.webp} 책장 덮기"
    old "Track 1. Pandemic"
    new "트랙 01. 팬더믹"
    old "Track 2. Sigh day"
    new "트랙 02. 탄식의 나날"
    old "Track 3. Mare tranquillitatis"
    new "트랙 03. 고요의 바다"
    old "Track 4. CCCanon"
    new "트랙 04. 트리플 캐논"
    old "Track 5. Let's game"
    new "트랙 05. 게임하자!"
    old "Track 6. Peace"
    new "트랙 06. 평화"
    old "Track 7. Unknown mist"
    new "트랙 07. 알 수 없는 안개"
    old "Track 8. Lush garden"
    new "트랙 08. 푸른 정원"
    old "Track 9. Jormungandr"
    new "트랙 09. 요르문간드"
    old "Track 10. Nyx"
    new "트랙 10. 밤의 여신"
    old "Track 11. Summit showdown"
    new "트랙 11. 정상결전"
    old "Track 12. Love song"
    new "트랙 12. 연가"
    old "Track 13. Sea of nectar"
    new "트랙 13. 넥타르의 평원"
    old "Track 3. Mare tranquillitatis\nTrack 7. Unknown mist"
    new "트랙 03. 고요의 바다\n트랙 07. 알 수 없는 안개"
    old "Track 8. Lush garden\nTrack 9. Jormungandr"
    new "트랙 08. 푸른 정원\n트랙 09. 요르문간드"
    old "Credits"
    new "만든이"
    old "Discouraged Workers ©2020 YGGDRASIL STUDIO Co, Pte. All Rights Reserved. All literary works/trademarks are property of their respective owners. Do not distribute our program or any alterations of our program files. For the End User License Agreement, please view the EULA.txt file in the licenses directory, or visit {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/blob/gh-pages/EULA.txt}here{/a}.\n\nThe source code of Discouraged Workers is covered by the terms of the GNU Lesser General Public License v3.0. The source code can be found {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/tree/source-codes}here{/a}.\n"
    new "Discouraged Workers ©2020 YGGDRASIL STUDIO Co, Pte. 모든 권리 보유. 실망실업자의 저작권은 익드라실 스튜디오에 있습니다. 모든 저작물/상표는 해당하는 소유자의 재산입니다. 우리의 프로그램이나 우리의 프로그램 파일의 변경을 배포하지 마십시오. 최종 사용자 사용권 계약은 licenses 디렉토리의 EULA_ko.txt 문서 또는 {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/blob/gh-pages/EULA_ko.txt}여기{/a}를 확인하세요.\n\n실망실업자의 소스 코드는 GNU 약소 일반 공중 사용권 v3.0 조항에 따라 이용할 수 있습니다. 소스 코드의 다운로드 위치는 {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/tree/source-codes}여기{/a}를 확인하세요.\n"
    old "This program contains free font software under a number of licenses, including the SIL Open Font License. A complete list of font software, including links to download can be found {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}here{/a}, or please view the fonts-LICENSE.txt file in the licenses directory.\n\nThis program contains a number of assets that are covered by the terms of the Creative Commons License. For a list of assets, and a location where the original assets can be downloaded from, please view the assets-LICENSE.txt file in the licenses directory or visit {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}here{/a}.\n"
    new "이 작품은 SIL 열린 글꼴 사용권을 포함한 여러 사용권하에 무료 글꼴 소프트웨어가 포함돼 있습니다. 사용한 프로젝트 목록과 다운로드 위치는 licenses 디렉토리의 fonts-LICENSE.txt 문서 또는 {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}여기{/a}를 확인하세요.\n\n이 작품은 창작 공유 사용권이 적용되는 다양한 자산을 사용합니다. 사용한 자산 목록과 다운로드 위치는 licenses 디렉토리의 assets-LICENSE.txt 문서 또는 {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}여기{/a}를 확인하세요.\n"
    old "This program contains Xbox 360 Controller/Button images. The asset pack can be found {a=http://xbox.create.msdn.com/en-us/education/catalog/utility/controller_buttons}here{/a}.\n"
    new "이 작품은 Xbox 360 컨트롤러/버튼 이미지를 사용합니다. 다운로드 위치는 {a=http://xbox.create.msdn.com/en-us/education/catalog/utility/controller_buttons}여기{/a}를 확인하세요.\n"
    old "©2020 Valve Corporation. Steam and the Steam logo are trademarks and/or registered trademarks of Valve Corporation in the U.S. and/or other countries.\n\n©2020 Valve Corporation. Steamworks and the Steamworks logo are trademarks and/or registered trademarks of Valve Corporation in the U.S. and/or other countries."
    new "©2020 Valve Corporation. Steam과 Steam 로고는 미국 및 기타 국가에서 등록된 Valve Corporation의 상표들입니다.\n\n©2020 Valve Corporation. Steamworks와 Steamworks 로고는 미국 및 기타 국가에서 등록된 Valve Corporation의 상표들입니다."
    old "{font=[gui.fontawesome]}{/font} Basic Settings"
    new "{font=[gui.fontawesome]}{/font} 기본설정"
    old "{font=[gui.fontawesome]}{/font} About"
    new "{font=[gui.fontawesome]}{/font} 작품정보"
    old "{font=[gui.fontawesome]}{/font} Help"
    new "{font=[gui.fontawesome]}{/font} 조작방법"
    old "{font=[gui.fontawesome]}{/font} Characters"
    new "{font=[gui.fontawesome]}{/font} 등장인물"
    old "{font=[gui.fontawesome]}{/font} Concept"
    new "{font=[gui.fontawesome]}{/font} 해설 모음"
    old "{font=[gui.fontawesome]}{/font} Diary"
    new "{font=[gui.fontawesome]}{/font} 가연의 일기"
    old "{font=[gui.fontawesome]}{/font} Gallery"
    new "{font=[gui.fontawesome]}{/font} 미술 전시관"
    old "{font=[gui.fontawesome]}{/font} Music"
    new "{font=[gui.fontawesome]}{/font} 음악 감상관"
    old "{font=[gui.fontawesome]}{/font} Replay"
    new "{font=[gui.fontawesome]}{/font} 다시 보기"
    old "{font=[gui.fontawesome]}{/font} Medals"
    new "{font=[gui.fontawesome]}{/font} 획득한 메달"
    old "{font=[gui.fontawesome]}{/font} Refresh"
    new "{font=[gui.fontawesome]}{/font} 새로고침"
    old "{font=[gui.fontawesome]}{/font} Window"
    new "{font=[gui.fontawesome]}{/font} 창 화면"
    old "{font=[gui.fontawesome]}{/font} Fullscreen"
    new "{font=[gui.fontawesome]}{/font} 전체 화면"
    old "{font=[gui.fontawesome]}{/font} Save"
    new "{font=[gui.fontawesome]}{/font} 저장하기"
    old "{font=[gui.fontawesome]}{/font} Start Reading"
    new "{font=[gui.fontawesome]}{/font} 처음부터 읽기"
    old "{font=[gui.fontawesome]}{/font} Load"
    new "{font=[gui.fontawesome]}{/font} 불러오기"
    old "{font=[gui.fontawesome]}{/font} Configuration"
    new "{font=[gui.fontawesome]}{/font} 환경설정"
    old "{font=[gui.fontawesome]}{/font} DLC&MOD"
    new "{font=[gui.fontawesome]}{/font} DLC&MOD"
    old "{font=[gui.fontawesome]}{/font} End Replay"
    new "{font=[gui.fontawesome]}{/font} 다시 보기 종료"
    old "{font=[gui.fontawesome]}{/font} Main Menu"
    new "{font=[gui.fontawesome]}{/font} 대문으로"
    old "{font=[gui.fontawesome]}{/font} Quit"
    new "{font=[gui.fontawesome]}{/font} 책장 덮기"
    old "{font=[gui.fontawesome]}{/font} Done"
    new "{font=[gui.fontawesome]}{/font} 완료"
    old "{font=[gui.fontawesome]}{/font} Return"
    new "{font=[gui.fontawesome]}{/font} 돌아가기"
    old "{font=[gui.fontawesome]}{/font} Yes"
    new "{font=[gui.fontawesome]}{/font} 네"
    old "{font=[gui.fontawesome]}{/font} No"
    new "{font=[gui.fontawesome]}{/font} 아니오"
    old "Version [config.version!t]\n"
    new "버전 [config.version!t]\n"
    old "Created with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\nThis program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license/}here{/a}.\n"
    new "이 작품은 시각 소설 엔진 {a=https://www.renpy.org/}렌파이{/a} [renpy.version_only]로 창작됐습니다.\n\n렌파이 엔진은 MIT 사용권 및 GNU 약소 일반 공중 사용권을 포함한 여러 사용권하에 무료 소프트웨어가 포함돼 있습니다. 사용한 프로젝트 목록과 다운로드 위치는 {a=https://www.renpy.org/l/license/}여기{/a}를 확인하세요.\n"
    old "empty slot"
    new "책갈피 가능"
    old "{#auto_page}A"
    new "{#auto_page}자동"
    old "{#quick_page}Q"
    new "{#quick_page}빠른"
    old "Page {}"
    new "{}쪽"
    old "Automatic saves"
    new "자동 저장"
    old "Quick saves"
    new "빠른 저장"
    old "{font=[gui.fontawesome]}{/font} Display"
    new "{font=[gui.fontawesome]}{/font} 화면 제어"
    old "{font=[gui.fontawesome]}{/font} Rollback Side"
    new "{font=[gui.fontawesome]}{/font} 롤백 방향"
    old "{font=[gui.fontawesome]}{/font} Enable"
    new "{font=[gui.fontawesome]}{/font} 활성화"
    old "{font=[gui.fontawesome]}{/font} Disable"
    new "{font=[gui.fontawesome]}{/font} 비활성화"
    old "{font=[gui.fontawesome]}{/font} Left"
    new "{font=[gui.fontawesome]}{/font} 왼쪽"
    old "{font=[gui.fontawesome]}{/font} Right"
    new "{font=[gui.fontawesome]}{/font} 오른쪽"
    old "{font=[gui.fontawesome]}{/font} Skip"
    new "{font=[gui.fontawesome]}{/font} 넘기기"
    old "{font=[gui.fontawesome]}{/font} Seen Text"
    new "{font=[gui.fontawesome]}{/font} 이미 읽은 지문"
    old "{font=[gui.fontawesome]}{/font} After Choices"
    new "{font=[gui.fontawesome]}{/font} 선택 이후"
    old "{font=[gui.fontawesome]}{/font} Transitions"
    new "{font=[gui.fontawesome]}{/font} 화면 전환 효과"
    old "{font=[gui.fontawesome]}{/font} Text Speed"
    new "{font=[gui.fontawesome]}{/font} 지문 출력 속도"
    old "{font=[gui.fontawesome]}{/font} Auto-Forward Time"
    new "{font=[gui.fontawesome]}{/font} 자동 재생 속도"
    old "{font=[gui.fontawesome]}{/font} Music Volume"
    new "{font=[gui.fontawesome]}{/font} 음악 음량"
    old "{font=[gui.fontawesome]}{/font} Sound Volume"
    new "{font=[gui.fontawesome]}{/font} 음향 음량"
    old "{font=[gui.fontawesome]}{/font} Test"
    new "{font=[gui.fontawesome]}{/font} 음향 확인"
    old "{font=[gui.fontawesome]}{/font} Voice Volume"
    new "{font=[gui.fontawesome]}{/font} 목소리 음량"
    old "{font=[gui.fontawesome]}{/font} Mute All"
    new "{font=[gui.fontawesome]}{/font} 모두 끄기"
    old "The dialogue history is empty."
    new "비어 있습니다."
    old "{font=[gui.fontawesome]}{/font} Total"
    new "{font=[gui.fontawesome]}{/font} 전체"
    old "{font=[gui.fontawesome]}{/font} Characters +2"
    new "{font=[gui.fontawesome]}{/font} 등장인물 +2"
    old "{font=[gui.fontawesome]}{/font} Music +1"
    new "{font=[gui.fontawesome]}{/font} 음악 감상관 +1"
    old "{font=[gui.fontawesome]}{/font} Replay +1"
    new "{font=[gui.fontawesome]}{/font} 다시 보기 +1"
    old "{font=[gui.fontawesome]}{/font} Replay +3"
    new "{font=[gui.fontawesome]}{/font} 다시 보기 +3"
    old "{font=[gui.fontawesome]}{/font} Characters +1"
    new "{font=[gui.fontawesome]}{/font} 등장인물 +1"
    old "{font=[gui.fontawesome]}{/font} Concept +1"
    new "{font=[gui.fontawesome]}{/font} 해설 모음 +1"
    old "{font=[gui.fontawesome]}{/font} Gallery +3"
    new "{font=[gui.fontawesome]}{/font} 미술 전시관 +3"
    old "{font=[gui.fontawesome]}{/font} Gallery +2"
    new "{font=[gui.fontawesome]}{/font} 미술 전시관 +2"
    old "{font=[gui.fontawesome]}{/font} Music +2"
    new "{font=[gui.fontawesome]}{/font} 음악 감상관 +2"
    old "{font=[gui.fontawesome]}{/font} Gallery +1"
    new "{font=[gui.fontawesome]}{/font} 미술 전시관 +1"
    old "{font=[gui.fontawesome]}{/font} Gallery +5"
    new "{font=[gui.fontawesome]}{/font} 미술 전시관 +5"
    old "{font=[gui.fontawesome]}{/font} Concept +2"
    new "{font=[gui.fontawesome]}{/font} 해설 모음 +2"
    old "{font=[gui.fontawesome]}{/font} Diary +15"
    new "{font=[gui.fontawesome]}{/font} 가연의 일기 +15"
    old "{font=[gui.fontawesome]}{/font} Diary +1"
    new "{font=[gui.fontawesome]}{/font} 가연의 일기 +1"
    old "Back to the bridge!"
    new "생명의 다리로 돌아가십시오!"
    old "Extras"
    new "엑스트라즈"
    old "{font=[gui.fontawesome]}{/font} Open"
    new "{font=[gui.fontawesome]}{/font} 열기"
    old "{font=[gui.fontawesome]}{/font} Gift"
    new "{font=[gui.fontawesome]}{/font} 선물하기"
    old "{font=[gui.fontawesome]}{/font} Delete"
    new "{font=[gui.fontawesome]}{/font} 지우기"
    old "{font=[gui.fontawesome]}{/font} Install"
    new "{font=[gui.fontawesome]}{/font} 설치하기"
    old "{font=[gui.fontawesome]}{/font} Add to cart"
    new "{font=[gui.fontawesome]}{/font} 장바구니 담기"
    old "{font=[gui.fontawesome]}{/font} Start"
    new "{font=[gui.fontawesome]}{/font} 시작"
    old "Original Sound Track"
    new "오리지널 사운드 트랙"
    old "{font=[gui.fontawesome]}{/font} Manual"
    new "{font=[gui.fontawesome]}{/font} 설명서"
    old "Digital Art Book"
    new "디지털 아트 북"
    old "{font=[gui.fontawesome]}{/font} View"
    new "{font=[gui.fontawesome]}{/font} 보기"
    old "Digital Concept Book"
    new "디지털 콘셉트 북"
    old "MOD Creator Development Kit"
    new "모드 창작자 개발 키트"
    old "Back to the Basic"
    new "백 투 더 베이직"
    old "Tarot PNP Pack"
    new "타로 PNP 팩"
    old "Please wait for more update."
    new "판올림을 기다려주세요."
    old "Skipping"
    new "넘기기 중"
    old "{font=[gui.fontawesome]}{/font} Language"
    new "{font=[gui.fontawesome]}{/font} 사용자 언어"
    old "{font=[gui.fontawesome]}{/font} Vibrate"
    new "{font=[gui.fontawesome]}{/font} 진동 제어"
    old "{font=[gui.fontawesome]}{/font} Controller"
    new "{font=[gui.fontawesome]}{/font} 제어기"
    old "{font=[gui.fontawesome]}{/font} Disable"
    new "{font=[gui.fontawesome]}{/font} 비활성화"
    old "Do not display any Controller images."
    new "제어기 단추 그림을 표시하지 않습니다."
    old "{font=[gui.fontawesome]}{/font} Steam Controller"
    new "{font=[gui.fontawesome]}{/font} 스팀 컨트롤러"
    old "Display the Steam Controller images."
    new "스팀 컨트롤러의 단추 그림을 표시합니다."
    old "{font=[gui.fontawesome]}{/font} General Gamepad"
    new "{font=[gui.fontawesome]}{/font} 일반 게임패드"
    old "{font=[gui.fontawesome]}{/font} {s}OUYA Controller{/s}"
    new "{font=[gui.fontawesome]}{/font} {s}우야 컨트롤러{/s}"
    old "Display the Xbox Controller images."
    new "엑스박스 컨트롤러의 단추 그림을 표시합니다."
    old "Display the OUYA Controller images."
    new "우야 컨트롤러의 단추 그림을 표시합니다."
    old "{font=[gui.fontawesome]}{/font} Tic disorder"
    new "{font=[gui.fontawesome]}{/font} 틱 장애"
    old "This will activate Ga-yeon's tic disorder."
    new "가연의 틱 장애를 활성화합니다."
    old "This will deactivate Ga-yeon's tic disorder."
    new "가연의 틱 장애를 비활성화합니다."
    old "{font=[gui.fontawesome]}{/font} Epilepsy-friendly"
    new "{font=[gui.fontawesome]}{/font} 뇌전증 배려"
    old "This will disable some screen effects for people who have epilepsy or similar photosensitive disorders."
    new "뇌전증 또는 유사한 감광성 질환을 앓고 있는 분들을 위해 일부 화면 효과를 비활성화합니다."
    old "{font=[gui.fontawesome]}{/font} Blind-friendly"
    new "{font=[gui.fontawesome]}{/font} 시각장애 배려"
    old "This will activate the blind-friendly features with the self-voicing feature."
    new "시각장애 배려 기능과 음성 지원 기능을 활성화합니다."
    old "This will disable the blind-friendly features."
    new "시각장애 배려 기능과 음성 지원 기능을 비활성화합니다."
    old "Reset"
    new "초기화"
    old '{font=[gui.fontawesome]}{/font} Old Version'
    new '{font=[gui.fontawesome]}{/font} 구버전'
    old "{font=[gui.fontawesome]}{/font} Authors"
    new "{font=[gui.fontawesome]}{/font} 저작권자"
    old "{font=[gui.fontawesome]}{/font} Photographers"
    new "{font=[gui.fontawesome]}{/font} 사진작가"
    old "{font=[gui.fontawesome]}{/font} Contributors"
    new "{font=[gui.fontawesome]}{/font} 후원자"
    old "{font=[gui.fontawesome]}{/font} Rooters"
    new "{font=[gui.fontawesome]}{/font} 응원자"
    old "Lee Yunseok"
    new "이윤석"
    old "Directing, Design, Programming, Music, Sound, Writing, UI Design, Background CG, Object Sprites, Packaging, Video, Website -From April 21, 2013"
    new "디렉팅, 디자인, 프로그래밍, 음악, 음향, 극본, UI 디자인, 백그라운드 CG, 오브젝트 스프라이트, 패키징, 영상, 웹사이트 -2013년 04월 21일부터"
    old "chibilis studio"
    new "치비리스 스튜디오"
    old "Animation, Character Sprites, CG Sprites -From March 10, 2015"
    new "애니메이션, 캐릭터 스프라이트, CG 스프라이트 -2015년 03월 10일부터"
    old "Brian Connors"
    new "브라이언 코너스"
    old "English Translation Adviser -June 3, 2015~July 1, 2017"
    new "영어 번역 고문 -2015년 06월 03일~2017년 07월 01일"
    old "Ga Younghee"
    new "가영희"
    old "English Translator -April 11, 2015~June 10, 2016"
    new "영어 번역 -2015년 04월 11일~2016년 06월 10일"
    old "IVY"
    new "아이비"
    old "Chinese Translator -July 25, 2016~February 10, 2018"
    new "중국어 번역 -2016년 7월 25일~2018년 2월 10일"
    old "Adam Patric Kratz"
    new "애덤 패트릭 크러츠"
    old "Roman Koledin"
    new "로만 콜레딘"
    old "Russian Translator -August 28, 2016~December 7, 2017"
    new "러시아어 번역 -2016년 8월 28일~2017년 12월 07일"
    old "Oscar Ballona Centeno"
    new "오스카 발로나 센테노"
    old "Project Leader in Spanish, Spanish Translator -From May 29, 2017"
    new "스페인어 프로젝트 리더, 스페인어 번역 -2017년 5월 29일부터"
    old "AxelBodga"
    new "악셀 보드가"
    old "Spanish Editor -From May 29, 2017"
    new "스페인어 편집 -2017년 5월 29일부터"
    old "Yisus"
    new "예수스"
    old "Spanish Translator -From May 29, 2017"
    new "스페인어 번역 -2017년 5월 29일"
    old "Epilepsy Adviser -November 15, 2015~November 20, 2015"
    new "뇌전증 고문 -2015년 11월 15일~2015년 11월 20일"
    old "Male sprites, CG sprites -April 8, 2015~September 13, 2015"
    new "남성 스프라이트, CG 스프라이트 -2015년 04월 08일~2015년 09월 13일"
    old "Jeon Junsik"
    new "전준식"
    old "Unofficial Demo Sprites -January 5, 2015~February 25, 2015"
    new "비공식 데모 스프라이트 -2015년 01월 05일~2015년 02월 25일"
    old "Kyle Fawcett"
    new "카일 포셋"
    old "English Demo Translation Adviser -June 3, 2015~June 14, 2015"
    new "체험판 영어 번역 고문 -2015년 06월 03일~2015년 06월 14일"
    old '{font=[gui.fontawesome]}{/font} Special Thanks To'
    new '{font=[gui.fontawesome]}{/font} 이 작품은 당신에 의해 만들어졌습니다, 감사합니다.'
    old "Christopher Rice, George Winston, Kim Sooyoung, Lee Illseong, Pixabay, Shin Haechul, So Reyeon, Tom Rothamel,\nValve Corporation"
    new "김수영, 밸브 코퍼레이션, 소리연, 신해철, 이일성, 조지 윈스턴, 크리스토퍼 라이스, 탐 로타멜, 픽사베이"
    old "ACOC, Aiman Sharul, Axel Mertes, Bgame, Brandon Tanimoto, Brian Connors, BRISAK Kim Doohyeon, cheif.choi, Choi Irang, Choi Jihye, cloture, Danielle Bell, Edward N Puckering, Gary King, Gwak Jaeryeol, Han Ihyeong, Hoe Namyoon, Hong Eunki, Hwang Daehoon, Hyojoon, James Emmerson, Jeong Dongwon, Jeong Wookjin, Jeong Yoonsoo, Jianmin Zhang,\nKarina Schulze, Keira Val\'Azr, Kim Hanseol, Kim Hyeoncheol, Kim Jaeseong, Kim Jeongwoong, Kim Myeongwook,\nLee Changki, Lee Eunji, Lee Gunhae, Lee Hyejin, Lee Jaewi, Light Twins, Lim Jisoo, Maddy Wootton,\nMarshall Proudfoot, Mirumu, Mojaeng, Oh Hyeonjun, Park Hyeonjun, Park JoonKoo, Rewind, Sander Tieleman, srwss, Sung Chanaul, YottaCho, Zerial.net"
    new "B게임, BRISAK김두현, srwss, 곽재렬, 게리 킹, 김명욱, 김정웅, 김재성, 김한솔, 김현철, 다니엘 벨, 라이트트윈스, 리와인드, 마샬 프라우드풋, 모쟁, 매디 우튼, 미루무, 박준구, 박현준, 브라이언 코너스, 브랜든 타니모토, 성찬얼, 샌더 디엘레만, 아이만 샤룰, 악셀 메르테스, 애드워드 앤 퍼커링,\n오현준, 요타초, 이건해, 이재위, 이은지, 이창기, 이혜진, 임지수, 정동원, 정욱진, 정윤수, 제리얼넷, 제임스 애머슨, 지안민 장, 창조도시, 최실장,\n최이랑, 최지혜, 카리나 슐츠, 클로튀르, 키이라 발 아즈르, 한이형, 허남윤, 홍은기, 효준, 황대훈"
    old "Caz Woolley, Game Dev Robot, Gamsadev, Indie GameDev Bot, Indie Game Lover, Indie Games Devel, IndieVideoGames, Joachim Dimitri Jensen, Kim Kyeongtae, Kim Younghwan, Kurt Simon, Linda Lee King, Peter Christiansen, Sakimichi, Sebastian Haba, Spero Mcgee, The Indie Sloth, Vrachos, Xin Liu, Yu Shinhyeon"
    new "카즈 울리, 게임 데브 로봇, 게임을 만드는 사람들, 인디 게임데브 로봇, 인디 게임 러버, 인디 게임즈 디벨, 인디비디오게임즈, 김경태, 김영환,\n린다 리 킹, 브라초스, 사키미지, 세바스찬 하바, 스페로 맥기, 신 리우, 요아킴 디미트리 옌센, 유신현, 인디 나무늘보, 커트 사이먼,\n피터 크리스티안센"
    old "{font=[gui.fontawesome]}{/font} The information is unknown at this time."
    new "{font=[gui.fontawesome]}{/font} 현재 알고 있는 정보가 없습니다."
    old "{b}Choi Ga-yeon{/b}"
    new "{b}최가연({font=gui/fonts/DroidSansFallback.ttf}崔佳妍{/font}){/b}"
    old "{b}Birth:{/b} April 19th, 1986"
    new "{b}생년월일:{/b} 1986년 4월 19일"
    old "{b}Blood Type:{/b} A(RH+)"
    new "{b}혈액형:{/b} A형(RH+)"
    old "{b}Height / Weight:{/b} 165cm / 48kg"
    new "{b}키 / 몸무게:{/b} 165cm / 48kg"
    old "{b}Bio:{/b} Discouraged worker, Temporary absence from Health Administration of Yonsei University"
    new "{b}전기:{/b} 실망실업자, 연세대학교 보건과학대학 보건행정학과 휴학"
    old "{b}Bio:{/b} Discouraged worker, Temporary absence from Health Administration of ○○ University"
    new "{b}전기:{/b} 실망실업자, ○○대학교 휴학"
    old "{b}Certificates:{/b} 1st class Hospital Coordinator, Hospital Administrator"
    new "{b}보유자격:{/b} 1급 병원코디네이터, 병원행정사"
    old "{b}Likes:{/b} Bagels, Margherita pizza, Sweet rice bun"
    new "{b}좋아하는:{/b} 깨찰빵, 마르게리타 피자, 베이글"
    old "{b}Dislikes:{/b} Capitalism, Doctors, Members of Parliament"
    new "{b}싫어하는:{/b} 국회의원, 의사, 자본주의"
    old "{b}Choi Hye-na{/b}"
    new "{b}최혜나({font=gui/fonts/DroidSansFallback.ttf}崔慧娜{/font}){/b}"
    old "{b}Birth:{/b} June 17th, 1989"
    new "{b}생년월일:{/b} 1989년 6월 17일"
    old "{b}Blood Type:{/b} O(RH+)"
    new "{b}혈액형:{/b} O형(RH+)"
    old "{b}Height / Weight:{/b} 168cm / 48kg"
    new "{b}키 / 몸무게:{/b} 168cm / 48kg"
    old "{b}Bio:{/b} Karaoke helper, Graduated in Tourism Food & Beverage of Korea Hotel Technical College"
    new "{b}전기:{/b} 노래방 도우미, 한국호텔관광전문학교 관광식음료과 졸업"
    old "{b}Bio:{/b} Karaoke helper, Graduated in Tourism Food & Beverage of ○○"
    new "{b}전기:{/b} 노래방 도우미, ○○학교 관광식음료과 졸업"
    old "{b}Certificates:{/b} 2nd class Barista"
    new "{b}보유자격:{/b} 2급 바리스타"
    old "{b}Likes:{/b} Money, Photography, Ga-yeon, Drinking"
    new "{b}좋아하는:{/b} 돈, 사진찍기, 언니, 음주가무"
    old "{b}Dislikes:{/b} Oryide, Sweet rice bun, Nightclub"
    new "{b}싫어하는:{/b} 깨찰빵, 나이트 클럽, 술주정"
    old "{b}Lee Seol-ah{/b}"
    new "{b}이설아({font=gui/fonts/DroidSansFallback.ttf}李雪雅{/font}){/b}"
    old "{b}Birth:{/b} December 7th, 1986"
    new "{b}생년월일:{/b} 1986년 12월 7일"
    old "{b}Died:{/b} October 3rd, 2006"
    new "{b}향년월일:{/b} 2006년 10월 3일"
    old "{b}Height / Weight:{/b} 158cm / 55kg"
    new "{b}키 / 몸무게:{/b} 158cm / 55kg"
    old "{b}Bio:{/b} Maid of Lauah"
    new "{b}전기:{/b} 라우비즈의 시녀"
    old "{b}Certificates:{/b} Craftsman Piano Tuner"
    new "{b}보유자격:{/b} 피아노조율기능사"
    old "{b}Likes:{/b} Ga-yeon, Herself, Papa, Taejin"
    new "{b}좋아하는:{/b} 아빠, 자기 자신, 최가연, 최태진"
    old "{b}Dislikes:{/b} Kelial, Mother, Tobacco, Truck"
    new "{b}싫어하는:{/b} 킬리엘, 엄마, 담배, 트럭"
    old "{b}Staff{/b}"
    new "{b}아르바이트{/b}"
    old "{b}Clerk{/b}"
    new "{b}직원{/b}"
    old "{b}Park Misun{/b}"
    new "{b}박미선({font=gui/fonts/DroidSansFallback.ttf}朴美仙{/font}){/b}"
    old "{b}Birth:{/b} April 28th, 1974"
    new "{b}생년월일:{/b} 1974년 4월 28일"
    old "{b}Height / Weight:{/b} 168cm / 47kg"
    new "{b}키 / 몸무게:{/b} 168cm / 47kg"
    old "{b}Bio:{/b} Conductor of Business Management in Arno Restaurant franchise, Essayist, Graduated in SNU Business School"
    new "{b}전기:{/b} 아르노 레스토랑 프렌차이즈 경영관리부서 차장, 서울대학교 경영대학원 졸업, 수필가"
    old "{b}Bio:{/b} Conductor of Business Management in Arno Restaurant franchise"
    new "{b}전기:{/b} 아르노 레스토랑 프렌차이즈 경영관리부서 차장"
    old "{b}Certificates:{/b} Doctor of Business Administration, Advanced level of TEPS, Special level of TESAT, Top level of MK TEST"
    new "{b}보유자격:{/b} 경영학박사, 매경 TEST 최우수, TEPS 상급, TESAT S급"
    old "{b}Likes:{/b} Acoustic guitar, Challenge, Taejin, Writing"
    new "{b}좋아하는:{/b} 글쓰기, 도전, 최태진, 통기타"
    old "{b}Dislikes:{/b} Electronic products, Game, Mantis, Sloth"
    new "{b}싫어하는:{/b} 게임, 나태, 사마귀, 전자제품"
    old "{b}Interviewer{/b}"
    new "{b}면접관{/b}"
    old "{b}Birth:{/b} Top Secret"
    new "{b}생년월일:{/b} 일급기밀"
    old "{b}Height / Weight:{/b} Top Secret"
    new "{b}키 / 몸무게:{/b} 일급기밀"
    old "{b}BWH:{/b} Top Secret"
    new "{b}BWH:{/b} 일급기밀"
    old "{b}Bio:{/b} Conductor of Business Management in ○○"
    new "{b}전기:{/b} ○○ 프렌차이즈 경영관리부서 차장"
    old "{b}Kim Yunwoo{/b}"
    new "{b}김윤우({font=gui/fonts/DroidSansFallback.ttf}金允宇{/font}){/b}"
    old "{b}Birth:{/b} January 19th, 1986"
    new "{b}생년월일:{/b} 1986년 1월 19일"
    old "{b}Blood Type:{/b} AB(RH+)"
    new "{b}혈액형:{/b} AB형(RH+)"
    old "{b}Height / Weight:{/b} 172cm / 58kg"
    new "{b}키 / 몸무게:{/b} 172cm / 58kg"
    old "{b}Bio:{/b} Bassist of The Ghost Crying"
    new "{b}전기:{/b} 귀곡성 밴드 베이시스트"
    old "{b}Bio:{/b} Bassist of ○○"
    new "{b}전기:{/b} ○○밴드 베이시스트"
    old "{b}Likes:{/b} Bob Dylan, Choi Ga-yeon, Yu Jaeha"
    new "{b}좋아하는:{/b} 밥 딜런, 유재하, 최가연"
    old "{b}Dislikes:{/b} Auditions, Management, Soju"
    new "{b}싫어하는:{/b} 매니지먼트, 소주, 오디션"
    old "{b}Choi Taejin{/b}"
    new "{b}최태진({font=gui/fonts/DroidSansFallback.ttf}崔泰镇{/font}){/b}"
    old "{b}Birth:{/b} March 28th, 1986"
    new "{b}생년월일:{/b} 1986년 3월 28일"
    old "{b}Blood Type:{/b} B(RH+)"
    new "{b}혈액형:{/b} B형(RH+)"
    old "{b}Height / Weight:{/b} 182cm / 73kg"
    new "{b}키 / 몸무게:{/b} 182cm / 73kg"
    old "{b}Bio:{/b} Lead Guitarist of The Ghost Crying, Graduated in Seoul Institute of the Arts"
    new "{b}전기:{/b} 귀곡성 밴드 리드 기타리스트, 서울예술대학교 실용음악학부 졸업"
    old "{b}Bio:{/b} Lead Guitarist of ○○, Graduated in ○○"
    new "{b}전기:{/b} ○○밴드 리드 기타리스트, ○○대학교 졸업"
    old "{b}Certificates:{/b} Bachelor of Arts Degree in Gebrauchsmusik"
    new "{b}보유자격:{/b} 실용음악예술학사"
    old "{b}Likes:{/b} Marylin Manson, NIN, Rammstein, Shin Junghyeon,\nShin Haechul"
    new "{b}좋아하는:{/b} 나인 인치 네일스, 람슈타인, 마릴린 맨슨, 신중현, 신해철"
    old "{b}Dislikes:{/b} Eggplant, Ginger, Idol"
    new "{b}싫어하는:{/b} 가지, 생강, 아이돌"
    old "{b}Park Hyeongsik{/b}"
    new "{b}박형식({font=gui/fonts/DroidSansFallback.ttf}朴炯植{/font}){/b}"
    old "{b}Birth:{/b} December 17th, 1979"
    new "{b}생년월일:{/b} 1979년 12월 17일"
    old "{b}Bio:{/b} Physician, Graduated in School of Medicine of Sungkyunkwan University"
    new "{b}전기:{/b} 내과의사, 성균관대학교 의과대학 졸업"
    old "{b}Bio:{/b} Physician, Graduated in ○○"
    new "{b}전기:{/b} 내과의사, ○○대학교 졸업"
    old "{b}Certificates:{/b} Medical Licence"
    new "{b}보유자격:{/b} 의사면허"
    old "{b}Likes:{/b} Fame, Money, Power"
    new "{b}좋아하는:{/b} 권력, 돈, 명예"
    old "{b}Dislikes:{/b} Capitalism, Members of Parliament, Soju"
    new "{b}싫어하는:{/b} 국회의원, 소주, 자본주의"
    old "{b}Doctor{/b}"
    new "{b}내과의사{/b}"
    old "{b}Bio:{/b} Physician"
    new "{b}전기:{/b} 내과의사"
    old "{font=[gui.fontawesome]}{/font} Stop"
    new "{font=[gui.fontawesome]}{/font} 재생중지"
    old "{font=[gui.fontawesome]}{/font} Shuffle"
    new "{font=[gui.fontawesome]}{/font} 순서 섞기"
    old "{font=[gui.fontawesome]}{/font} Loop"
    new "{font=[gui.fontawesome]}{/font} 반복재생"
    old "{font=[gui.fontawesome]}{/font} Previous"
    new "{font=[gui.fontawesome]}{/font} 이전"
    old "{font=[gui.fontawesome]}{/font} Next"
    new "{font=[gui.fontawesome]}{/font} 다음"
    old "{font=[gui.fontawesome]}{/font} Random"
    new "{font=[gui.fontawesome]}{/font} 무작위재생"
    old "{font=[gui.fontawesome]}{/font} Bandcamp"
    new "{font=[gui.fontawesome]}{/font} 밴드캠프"
    old "{font=[gui.fontawesome]}{/font} Soundcloud"
    new "{font=[gui.fontawesome]}{/font} 사운드클라우드"
    old "{font=[gui.fontawesome]}{/font} Add to cart"
    new "{font=[gui.fontawesome]}{/font} 장바구니 담기"
    old '{size=[gui.quick_button_text_size]}Previous{/size}'
    new '{size=[gui.quick_button_text_size]}이전{/size}'
    old '{size=[gui.quick_button_text_size]}Next{/size}'
    new '{size=[gui.quick_button_text_size]}다음{/size}'
    old '{size=[gui.quick_button_text_size]}Loop{/size}'
    new '{size=[gui.quick_button_text_size]}반복재생{/size}'
    old '{size=[gui.quick_button_text_size]}Shuffle{/size}'
    new '{size=[gui.quick_button_text_size]}순서 섞기{/size}'
    old "Prologue"
    new "프롤로그"
    old "Discouraged Worker"
    new "실망실업자"
    old "Depressive Disorder"
    new "우울 장애"
    old "Reclusive Outsider"
    new "은둔형 외톨이"
    old "IMF Crisis"
    new "IMF 경제위기"
    old "Anxiety Disorder"
    new "불안 장애"
    old "Medical Referral"
    new "진료 의뢰서"
    old "Bridge of the Life"
    new "생명의 다리"
    old "Epilogue"
    new "에필로그"
    old "Accident"
    new "사건발생"
    old "Flowery Mornings and Moonlit Nights"
    new "꽃이 핀 아침과 달 밝은 저녁"
    old "Red Dialogue Window"
    new "붉은색 지문 창"
    old "Seohae Grand Bridge"
    new "서해대교 29중 추돌사고"
    old "Mahalath Leannoth"
    new "마할랏르안놋"
    old " A discouraged worker is a person of legal employment age who is not actively seeking employment, or who can not find employment after long-term unemployment. This is usually because an individual has given up looking or has had no success in finding a job, hence the term \"discouraged\".\n\n{a=https://en.wikipedia.org/wiki/Discouraged_worker}Wikipedia{/a}\n\n Discouraged workers are classified as an economically inactive population and not included in the unemployment rate, although they are actually unemployed.\n\n And this artificially causes a decrease in the unemployment rate in official statistics, in spite of an actually higher unemployment rate. In the case of Korea, the Subsidiary Employment Index, which includes the not-calculated unemployed, was reported first in November, 2014, and accordingly, the hidden problems in Korea's employment-population ratio and discouraged workers have surfaced."
    new " 실망실업자의 사전적인 의미는 취업을 원하지만, 일자리를 구하지 못해 구직을 단념한 사람을 말한다. 이들은 법적으로 직장을 구할 수 있는 연령대지만 보통은 개인이 직장을 얻는 것을 포기했거나 성공하지 못했기 때문에 적극적으로 구직활동을 하지 않거나,  장기간 실업상태 이후 구직활동을 하지 않는다. 따라서 \"실망실업자\"라는 용어로 쓴다.\n\n 실망실업자는 사실상 실업자이지만 실업자의 조건을 만족하지 못하기 때문에 비경제활동인구로 분류돼 실업자 통계에 포함되지 않는다.\n\n 이 때문에 체감 실업률이 높아져도 실업자 통계에서는 실업률이 하락하는 현상이 나타나며, 한국은 2014년 11월에 숨은 실업자를 포함한 보조고용지표를 처음 발표했고 한국의 고용률과 실망실업자에 대한 문제가 표면에 드러났다."
    old " Reclusive outsider is the phenomenon of reclusive adolescents or adults who withdraw from social life, often seeking extreme degrees of isolation and confinement. The term reclusive outsider refers to both the sociological phenomenon in general as well as to people belonging to this societal group.\n\n{a=https://en.wikipedia.org/wiki/Hikikomori}Wikipedia{/a}\n\n Choi Ga-yeon, a heroine of \"Discouraged Workers\", suffered from depressive disorder because of the sudden firing from her job and breaking-up with her lover.\n\n In addition, with her continuous failure to get a job, her anxiety disorder symptoms only became worse. And she naturally has become a hikikomori(a person who becomes a recluse and gives up any social life) after she gave up trying to get a job."
    new " 은둔형 외톨이는 방이나 집 등의 특정 공간에서 나가지 못하거나 나가지 않는 사람과 그러한 현상 모두를 일컫는다. 2005년 일본의 정신과 의사 사이토 다마키가 자신의 저서를 통해 히키코모리라는 개념으로 처음 소개하였다.\n\n{a=https://ko.wikipedia.org/wiki/히키코모리}위키피디아{/a}\n\n \"실망실업자\"의 주인공 최가연은 직장에서 해고당하고 연인과 이별한 후유증으로 우울 장애를 앓았으며, 계속되는 구직 실패로 인해 불안 장애를 앓게 되면서 그녀의 증세는 더욱 심해졌다.\n\n 구직을 포기한 후에는 주변인들과 점점 멀어지면서 자연스럽게 은둔형 외톨이가 됐다."
    old "Lee Yunseok -YGGDRASIL STUDIO"
    new "이윤석 -익드라실 스튜디오"
    old " Generally, a medical referral is issued by a hospital when sending a patient to another hospital. Ga-yeon has received medical treatment from a psychiatrist since she was fired from the hospital where she was working as a coordinator. In spite of long treatment, her condition did not improve at all, and the hospital issued a medical referral to another hospital. But Ga-yeon refused the referral as she felt the psychiatrist gave up on her, and this made her fall into despair. So she didn't seek any more psychiatric treatment.\n\n Since many people still think negatively about seeking psychiatric treatment, and have unfavorable perceptions about those who seek it, often, people who need help with their problems, tend to avoid getting the help they need, both here in Korea and elsewhere in the world.\n\n Also in the case of Ga-yeon, she hasn't talked about it, regarding it as her embarrassing secret. The medical referral Yunwoo found in Ga-yeon's mailbox was actually a referral that Hye-na arranged for her.\n\n Actually, the description shown in the medical referral in the \"Ga-yeon and Yunwoo\" part of the story, is almost the same as the one commonly issued in a real hospital in Korea."
    new " 진료의뢰서는 보통 병원에서 타원으로 환자를 보낼 때 발행한다. 가연은 코디네이터로 일하던 내과에서 해고당했을 때부터 신경정신과에서 진료를 받아왔지만 호전되지 않았고, 병원에서는 타원으로 진료를 의뢰하는 의뢰서를 발행했다. 그러나 가연은 의사가 자신을 포기했다는 실망과 절망감으로 의뢰서를 거부했고 더는 정신과를 찾지 않았다.\n\n  아직까지도 한국에서는 신경정신과에 부정적인 사람이 많으며, 신경정신과에서 진료를 받았다는 사실 역시 상대방에게 부정적인 인식을 하게 만들기 때문에 치료를 위해 진료를 받는 환자 자신도 거부감을 느끼는 것이 보통이다.\n\n 가연 역시 이것을 자신의 치부라 생각하여 아무에게도 말하지 않고 숨겼다. 윤우가 우체통에서 발견한 진료의뢰서는 혜나가 꽂아놓은 것이다.\n\n \"가연과 윤우\"에서 묘사하는 진료의뢰서의 내용은 실제 한국의 신경정신과에서 발행하는 그것과 같다."
    old " Anxiety disorders are a category of mental disorders characterized by feelings of anxiety and fear, where anxiety is a worry about future events and fear is a reaction to current events. These feelings may cause physical symptoms, such as a racing heart and shakiness.\n\n{a=https://en.wikipedia.org/wiki/Anxiety_disorder}Wikipedia{/a}\n\n My mother had suffered from panic disorder for almost eight years, and she used to complain of pain and hyperpnea in certain and sometimes new and unexpected situations(Hyperpnea is the need to breathe more deeply because the person experiencing it feels light headed or otherwise feels they need more oxygen for various reasons.).\n\n And someone whom I know had anxiety disorder, and she suffered from a tic disorder including repetitive eye blinking and apnea when she feels anxiety in those same kinds of situations. She was even very dependent on alcohol and showed symptoms of caffeine addiction as well. Standing by my mother's and her side, and watching their pain and experiencing it with them, I hoped to help set them free from those painful days. But as time went by, I found I was getting numb with their pain, and at that moment, I felt extremely ashamed as a human being."
    new " 불안 장애의 사전적 의미는 병적인 불안으로 인하여 과도한 심리적 고통을 느끼거나 현실적인 적응에 심각한 어려움을 겪는 경우를 말한다.\n\n  내 어머니는 8년간 공황 장애를 앓았었고, 특정한 또는 불특정한 어떤 상황에서 과호흡을 동반한 고통을 호소했다. 어느 누군가는 불안 장애 환자였는데, 특정한 또는 불특정한 상황에서 불안해지면 눈을 계속해서 깜빡거리는 틱 증세와 무호흡을 동반했으며, 알코올 의존과 카페인 중독 증세까지 보였다.\n\n 이러한 상황들을 지켜보고 함께 부딪히면서 나는 그 사람들을 낫게 해주고 싶었다. 그러나 시간이 지남에 따라 그들의 고통에 무뎌져가는 내 자신을 발견했고, 인간으로서의 자괴감에 빠졌다."
    old " Depressive disorder is a mental disorder characterized by a pervasive and persistent low mood that is accompanied by low self-esteem and by a loss of interest or pleasure in normally enjoyable activities. The term \"depression\" is used in a number of different ways. It is often used to mean this syndrome but may refer to other mood disorders or simply to a low mood. Major depressive disorder is a disabling condition that adversely affects a person's family, work or school life, sleeping and eating habits, and general health.\n\n{a=https://en.wikipedia.org/wiki/Major_depressive_disorder}Wikipedia{/a}\n\n Choi Ga-yeon, a heroine of \"Discouraged Workers\", suffered from depressive disorder because of the sudden firing from her job and breaking-up with her lover. In addition, with her continuous failure to get a job, her anxiety disorder symptoms only became worse. And she naturally has become a hikikomori(a person who becomes a recluse and gives up any social life) after she gave up trying to get a job."
    new " 우울증의 사전적 의미는 병리적인 수준의 우울한 상태를 말한다. 일시적으로 우울한 기분을 느끼는 우울감과는 다르다. 실망실업자의 주인공 최가연은 직장에서 해고당하고 연인과 이별한 후유증으로 우울 장애를 앓았으며, 계속되는 구직 실패로 인해 불안 장애를 앓게 되면서 그녀의 증세는 더욱 심해졌다. 구직을 포기한 후에는 주변인들과 점점 멀어지면서 자연스럽게 은둔형 외톨이가 됐다."
    old " \"Bridge of the life\" was actually a sort of attempt using advanced technological methods to prevent suicide. By trying to have a conversation with a pedestrian through hopeful words and changing their desperation into hope, the designers thought suicidal people might be encouraged not to end their lives, but, in the event that failed, there was still the traditional physical anti-suicide barrier. The sensors mounted on every section of the bridge detects the exact location of a pedestrian as she/he walks by and the bridge lights the hopeful word up in the right position for a pedestrian to read.\n\n The very first bridge of life opened on Mapo Bridge, Korea on September 26, 2012, and was sponsored by Seoul City and Samsung Life Insurance. Mapo Bridge was chosen as the first installation of this new technology because it has been notorious as the place with the highest suicide rate. And the second one opened on Hangang Bridge, Korea on November 5, 2013, sponsored by Korea Health Promotional Foundation.\n\n And the ad for \"Bridge of the life\" received 39 awards in the International Advertising Festival and obtained excellent advertising effects. But regardless of this successful record, the rate of suicides by death leap has steadily increased. According to statistics, installing closed circuit television on the public bridges was more helpful in preventing suicide jumps and rescuing suicide jumpers who actually did jump than the bridge of life technology.\n\n As a result of the Samsung Life Insurance's decision to discontinue their operational support for \"Bridge of the Life\" on Mapo Bridge in September 2015, the automatic detection sensor has not worked since December 1, 2015 and the website of Bridge of the Life was also closed.\n\n In fact, Hangang Bridge wasn't yet built at the time that the \"Discouraged workers\" story takes place. But in the game, it was set as a background to let Yunwoo try to think where Ga-yeon disappeared to."
    new " 생명의 다리는 기존의 물리적인 자살방지 수단을 벗어나, 희망문구를 통해 보행자와의 소통을 형성하여 비관을 희망으로 바꾸고 자살을 방지하기 위한 첨단 방식의 시도였다. 구간마다 설치된 센서가 보행자의 보폭에 맞추어 위치를 감지하고, 그 위치에 설치된 희망문구 조명이 켜지는 방식이다.\n\n 2012년 9월 26일 서울특별시와 삼성생명이 과거부터 자살률 1위라는 부정적인 인식이 있는 마포대교에 생명의 다리를 개통했고, 2013년 11월 5일에는 한국건강증진재단이 힘을 더해 한강대교에 생명의 다리를 개통했다.\n\n 생명의 다리 영상은 국제 광고제에서 39개 부문을 수상하며 뛰어난 광고효과를 보였지만 투신율은 이것과 무관하게 점점 증가하고 있으며, 오히려 폐쇄회로TV 설치와 확대가 투신시도를 막거나 투신한 사람을 구조하는 데 도움이 되고 있다.\n\n  2015년 9월 삼성생명이 마포대교 생명의 다리 운영 지원을 중단함에 따라 2015년 12월 1일부터 자동 감지센서가 작동하지 않고 있으며, 생명의 다리 웹사이트 또한 폐쇄됐다.\n\n 실망실업자 무대의 실제 시기는 한강대교 생명의 다리가 개통되기 전이나, 윤우로 하여금 사라진 가연이 어디로 향했을지 고민하게 하려고 존재하는 것으로 설정했다."
    old " The Asian financial crisis was a period of financial crisis that gripped much of East Asia beginning in July 1997 and raised fears of a worldwide economic meltdown due to financial contagion.\n\n The crisis started in Thailand with the financial collapse of the Thai baht after the Thai government was forced to float the baht due to lack of foreign currency to support its fixed exchange rate, cutting its peg to the U.S. dollar, after exhaustive efforts to support it in the face of a severe financial over-extension that was in part real estate driven.\n\n{a=https://en.wikipedia.org/wiki/1997_Asian_financial_crisis#South_Korea}Wikipedia{/a}\n\n At the time, Thailand had acquired a burden of foreign debt that made the country effectively bankrupt even before the collapse of its currency. As the crisis spread, most of Southeast Asia and Japan saw slumping currencies, devalued stock markets and other asset prices, and a precipitous rise in private debt.\n\n Indonesia, South Korea and Thailand were the countries most affected by the crisis. Hong Kong, Laos, Malaysia and the Philippines were also hurt by the slump. Brunei, China, Singapore, Taiwan and Vietnam were less affected, although all suffered from a loss of demand and confidence throughout the region."
    new " 대한민국의 IMF 구제금융 요청은 국가부도 위기에 처한 대한민국이 IMF으로부터 자금을 지원받는 양해각서를 체결한 사건이다. 1997년 12월 3일에 이루어졌다. 기업이 연쇄적으로 도산하면서 외환보유액이 급감했고 IMF에 20억 달러 긴급 융자를 요청하였다. 외환 위기 속에 대한민국은 외환보유액이 한때 39억 달러까지 급감했지만, IMF에서 195억 달러의 구제금융을 받아 간신히 국가부도 사태는 면했다.\n\n 태국, 홍콩, 말레이시아, 필리핀, 인도네시아 등 동남아시아의 연쇄적 '외환 위기' 속에 대한민국 정부의 외환관리정책의 미숙과 실패가 'IMF 환란'의 직접적인 원인이다. 대한민국 제14대 대통령 김영삼은 1997년 11월 10일에 이루어진 강경식 경제부총리와의 통화 이전까지 외환위기의 심각성조차 모르고 있었다.\n\n{a=https://ko.wikipedia.org/wiki/대한민국의_IMF_구제금융_요청}위키피디아{/a}\n\n 많은 회사들의 부도 및 경영 위기가 나타났고, 이 과정에서 대량 해고와 경기 악화로 인해 대한민국의 온 국민이 큰 어려움을 겪었다. 이 사건이 일어난 직후인 1997년 12월 18일에 대한민국 제15대 대통령 선거가 치러졌고, 이 선거에서 여당은 야당에게 패배하여 정권 교체가 이루어졌다.\n\n 1998년 12월, IMF 긴급 보관 금융에 18억 달러를 상환한 것을 계기로 대한민국은 금융 위기로부터 서서히 빠져나갔다. 2000년 12월 4일, 김대중 대통령은 \"국제 통화 기금의 모든 차관을 상환하였고, 우리나라가 'IMF 위기'에서 완전히 벗어났다\"라고 공식 발표하였다. 2001년 8월 23일, 대한민국에 대한 IMF 관리 체제가 종료되었다."
    old " \"Accident\" tells what happens after \"Epilogue\" which is the basic ending of \"Discouraged Workers\".\n\n Ga-yeon reached out her hand toward Yunwoo, but at that moment, she blacked out and fell off the bridge. And Yunwoo threw himself into the river to save her. A few days later, they rose to the surface, and one passerby's report told their deaths to the world.\n\n If Yunwoo hadn't found his wallet, Ga-yeon would die alone while he was haggling over the taxi fare."
    new " \"사건발생\"은 \"에필로그\"에서 연결되는 \"실망실업자\"의 기본 결말이다.\n\n 가연이 윤우에게 손을 내밀었지만 곧 정신을 잃고 대교 아래로 추락했다. 그러자 윤우가 그녀를 구하기 위해 강물로 몸을 던졌다. 며칠 후 둘은 강물 위로 떠올랐고, 지나가던 행인의 신고로 둘의 죽음을 세상에 알렸다.\n\n 만약 윤우가 가연의 방에서 지갑을 찾지 못했다면, 그가 택시기사와 택시비 문제로 승강이를 벌일 동안 가연은 죽는다."
    old " As a hospital coordinator, Ga-yeon fell in love with a doctor at the hospital she was working in and they had an affair even though the doctor was a married man. When the director found out, she was fired. For over a year she tried to find another job, but her mental uneasiness eventually made her give up and she became a recluse.\n\n A year later, in the spring of 2013, her younger sister, Hye-na, and her first love Yunwoo come to her.\n\n A story about the dark side of today's youth and serious life events happening around Ga-yeon."
    new " 병원 코디네이터라는 직업을 가지고 있던 가연은 자신이 근무하는 병원의 의사와 사랑을 하게 되었다. 하지만 의사에게는 아내가 있었고, 둘의 사랑은 불륜이었다. 사실을 알게 된 원장에 의해 해고된 후 다른 직장을 찾아다니지만, 그녀의 정신적인 불안과 현실의 벽으로 1년 동안 직장을 구하지 못하고 결국 취업을 포기한다.\n\n 그로부터 다시 1년이 지난 2013년 봄의 대한민국, 은둔형 외톨이가 되어버린 그녀에게 찾아온 여동생 혜나와 첫사랑 윤우.\n\n 이 시대를 살아가는 청춘들의 어두운 단면과 가연을 중심으로 벌어지는 가볍지 않은 일상."
    old " \"Flowery Mornings and Moonlit Nights\" is the true ending which assumes that Ga-yeon didn't faint and grabbed Yunwoo's hand in \"Epilogue\". Originally \"Discouraged Workers\" was intended to end with the \"Accident\" story as the true ending. But after deciding to release it in the market, this was chosen as the true ending.\n\n Ga-yeon finds the culprit who spread the video, with the help of Yunwoo, and reports him to the police. After that, she tries to find a job, but it's still not easy for her. Even some interviewers who know her, hurt her.\n\n Yunwoo just stays by her side and tries to protect her without saying anything, and Hye-na helps Ga-yeon to work part-time at the cafe where she's working. Ga-yeon works hard every day, grateful for being allowed to work there. One day, the cafe manager gives her a letter of recommendation from the general manager of the head office, and Ga-yeon gets an opportunity to have an interview for a large affiliated store run by the head office. And by chance, the interviewer she meets with for the job is her old boss, who during her schooldays, originally gave her the idea of her dream job being a restaurant manager. Ga-yeon passes the interview with ease, and finally, she starts to move towards her dream."
    new " \"꽃이 핀 아침과 달 밝은 저녁\"은 \"에필로그\"에서 가연이 정신을 잃지 않고 윤우의 손을 잡았을 때를 가정한 진짜 결말이다. 실망실업자는 본래 \"사건발생\"이 결말이었으나 상용 출시를 결정한 후 진짜 결말로 이것을 채택했다.\n\n 가연은 윤우의 도움으로 동영상 유포자를 구속시킨다. 이후 직장을 구하기 위해 노력하지만 쉽지 않고, 가연을 알아보는 사람들과 면접관들에게 상처받게 된다.\n\n 윤우는 그런 가연의 옆에서 그녀를 묵묵히 지켜주고, 혜나는 자신이 일하는 카페에 가연을 아르바이트로 일할 수 있도록 도와준다. 아르바이트지만 일을 할 수 있다는 것에 감사하며 하루하루 열심히 일하던 가연에게, 카페 매니저는 본사 차장의 추천서를 받아 그것을 건넨다. 가연은 추천서를 들고 본사에서 준비하는 대형 가맹점의 면접을 보러 가고, 놀랍게도 학창시절 가연에게 외식업 매니저의 꿈을 꾸게 해준 캡틴을 면접관으로 만난다. 이 면접에서 당당하게 합격한 가연은 자신의 꿈을 향해 나아가기 시작한다."
    old " A chain reaction collision, involving 29 vehicles, happened at 7:50am on October 3, 2006, Korean time, on Seohae Grand Bridge in South Korea. This collision happened due to a thick fog, and it left 12 people dead and about 50 injured. According to the investigation, the accident occurred not only because of bad weather, but also because some drivers were speeding as well as shoulder riding. But whatever the reason was, the damage was almost 4 billion won, which was the most awful and costly accident in Korean car insurance history.\n\n \"Lee Seol-ah\" is a fictitious character who died in this accident. This woman, who died at the age of 21, still in the flower of her youth, visits the world she used to live in after she died, and watches people whom she loved and shared friendships with. One day, she meets Ga-yeon who helped her in the past. To prevent her death, she decides to help Yunwoo."
    new " 서해대교 29중 추돌사고는 한국 표준시로 2006년 10월 3일 오전 7시 50분경에 일어났다. 짙은 안개로 말미암은 29중 연쇄 추돌 사고가 발생하여, 12명이 사망하고 50여 명이 부상하는 인명 피해를 냈다. 기상 상황뿐만 아니라 운전자들의 과속, 일부 운전자들의 갓길 주행도 피해의 원인이었다. 피해액은 약 40억 원으로, 한국의 자동차보험 역사상 가장 큰 사고로 기록되는 불명예를 안았다.\n\n{a=https://ko.wikipedia.org/wiki/서해대교#2006.EB.85.84_.EC.97.B0.EC.87.84_.EC.B6.94.EB.8F.8C_.EC.82.AC.EA.B3.A0}위키피디아{/a}\n\n \"이설아\"는 이 끔찍한 사고로 사망한 가상의 인물이다. 21세의 꽃다운 나이에 사망한 이 여성은 자신이 살던 세계를 방문해 사랑하는 사람들과 우정을 나눈 사람들을 지켜보기로 했고, 과거 자신을 도와줬던 가연의 죽음을 막기 위해 윤우를 돕기로 한다."
    old " In \"Discouraged Workers\", a word box in red color is used to show the words and thoughts of Ga-yeon and a clerk Because when the basic scenario was developed, they are actually not alive.\n\n But when Ga-yeon is talking with her mom on the phone, the black box is used out of consideration for her mother."
    new " 실망실업자에서 붉은색 지문 창은 주인공 가연과 직원의 생각과 말을 출력할 때 사용된다. 이들은 기본 시나리오에서 실제 세계시각을 기준으로 사망한 상태기 때문이다.\n\n 가연이 어머니와 통화할 때는 그녀의 어머니를 배려하여 검은색 지문 창을 사용했다."
    old "{font=[gui.fontawesome]}{/font} Find the diary in the room."
    new "{font=[gui.fontawesome]}{/font} 가연의 방에서 그녀의 일기를 찾으십시오."
    old "My cool captain!"
    new "멋쟁이 캡틴 언니"
    old "My captain's tear"
    new "캡틴 언니의 눈물"
    old "Went to see Yunwoo"
    new "면회를 가다"
    old "I rejected him"
    new "그의 고백을 거절하다"
    old "As a friend"
    new "친구로"
    old "My days in hospital"
    new "병원생활"
    old "Observing a doctor"
    new "의사를 관찰하다"
    old "His wife"
    new "그의 아내"
    old "Farewell"
    new "이별"
    old "I miss him"
    new "그리움"
    old "Sign"
    new "조짐"
    old "A lunatic"
    new "정신병자"
    old "My friend, Eunju"
    new "친구와 함께"
    old "Getting a job"
    new "구직활동"
    old "Rubbish and rubbish can"
    new "쓰레기와 쓰레기통"
    old "Dying message"
    new "다잉 메시지"
    old " It's been more than a month since I started working in a family restaurant. In the beginning, it was really hard to carry a tray and I even broke a few dishes. But now, I feel like I'm getting better and better. Sometimes, customers tip me as well, and also the other staff often praises my work. I'm especially good at…. hmmm…. well, it's too many to write them all down here! Later!\n\n However, the captain looks really cool. She's beautiful, smart, and also good at her work. Oh, she seems to be strong as well, as she usually carries heavy things by herself!\n\n I saw her carrying two metal trays stacked with dishes with just her two hands. It is hard even for men, but she's such a superwoman. How the hell can she do that? I hope I can do work as well as her someday."
    new " 패밀리 레스토랑 아르바이트를 시작한 지 한 달이 넘었다. 처음에는 트레이 중심 잡기도 어려웠고 접시도 몇 장 깨 먹었는데, 지금은 내가 생각해도 꽤 잘 하는 것 같다. 가끔 손님들이 팁을 주기도 하고, 같이 일하는 사람들한테 칭찬도 많이 듣는다. 구체적으로 내가 잘하는 것들은…. 음…, 이 한 장에 다 적기엔 너무 많으니 패스!\n\n 아! 그나저나 우리 홀 캡틴 언니는 정말 대단한 것 같다. 엄청 미인인데다 똑똑하고 일도 잘한다. 무거운 것도 척척 잘 든다.\n\n 커다란 철판 트레이에 접시를 가득 담아 한 손에 하나씩 들고 다닌다. 남자들도 하기 어려운 일인데 이 언니는 진짜 괴물이다. 어쩜 일을 저렇게 할 수 있을까? 나도 캡틴 언니처럼 일을 잘했으면 좋겠다."
    old " Today the section chief of the head office visited the restaurant. I thought the chief would be a man, but she was a young woman. She came to our restaurant and called the captain to the locker room. She passed by me while I was working there, and I saw her nametag. And I found she has the same name as a famous comedian. Funny!\n\n As the captain was not in the hall, I tried to look for her, and when I opened the door of the locker room, she looked at me in surprise and turned her face hurriedly. And she said leave her alone for a while, forcing me out of the room. She was crying.\n\n Probably the section chief made her cry. That bitch! What did the captain do wrong? Hey, I'll get even with her!! Shit!"
    new " 오늘 레스토랑에 본사 과장이 다녀갔다. 아저씨가 올 줄 알았는데 왜 젊어 보이는 여자가 와서 우리 캡틴 언니를 부르더니 라커룸으로 들어갔다. 일하고 있다가 그 여자가 내 옆을 지나가길래 슬쩍 명찰에 적힌 이름을 봤다. 유명한 개그우먼이랑 이름이 같아 외우기 쉬울 것 같다.\n\n 그런데 캡틴 언니가 홀에 보이지 않아 라커룸으로 가서 문을 열었는데 안에서 언니가 나를 보고는 급하게 고개를 돌리며 문을 닫아 잠궜다.\n\n 언니는 울고 있었다. 그 여자가 우리 캡틴 언니를 울린 것이다. 지가 과장이면 다야? 캡틴 언니가 뭘 잘못했길래 우리 언니를 울려? 어이, 박미선 과장! 내가 꼭 복수할 거다! 흥!!"
    old " I went to Cheolwon, with Eunyoung to see Yunwoo today. I didn't realize it was that cold, but when I got off the bus, I was just shocked as it was literally freezing. It didn't snow, and the wind didn't blow, but cold air made even my eyes freeze. Eunyoung and I hurried into the visitor's room to wait for Yunwoo.\n\n A few minutes later, a soldier came in - actually I recognized that he was Yunwoo as soon as I saw him! And I got the giggles. His camouflage patterned muffler looked pretty cool, but his earmuffs reminded me of a once famous singer, and I couldn't stop laughing!\n\n I told him about that singer, and he got embarrassed. Eunyoung took his earmuffs away and danced, and all of us burst into laughter.\n\n However, since we said goodbye to Yunwoo, I've felt somewhat lonesome, and I still feel that way even as I'm writing this…. why do I feel this way?"
    new " 오늘은 윤우 면회를 하려고 은영이랑 같이 철원까지 다녀왔다. 차에 있을 때는 몰랐는데 내리고 보니 너무 추워서 깜짝 놀랐다. 눈이 막 내리는 것도 아니고 바람도 잠잠한데 공기가 어찌나 차가운지 내 눈이 시릴 정도였다. 나는 은영이와 함께 서둘러 면회소에 들어가 윤우를 기다렸다.\n\n 몇 분 후에 면회소에 들어온 군인 아저씨-한눈에 윤우인 걸 알았지만-를 보고 피식하고 웃음이 새나왔다. 얼룩무늬 머플러까진 멋있다고 생각했는데 귀마개를 보니 중학생 때 본 가수 엄정화가 겹쳐 보여 웃음을 참을 수가 없었다.\n\n 멋쩍은 듯이 자리에 앉는 윤우를 보고 그 얘기를 했더니 은영이가 윤우의 귀마개를 뺏어 끼고 춤을 춰서 한바탕 또 웃음이 터졌다.\n\n 면회를 마치고 집으로 가는 차 안에서부터 일기를 쓰고 있는 지금까지, 나는 조금 쓸쓸한 기분이다. 이 감정은 뭘까…."
    old " After I parted with him, and while I was coming home, I tried really hard to fight back tears. But when I arrived in my room, I just burst into tears. Why? Why was I so mean to him? I raged at him, and told him to quit music. Why the hell did I do that?\n\n Today he told me what I've really looked forward to hearing from him, but why…. why couldn't I accept him? And why did I hurt him? I can't stop crying…."
    new " 그와 헤어지고 집으로 오는 동안 꾹 참았던 눈물이 방에 들어오자마자 쏟아져나왔다. 왜 그랬을까, 왜 그에게 그렇게 모질게 굴었을까. 나는 기어이 그에게 화를 내고 음악을 그만두라고 말해버렸다.\n\n 도대체 왜 그랬을까. 내가 그렇게 기다렸던 그 말을 그에게서 들었는데, 왜 나는 그를 받아들이지 못하고 그에게 상처만 줬을까. 눈물이 자꾸만 뚝뚝 떨어진다."
    old " I had a long conversation with Yunwoo today;\n\n You've just been discharged from the army, and I'm a student without a job. So what can we do now? You really think we can get married and start our home? Seriously? How?\n\n Besides, we're not romantically involved with each other. We're just friends. I think of you as my friend, and hope we could get along well with each other for a long time. That's all….\n\n I think I probably said it like that…. but of course it's not true that I think of him just as a friend, but…. To get back to our relationship as usual, I had to say it that way.\n\n I also said sorry that I hurt him.\n\n However, unexpectedly, it seemed he doesn't care about it. He said he was actually kidding when he asked me to marry him. And since I already refused his proposal anyway, there's nothing hard about getting along with me simply as a friend.\n\n What he said made me a little bit regretful, but anyway, we decided to leave as good friends as we've always been."
    new " 윤우와 긴 시간 대화를 나눴다.\n\n 이제 막 제대한 너와 대학생인 나. 아직 직업도 없는 우리가 무슨 수로 결혼을 하고 살림을 차리겠느냐고, 그게 가능할 것 같냐고 그에게 말했다.\n\n 그리고 우리는 사귀는 사이도 아니었고 나는 너를 친구로 생각한다고, 앞으로도 좋은 친구로 지냈으면 좋겠다고 그에게 말했다.\n\n 물론 친구로 생각한다는 말은 거짓말이었지만, 우리가 예전처럼 돌아가기 위해서는 이렇게 말해야 한다고 생각했다.\n\n 그에게 상처를 준 것에 대해서는 진심을 담아 사과했다.\n\n 뜻밖에도 그는 개의치 않는다는 듯이 대답했다. 결혼하자고 말한 건 장난이 아니었지만, 이미 거절당했고 나와 친구로 지내는 것에 아무런 불편함도 없다고. 내가 그를 불편하게 생각하지 않는다면 친구로 지내는 것에 문제가 없다고 했다.\n\n 그 말을 듣고 조금 서운하기도 했지만, 어쨌든 우리는 친구로서 관계를 유지하기로 했다."
    old " It's been almost a year since I started working in this hospital. I work as a coordinator of the hospital. I had my salary raised, and also I'm pretty satisfied with my job. My savings account with the balance which gets bigger and bigger makes me feel really happy.\n\n When I had to quit the university temporarily, I was just stunned. But now that I think about it, it was rather smart to do that, actually. Because of that choice, I was able to pay Hye-na's university tuition, without a loan.\n\n I'll save more money to send Mom and Daddy to travel on, and also support Hye-na until she gets married someday. Jeez, why is time passing so fast today? Until tomorrow, I'm going to bed!\n\n Ga-yeon, just keep it up as you've done so far!"
    new " 병원에서 일한 지 어느덧 일 년, 나는 지금 코디네이터로 일하고 있다. 처음보다 월급도 많이 올랐고, 만족스러운 직장생활을 하고 있다. 통장에 차곡차곡 쌓여가는 월급을 보면 마냥 행복하기만 하다.\n\n 학교를 휴학해야 했을 때는 눈앞이 캄캄했는데, 지금 와서 생각해보면 오히려 잘 됐다는 생각도 든다. 대출 없이 혜나 등록금도 해결할 수 있었으니까.\n\n 이대로 계속 돈 모아서 엄마 아빠 여행도 보내드리고, 혜나 결혼할 때도 보태주고 싶다. 어머, 벌써 시간이 이렇게 됐네.\n\n 내일의 최가연을 위해, 아자아자 파이팅!"
    old " Oh, my god…. how could he look like him that much? His face, way of talking, character, and even that he can't hold liquor well…. everything is just like him. He reminds me of Yunwoo a lot. And it makes me feel sad. And this keeps bothering me so much. These days, I'm often trying to speak to him, or be around him. He also seems to be interested in me, and sometimes talks to me, or brings some snack or drink. He looks like a pretty good man."
    new " 어쩜 저렇게 닮았을까? 외모도, 말투도, 성격도, 심지어 소주를 못 마시는 것까지 너무 닮았다. 그를 볼 때마다 윤우가 떠올라 마음이 아프다. 그래서인지 자꾸 그에게 신경이 쓰인다. 괜히 말 한마디라도 더하게 되고 주변을 서성이게 된다. 그도 나를 의식하고 있는지 가끔 일부러 내게 와서 말을 걸기도 하고 간식이나 음료 같은 것들도 챙겨준다. 좋은 사람 같다."
    old " His wife visited the hospital. Though the Director and my lover prefer a simple and plain style, she dressed up too much, with luxurious dress and accessories. She looked just full of vanity. When I saw she's coquetting with him arm in arm, she really looked like an old fox. I can't imagine she's the Director's sister, and my lover's wife. She really makes me feel sick.\n\n When he and I were left alone because of night duty. he talked to me as if he was just working, because he knew we were being recorded on a CCTV.\n\n After finishing work, I got out of the hospital, and sat alone on the bench in front of the building. After a while, all lights were off in the hospital except one—Light from his office, coming through the blinds."
    new " 그의 아내가 병원을 방문했다. 검소한 원장님이나 그와는 달리 굉장히 비싸 보이는 옷과 고급스러운 장신구로 치장한 그녀의 모습은 허영심으로 가득해 보였다. 그의 팔짱을 끼고 아양 떠는걸 보니 늙은 여우가 딱 어울린다. 저런 여자가 원장님의 동생이고 그의 아내라니, 기가 차고 불쾌하다.\n\n 당직인 나와 그만이 남은 시간, 그는 CCTV를 의식해 업무를 보는 척 프론트로 와 나에게 말을 건다.\n\n 퇴근 시간, 그에게 인사하고 건물을 나와 병원 앞 쉼터 의자에 앉았다. 잠시 후 병원의 모든 불이 꺼지고, 곧 그의 진료실에 켜진 불빛이 블라인드를 밝혔다."
    old " The director seemed to be trying hard not to hurt me, controlling his feelings. I understand he would feel betrayed as he has trusted me a lot, but he never swore at me at all, and treated me human to human. And now, I've finally realized what the hell I did. I felt really sorry for his wife, as she has never thought about this, and also felt sorry for the director who has always truly taken care of me. At the request of the Director, I decided to quit the hospital. I also said to him I would definitely break off my affair with the Doctor.\n\n After I packed up my stuff and got out of the hospital, I saw him running after me, but I just came out of the building and got into a taxi. In the running taxi, I just cried and cried. I could never see my colleagues there and the Director anymore…. and also him…. whom I made love with…. goodbye, everyone…. My greed has screwed up everything. Thank you all, and sorry…."
    new " 원장님은 내게 상처를 주지 않으려고 감정을 억누르는 기색이 역력했다. 그동안 나를 무척 예뻐해 주셨기에 배신감도 클 텐데, 끝까지 내게 욕 한마디 안 하시고 사람으로 대해주셨다. 나는 오늘에서야, 내가 그동안 무슨 일을 저지른 건지 알았다. 아무것도 모르고 있는 그의 아내에게 미안했고, 지금까지 나를 보살펴준 원장님께 죄송한 생각만 들었다. 나는 원장님의 말대로 병원을 그만두기로 했다. 그와도 깨끗이 정리하겠다고 말했다.\n\n 정든 병원에서 짐을 들고 나올 때 달려나오는 그의 모습이 잠깐 보였지만 망설이지 않고 건물을 나와 택시를 탔다.\n\n 달리는 차 안에서 계속 울었다. 이제 병원 식구들과 원장님을 다시는 볼 수 없을 것이다. 나와 사랑을 나눈 그 사람도…, 이젠 안녕이다…. 내 욕심이 모든 걸 망쳐버렸다. 모두에게 감사했고, 죄송하다…."
    old " Every single day, I cry, sleep, and wake from sleep, remember my good old days, especially with him, and then, cry, and fall asleep again. Beginning with a few days ago, I sometimes burst into laughter, and sometimes, burst into a fit of anger. I feel like I can't breathe well from time to time.\n\n I miss him. I miss him looking at me with a gentle smile. Thinking this makes me weepy, and it becomes hard to breathe. Also at this moment I'm writing this, I'm feeling really suffocated."
    new " 요즘의 나는 매일같이 울다가 잠들고, 일어나면 그와 함께했던 시간을 추억하고, 다시 울다가 잠든다. 며칠 전부터는 갑자기 웃음이 나오기도 하고, 화가 치밀어오르기도 한다. 숨이 잘 안 쉬어지는 것 같은 느낌이 들 때도 있다.\n\n 그가 보고 싶다. 나를 보고 환하게 웃어주던 그의 모습이 그립다. 그럴수록 눈물이 흐르고, 숨을 제대로 쉴 수가 없다. 일기를 쓰고 있는 지금도 갑갑하기만 하다."
    old " Even though I had no interview today, I sat in front of my dressing table to put on makeup. But as soon as I saw my face, I was frightened, as it suddenly looked awful and disgusting. I fell backward, and managed to crawl to the bed. And I trembled and trembled. Then, I called Hye-na and begged her to save me.\n\n Soon, Hye-na came to my home, and I said to her I was probably going crazy, crying loudly in her arms. After I cried for a good while, I told her everything and taking her suggestion, I decided to see a doctor tomorrow. Hye-na is drinking a can of beer now.\n\n When I'm glancing at her, I feel my wrist, wrapped with bandages, is stinging.\n\n Okay, I'll finish today's diary here and go to bed after having some more conversations with Hye-na. Good night."
    new " 오늘은 면접도 없는 날인데 화장하려고 거울 앞에 앉았다가 거울에 비친 내 얼굴이 너무 무서워서 뒤로 넘어지고, 기어서 침대 위로 올라가 베개를 끌어안고 부들부들 떨었다. 울면서 혜나에게 전화를 걸어 살려달라고 애원했다.\n\n 얼마 후 원룸으로 찾아온 혜나를 부둥켜안고 엉엉 울면서 내가 미쳐버린 것 같다고 말했다. 한참을 운 후에 혜나에게 그간 있었던 일들을 말했고 내일 함께 병원에 가기로 했다. 혜나는 침대에 걸터앉아 아무 일 없던 듯이 맥주를 마시고 있다.\n\n 혜나를 보는데 붕대를 맨 손목이 따끔거린다. 일기는 그만 쓰고 혜나랑 좀 더 이야기하고 자야겠다."
    old " Today, I visited a neuropsychiatric clinic, with Hye-na. I was pretty afraid to go there, but as I was with my sister, I could do it. The doctor asked me a number of things, from trivial questions to what is happening to me now and what I don't want to tell others as well.\n\n He also asked whether I have some physical problems, and I told him I hurt myself several times, and especially when I looked at my face yesterday, I was really frightened, as my eyes continuously blinked. The doctor asked me to have a medical checkup. So I filled out the questionnaire and had a blood test as well.\n\n And the result said I had 'anxiety disorder' and 'depressive disorder'. I asked the doctor if I was going to be a mental patient. But he said no.\n\n He just told me my condition and tick disorder would get better soon, if I try hard to improve my life pattern and steadily get counseling."
    new " 오늘은 혜나와 함께 신경정신과를 찾았다. 막상 가려니 무서웠지만, 동생이 옆에 있어 용기를 냈다. 의사는 시시한 질문부터 시작해 나에게 일어나고 있는 일들과 내가 말하고 싶지 않은 것들에 대해 물었다.\n\n 신체적으로 일어난 문제는 없느냐고 묻길래 자해를 몇 번 했고, 어제 거울을 봤는데 내 눈이 계속 깜빡여서 무서웠다고 말했다. 의사가 정밀하게 검사해보자고 해서 설문지도 작성하고 혈액 검사까지 했다.\n\n 불안 장애와 우울 장애로 결과가 나왔다. 내가 정신병자가 된 거냐고 의사에게 물었더니 그건 아니란다.\n\n 현재의 생활을 개선하고 꾸준히 상담받으면서 치료하면 틱장애도 함께 나아질 거라고 의사가 말했다."
    old " Today, I met Eunju. It's been a really long time since I've seen her. She used to be my best friend when we were high school students, but she is not single anymore. She said she's really worried as she hasn't lost any weight in spite of her steady diet since she gave birth to her baby. So I told her that she still looks good. Eunju worried about me saying I'm so bony, and she said to take her fat from her, shaking her potbelly. It was hilarious.\n\n Eunju has become a master of a Japanese fencing school. I think she probably heard about my situation from Hye-na, because she has never asked me about my job or marriage.\n\n She just kept talking about our school days, or her travel. Like other mamas, her voice was louder than it used to be, and also she speaks so fast Anyway, I'm happy she is having a good life.\n\n Ga-yeon, no more negative thinking! Okay?"
    new " 몇 년 만에 은주를 만났다. 고등학생 때 나와 단짝이었던 은주는 이제 아줌마가 다 됐다. 출산 후에 살이 쪄서 다이어트를 하는데 살이 안 빠져 걱정이라고. 내가 통통한 것도 보기 좋다고 말했더니 너는 왜 그리 삐쩍 말랐느냐며 자기 살 좀 가져가라고 배를 잡고 흔드는 모습이 웃겼다.\n\n 은주는 검도장 사범이 됐다고 한다. 혜나에게서 내 얘기를 들었는지 직장이나 결혼 같은 건 물어보지 않고 학창시절 때나 자기 여행 얘기를 많이 했다.\n\n 애 엄마 아니랄까봐 예전에도 컸던 목소리가 더 커지고 말도 빨라진 것 같다. 잘살고 있는 것 같아 내 기분도 좋았다.\n\n 부정적인 생각은 하지 말자!"
    old " These days, I receive mental health treatment, and also try hard to get a job. I didn't want to close my installment savings account, but I did, to have some reserved money for myself and also give some of it to my parents. I can't stop sending money to my parents because I have to make them believe I live well without any problem as always.\n\n However, getting a new job is harder than I expected. Because I worked mostly in restaurants, I have failed several times already, although I had a number of interviews for general office jobs.\n\n Besides, I never wrote my mental health-related matter in the resume, but some interviewers seemed to recognize my problem, as my tick disorder appeared even during the interview.\n\n I'm trying really to keep the steam up, but…. I'm getting tired of living…."
    new " 요즘은 정신과 치료와 구직 활동을 병행하고 있다. 아깝긴 했지만 모아둔 적금을 깨서 부모님께 드릴 용돈과 나를 위해 쓸 돈을 준비했다. 부모님 용돈은 무슨 일이 있어도 계속 보내야 한다. 그래야 내가 문제없이 잘 지내고 있을 거라고 안심하실 거다.\n\n 그런데 새 일자리를 구하는 것이 생각보다 쉽지 않다. 외식업계를 주로 해서 일반 사무직이나 경리직도 알아보고 있는데 매번 면접에서 떨어지고 있다.\n\n 정신과 치료를 받고 있다는 건 이력서에 쓰지 않았는데, 가끔은 면접 중에 틱 증상이 나타나 면접관이 장애가 있느냐고 묻기도 한다.\n\n 힘내자고 스스로 다독이고 있지만…, 여러모로 힘들다…."
    old " I gave up. I gave up finding a new job, meeting people, receiving medical treatment, and everything. All are just useless. What I have now is…. only this tiny space. Where nothing happens unless I stir it.\n\n In spite of heaps of attempts to get a job, what I had was only frustration and discouragement. The hospital where I've received the treatment suggested I transfer to another hospital. Sometimes, the nebulizer which Hye-na presented me to soothe myself didn't work at all.\n\n I feel like my room is a rubbish can, and I'm just rubbish."
    new " 이제 나는 포기했다. 직장을 구하는 일도, 누군가를 만나는 일도, 정신과 치료를 받는 일도. 이 쓸모없는 짓들을 모두 포기했다. 나에게 남은 건 이 작은 공간. 내가 무언가 하지 않으면 아무런 일도 일어나지 않는 이곳뿐이다.\n\n 구직활동을 계속할수록 돌아오는 것은 좌절뿐이었고, 치료하러 다니던 병원에서는 더 해줄 수 있는 것이 없다며 병원을 옮겨보라고 했다. 호흡이 어려울 때 심신 안정에 도움이 될지도 모른다며 혜나가 선물해준 네뷸라이저도 가끔은 아무런 소용이 없다.\n\n 내 방은 쓰레기통, 나는 쓰레기다."
    old " Go die, you bitch. How dare you want to live on! You're such a hooker who tried to take another's husband! Why are you still alive? You know well what a useless thing you are. You're just a whore. Now are you going to cling to him, instead of your previous lover? You don't deserve to live anymore. Go away. Go away and die.\n\n Someone keeps whispering in my ears. Okay. Alright. Just stop it, please. Please. I'm sorry. I go and die now. So, please shut up!"
    new " 죽어, 이 쓸모없는 년아. 남에 남편을 뺏으려 한 주제에 잘 살 수 있을 것 같았니? 왜 살아 있어? 이 아무짝에도 쓸모없는 갈보년아. 꿩대신닭이라고 이제 그에게 들러붙으려는 거야? 너는 살아 있을 자격도 없는 년이야. 죽어, 죽어 없어져 버리라고.\n\n 누군가 내 귀에 대고 계속 말하고 있다. 알았어, 그만해. 나도 알아. 그러니까 제발 그만 좀 해. 그래, 미안해. 내가 죽을게. 죽으면 되잖아. 제발, 제발 그만 하라고!"
    old 'STORY'
    new '이야기 연계성'
    old 'SIZE'
    new '무대 크기'
    old 'TIME'
    new '제한시간'
    old 'TRICK'
    new '속임수'
    old 'Help….'
    new '도와줘….'
    old 'Hmm….'
    new '흠….'
    old 'My bed.'
    new '나의 침대.'
    old 'There is no plastic bag.'
    new '거기에는 비닐 봉지가 없어.'
    old 'There is no jam on the bookshelf.{w=.3} And toilet…?'
    new '책장에는 잼이 없다.{w=.3} 설마 화장실에…?'
    old 'My room is very small.'
    new '내 방은 굉장히 작다.'
    old "It seems to be around…."
    new "가까이에 있어…."
    old "It seems to be around.{w=.3} But it's not in the refrigerator."
    new "가까이에 있어.{w=.3} 하지만 냉장고는 아냐."
    old 'I stare at my reflection in the mirror.{w=.3} Are you happy now?'
    new '거울에 비친 내 모습을 응시한다.{w=.3} 너는 행복하니?'
    old "It's near."
    new "가까워졌어."
    old 'The water coming out of well.'
    new '물은 잘 나오고 있다.'
    old "It's me."
    new "그건 나야."
    old 'Please….'
    new '제발….'
    old 'Somebody…, help me….'
    new '누가 제발…, 나를 구해줘….'
    old 'Not there!'
    new '거기가 아냐!'
    old "It's a washing machine,{w=.3} and a gas stove."
    new "세탁기와 가스 레인지다."
    old 'Open it!'
    new '열어보는 거야!'
    old "I don't have any kitchen tools."
    new "주방도구는 하나도 가지고 있지 않아."
    old 'Take out it!'
    new '그걸 꺼내!'
    old "It's a cat plastic bag."
    new "고양이 모양의 비닐 봉지다."
    old "Mouse"
    new "다람쥐"
    old "Keyboard"
    new "글쇠판"
    old "Gamepad"
    new "제어기"
    old "Left Click"
    new "왼쪽 단추"
    old "Advances dialogue and activates the interface."
    new "지문을 진행하고 선택지 또는 단추를 선택합니다."
    old "Right Click"
    new "오른쪽 단추"
    old "Accesses the game menu."
    new "메뉴판을 엽니다."
    old "Mouse Wheel Up\nClick Rollback Side"
    new "바퀴 올리기\n측면 단추"
    old "Rolls back to earlier dialogue."
    new "이전 지문으로 돌아갈 수 있습니다."
    old "Mouse Wheel Down"
    new "바퀴 내리기"
    old "Rolls forward to later dialogue."
    new "이후 지문을 읽을 수 있습니다."
    old "Middle Click"
    new "바퀴 단추 누르기"
    old "Hides the user interface."
    new "지문 창이나 기타 UI를 숨깁니다."
    old "Enter"
    new "넣음쇠\n(Enter)"
    old "Space"
    new "사이띄개\n(Space)"
    old "Advances dialogue without selecting choices."
    new "지문을 진행하지만 선택지를 선택하지는 않습니다."
    old "Arrow Keys"
    new "방향쇠"
    old "Navigate the interface."
    new "선택지, 단추를 고릅니다."
    old "Ctrl"
    new "제어쇠\n(Ctrl)"
    old "Skips dialogue while held down."
    new "단추를 누르고 있는 동안 넘기기를 활성화합니다."
    old "Tab"
    new "징검쇠\n(Tab)"
    old "Toggles dialogue skipping."
    new "넘기기를 시작하거나 중단합니다."
    old "Page Up"
    new "앞쪽쇠\n(PageUp)"
    old "Page Down"
    new "뒤쪽쇠\n(PageDown)"
    old "Escape"
    new "나옴쇠\n(Escape)"
    old "Takes a screenshot."
    new "갈무리를 저장합니다."
    old "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    new "{a=https://www.renpy.org/l/voicing}음성지원{/a}을 시작하거나 중단합니다."
    old "Start"
    new "시작(Start)"
    old "Back"
    new "뒤로\n(Back)"
    old "D-Pad, Sticks"
    new "방향판, 막대"
    old "A/Bottom Button"
    new "A\n(아래쪽 단추)"
    old "Left Bumper"
    new "왼쪽 완충기\n(Bumper)"
    old "Right Bumper"
    new "오른쪽 완충기\n(Bumper)"
    old "Calibrate"
    new "보정"
