translate Chinese strings:
    old "{#weekday}Monday"
    new "{#weekday}星期一"
    old "{#weekday}Tuesday"
    new "{#weekday}星期二"
    old "{#weekday}Wednesday"
    new "{#weekday}星期三"
    old "{#weekday}Thursday"
    new "{#weekday}星期四"
    old "{#weekday}Friday"
    new "{#weekday}星期五"
    old "{#weekday}Saturday"
    new "{#weekday}星期六"
    old "{#weekday}Sunday"
    new "{#weekday}星期日"
    old "{#weekday_short}Mon"
    new "{#weekday_short}周一"
    old "{#weekday_short}Tue"
    new "{#weekday_short}周二"
    old "{#weekday_short}Wed"
    new "{#weekday_short}周三"
    old "{#weekday_short}Thu"
    new "{#weekday_short}周四"
    old "{#weekday_short}Fri"
    new "{#weekday_short}周五"
    old "{#weekday_short}Sat"
    new "{#weekday_short}周六"
    old "{#weekday_short}Sun"
    new "{#weekday_short}周日"
    old "{#month}January"
    new "{#month}1月"
    old "{#month}February"
    new "{#month}2月"
    old "{#month}March"
    new "{#month}3月"
    old "{#month}April"
    new "{#month}4月"
    old "{#month}May"
    new "{#month}5月"
    old "{#month}June"
    new "{#month}6月"
    old "{#month}July"
    new "{#month}7月"
    old "{#month}August"
    new "{#month}8月"
    old "{#month}September"
    new "{#month}9月"
    old "{#month}October"
    new "{#month}10月"
    old "{#month}November"
    new "{#month}11月"
    old "{#month}December"
    new "{#month}12月"
    old "{#month_short}Jan"
    new "{#month_short}1月"
    old "{#month_short}Feb"
    new "{#month_short}2月"
    old "{#month_short}Mar"
    new "{#month_short}3月"
    old "{#month_short}Apr"
    new "{#month_short}4月"
    old "{#month_short}May"
    new "{#month_short}5月"
    old "{#month_short}Jun"
    new "{#month_short}6月"
    old "{#month_short}Jul"
    new "{#month_short}7月"
    old "{#month_short}Aug"
    new "{#month_short}8月"
    old "{#month_short}Sep"
    new "{#month_short}9月"
    old "{#month_short}Oct"
    new "{#month_short}10月"
    old "{#month_short}Nov"
    new "{#month_short}11月"
    old "{#month_short}Dec"
    new "{#month_short}12月"
    old "%b %d, %H:%M"
    new "%m月%d日, %H:%M"
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new "{#file_time}%Y年 %B %d日, %A, %H:%M"
    old "Quick save complete."
    new "快速存档。"
    old "Image [index] of [count] locked."
    new "[count]个图片中的第[index]个图片被锁定。"
    old "Graphics Acceleration"
    new "图形加速"
    old "Automatically Choose"
    new "自动选择"
    old "Force Angle/DirectX Renderer"
    new "强制 Angle/DirectX 渲染"
    old "Force OpenGL Renderer"
    new "强制 OpenGL 渲染"
    old "Force Software Renderer"
    new "强制软件渲染"
    old "Changes will take effect the next time this program is run."
    new "更改将会在下次启动程序时生效。"
    old "Performance Warning"
    new "性能影响警告"
    old "This computer is using software rendering."
    new "该计算机正在使用软件渲染。"
    old "This computer is not using shaders."
    new "该计算机没有使用着色器"
    old "This computer is displaying graphics slowly."
    new "该计算机图形显示缓慢。"
    old "This computer has a problem displaying graphics: [problem]."
    new "该计算机图形显示出错：[problem]。"
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display. Updating DirectX could fix this problem."
    new "目前的图形驱动程序版本可能过旧或未正确运行。这样会导致图形显示缓慢或者错误。升级 DirectX 可能会解决该问题。"
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new "目前图形驱动程序版本可能过旧或未正确运行。这样会导致图形显示缓慢或者错误。"
    old "Update DirectX"
    new "更新 DirectX"
    old "Continue, Show this warning again"
    new "继续，下次再显示该警告"
    old "Continue, Don't show warning again"
    new "继续，不再显示该警告"
    old "Updating DirectX."
    new "正在更新 DirectX。"
    old "DirectX web setup has been started. It may start minimized in the taskbar. Please follow the prompts to install DirectX."
    new "DirectX 在线安装已启动，它将会最小化至任务栏。请按照说明安装 DirectX。"
    old "{b}Note:{/b} Microsoft's DirectX web setup program will, by default, install the Bing toolbar. If you do not want this toolbar, uncheck the appropriate box."
    new "{b}警告:{/b} Microsoft's DirectX 在线安装程序会默认安装 Bing 浏览器工具栏。如果您不需要安装这个工具栏，请取消勾选对应选项。"
    old "When setup finishes, please click below to restart this program."
    new "当安装完成后请点选下方来重新启动应用程序。"
    old "Restart"
    new "重新启动"
    old "Saved screenshot as %s."
    new "储存屏幕截图为 %s。"
    old "Are you sure?"
    new "是否确认？"
    old "Are you sure you want to delete this save?"
    new "您确定您要删掉这份存档吗？"
    old "Are you sure you want to overwrite your save?"
    new "您确定您要覆盖存档？"
    old "The next step is an important scene. Do you want to save here?"
    new "下面将发生重要的场面。要在这里保存吗？"
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new "载入将会失去所有未储存的进度。\n您确定您要这么做吗？"
    old "Are you sure you want to quit?"
    new "您确定您要退出吗？"
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new "您确定您想回到标题画面吗？\n未保存的进度将会丢失。"
    old "Are you sure you want to skip to unseen dialogue or the next choice?"
    new "是否确定跳过未读文本与下个选项？"
    old "Are you sure you want to end the replay?"
    new "您确定要结束回放吗？"
    old "Skip Mode"
    new "快进"
    old "Fast Skip Mode"
    new "高速快进"
    old "An exception has occurred."
    new "发生一个异常状况。"
    old "Rollback"
    new "回滚一行"
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new "尝试回滚到先前的状态，使您可以存盘或者选择不同选项。"
    old "Ignore"
    new "忽略错误"
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new "忽略异常，让您可以继续。但这通常会带来更多的问题。"
    old "Reload"
    new "重新加载"
    old "Reloads the game from disk, saving and restoring game state if possible."
    new "从硬盘重载游戏，请您储存游戏状态。"
    old "Open Traceback"
    new "打开日志"
    old "Opens the traceback.txt file in a text editor."
    new "在文本编辑器中打开日志（traceback.txt）。"
    old "Quits the game."
    new "离开游戏。"
    old "Parsing the script failed."
    new "解析脚本失败。"
    old "Open Parse Errors"
    new "开启解析错误"
    old "Opens the errors.txt file in a text editor."
    new "在文本编辑器中打开解析错误档案（errors.txt）。"
    old "Self-voicing enabled. Press 'v' to disable."
    new "自动朗读已开启。按 V 来关闭。"
    old "Self-voicing disabled."
    new "自动朗读已关闭。"