translate Chinese python:
    gui.main_font = "gui/fonts/ShuTiFangZhuoXiaoFengXingCaoTi.ttf"
    gui.text_font = "gui/fonts/DroidSansFallback.ttf"
    gui.name_text_font = "gui/fonts/DroidSansFallback.ttf"
    gui.interface_text_font = "gui/fonts/DroidSansFallback.ttf"
    gui.button_text_font = "gui/fonts/DroidSansFallback.ttf"
    config.name = "失望失业者"
    config.window_title = u"失望失业者"
    if renpy.variant("small"):
        config.translations["{font=[gui.fontawesome]}{/font} Basic Settings"] = u"{font=[gui.fontawesome]}{/font} 基本设置"
        config.translations["{font=[gui.fontawesome]}{/font} Seen Text"] = u"{font=[gui.fontawesome]}{/font} 看过"
        config.translations["{font=[gui.fontawesome]}{/font} Mute All"] = u"{font=[gui.fontawesome]}{/font} 声音关"
        config.translations["{font=[gui.fontawesome]}{/font} Authors"] = u"{font=[gui.fontawesome]}{/font} 版权所有者"
        config.translations['ACOC, Aiman Sharul, Axel Mertes, Bgame, Brandon Tanimoto, Brian Connors, BRISAK Kim Doohyeon, cheif.choi, Choi Irang, Choi Jihye, cloture, Danielle Bell, Edward N Puckering, Gary King, Gwak Jaeryeol, Han Ihyeong, Hoe Namyoon, Hong Eunki, Hwang Daehoon, Hyojoon, James Emmerson, Jeong Dongwon, Jeong Wookjin, Jeong Yoonsoo, Jianmin Zhang,\nKarina Schulze, Keira Val\'Azr, Kim Hanseol, Kim Hyeoncheol, Kim Jaeseong, Kim Jeongwoong, Kim Myeongwook,\nLee Changki, Lee Eunji, Lee Gunhae, Lee Hyejin, Lee Jaewi, Light Twins, Lim Jisoo, Maddy Wootton,\nMarshall Proudfoot, Mirumu, Mojaeng, Oh Hyeonjun, Park Hyeonjun, Park JoonKoo, Rewind, Sander Tieleman, srwss, Sung Chanaul, YottaCho, Zerial.net'] = u'ACOC, Aiman Sharul, Axel Mertes, Bgame,\nBrandon Tanimoto, Brian Connors,\nBRISAK Kim Doohyeon, cheif.choi, Choi Irang,\nChoi Jihye, cloture, Danielle Bell,\nEdward N Puckering, Gary King, Gwak Jaeryeol,\nHan Ihyeong, Hoe Namyoon, Hong Eunki,\nHwang Daehoon, Hyojoon, James Emmerson,\nJeong Dongwon, Jeong Wookjin, Jeong Yoonsoo,\nJianmin Zhang, Karina Schulze, Keira Val\'Azr,\nKim Hanseol, Kim Hyeoncheol, Kim Jaeseong,\nKim Jeongwoong, Kim Myeongwook,\nLee Changki, Lee Eunji, Lee Gunhae, Lee Hyejin,\nLee Jaewi, Light Twins, Lim Jisoo, Maddy Wootton,\nMarshall Proudfoot, Mirumu, Mojaeng,\nOh Hyeonjun, Park Hyeonjun, Park JoonKoo,\nRewind, Sander Tieleman, srwss, Sung Chanaul,\nYottaCho, Zerial.net'
        config.translations['Caz Woolley, Game Dev Robot, Gamsadev, Indie GameDev Bot, Indie Game Lover, Indie Games Devel, IndieVideoGames, Joachim Dimitri Jensen, Kim Kyeongtae, Kim Younghwan, Kurt Simon, Linda Lee King, Peter Christiansen, Sakimichi, Sebastian Haba, Spero Mcgee, The Indie Sloth, Vrachos, Xin Liu, Yu Shinhyeon'] = u'Caz Woolley, Game Dev Robot, Gamsadev,\nIndie GameDev Bot, Indie Game Lover,\nIndie Games Devel, IndieVideoGames,\nJoachim Dimitri Jensen, Kim Kyeongtae,\nKim Younghwan, Kurt Simon, Linda Lee King,\nPeter Christiansen, Sakimichi, Sebastian Haba,\nSpero Mcgee, The Indie Sloth, Vrachos, Xin Liu,\nYu Shinhyeon'
        config.translations['Christopher Rice, George Winston, Kim Sooyoung, Lee Illseong, Pixabay, Shin Haechul, So Reyeon, Tom Rothamel,\nValve Corporation'] = u"Christopher Rice, George Winston, Kim Sooyoung, Lee Illseong, Pixabay, Shin Haechul, So Reyeon,\nTom Rothamel, Valve Corporation"
    build_date = "2019年01月01日"
    copyright = "(c)2019 YGGDRASIL STUDIO"
    gui.attention = "警     告"
    gui.language = "此故事禁止未成年人观看。不建议儿童(青少年)、老弱者或者孕妇、身心较弱者观看。\n这个节目包含以下内容。\n\n性、菸酒、不當言語"
    gui.start = "开始游戏"
    gui.bookmarks = "的书签"
    gui.load = "载入游戏"
    gui.archives = "的档案室"
    gui.arcq = "的档案室"
    gui.dlc = "{font=gui/fonts/YiSunShinBold.ttf}DLC&MOD{/font}"
    gui.conf = "环境设定"
    gui.blind_char  = "人物"
    gui.blind_con  = "解说集"
    gui.blind_diary  = "佳妍的日记"
    gui.conq = "环境设定"
    gui.play = "播放"
    gui.stop = "停止"
    gui.skip = "快进模式"
    gui.history = "脚本"
    gui.hisq = "脚本"
    gui.hide = "隐藏"
    gui.save = "储存游戏"
    gui.quit = "退出游戏"
    gui.credits = "主创者"
    gui.unlocked = "解锁"
    gui.heal = "治疗"
    gui.judge = "旁观"
    gui.left = "回家"
    gui.right = "未走过的路"
    gui.choice = "可在这里进行选择。听完说明后，请做出选择。"
    gui.teddy = "请寻找玩具熊。"
    gui.part01 = "慧娜的访问"
    gui.part02 = "佳妍的独白"
    gui.part03 = "和允宇的见面"
    gui.part04 = "允宇和新村街头"
    gui.part05 = "和允宇的午餐"
    gui.part06 = "佳妍的独白"
    gui.part07 = "和允宇的说笑"
    gui.part08 = "允宇说出的慧娜的故事"
    gui.part09 = "慧娜的处境"
    gui.part10 = "扭曲"
    gui.part11 = "佳妍的独白"
    gui.part12 = "医院的故事"
    gui.part13 = "生活讨论"
    gui.part14 = "佳妍的现实了解"
    gui.part15 = "自作自受"
    gui.part16 = "入睡于安息"
    gui.part17 = "疯狂"
    gui.part18 = "允宇的角度"
    gui.part19 = "佳妍的角度"
    gui.part20 = "佳妍和允宇"
    gui.part21 = "生命之桥"
    gui.part22 = "世界的尽头"
    gui.part23 = "事件发生"
    gui.part24 = "结局"
    gui.part25 = "花朝月夕"
    gui.the_end = "结束"
    gui.game_over = "游戏结束"
    gui.bgm01 = "Track 01。 Pandemic"
    gui.bgm02 = "Track 02。 Sigh day"
    gui.bgm03 = "Track 03。 Mare tranquillitatis"
    gui.bgm04 = "Track 04。 CCCanon"
    gui.bgm05 = "Track 05。 Let's game"
    gui.bgm06 = "Track 06。 Peace"
    gui.bgm07 = "Track 07。 Unknown mist"
    gui.bgm08 = "Track 08。 Lush garden"
    gui.bgm09 = "Track 09。 Jormungandr"
    gui.bgm10 = "Track 10。 Nyx"
    gui.bgm11 = "Track 11。 Summit showdown"
    gui.bgm12 = "Track 12。 Love song"
    gui.bgm13 = "Track 13。 Sea of nectar"
    gui.about = "Discouraged Workers (c)2019 YGGDRASIL STUDIO Co, Pte。拥有所有权利。失望失业者的著作权归YGGDRASIL STUDIO所有。所有的著作/商标都属于所有者的财产。请禁止传播本公司的程序(program)及利用本公司程序(program)进行变更的程序(program)文件。最终用户的使用权合同请参考licenses目录的EULA.txt文件或{a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/blob/gh-pages/EULA.txt}请访问此处{/a}"
    code.license = "可根据GNU宽通用公共许可证v3.0条款使用失望失业者的源代码(source code)。源代码(source code)下载地址{a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/tree/source-codes}请访问此处。{/a}"
    font.license = "在包括SIL开源字体授权在内的多种使用权下，本作品含有免费字体软件。使用的项目(project)目录和下载地址请参考licenses目录的fonts-LICENSE.txt文件或{a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}请访问此处。{/a}"
    renpy.license = "Ren'Py包含了由数个许可证授权的免费软件，包括 MIT 许可证和 GNU 宽通用公共许可证。完整软件列表及源代码链接，{a=https://www.renpy.org/l/license}请访问此处。{/a}"
    valve.license = "(c)2019 Valve Corporation。Steam 和 Steam 徽标均为 Valve Corporation 在美国和/或其他国家（地区）的商标和/或注册商标。\n\n(c)2019 Valve Corporation。Steamworks 和 Steamworks 徽标均为 Valve Corporation 在美国和/或其他国家（地区）的商标和/或注册商标。"
    xbox.license = "本作品使用了Xbox 360控制器/按键图片。下载地址{a=http://xbox.create.msdn.com/en-us/education/catalog/utility/controller_buttons}请访问此处。{/a}"
    cc.license = "本作品使用了适用创作共用授权条款的各种资产。使用的资产目录和下载地址请参考licenses目录的assets-LICENSE.txt文件或{a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}请访问此处。{/a}"
