translate Chinese strings:
    old "Load"
    new "载入游戏"
    old "Left arrow key: Yes, Right arrow key: No."
    new "左: 是， 右: 否。"
    old "Left arrow key: Previous, Right arrow key: Next."
    new "左: 上一页， 右: 下一页。"
    old "Left arrow key: Healing, Right arrow key: Onlooking"
    new "左: 治疗, 右: 旁观"
    old "Left arrow key: Back home, Right arrow key: Road not taken"
    new "左: 回家, 右: 未走过的路"
    old "You can make a choice here. Listen to the following explanation and choose what you want."
    new "可在这里进行选择。听完说明后，请做出选择。"
    old "©2020 YGGDRASIL STUDIO"
    new "(c)2020 YGGDRASIL STUDIO"
    old "Jun 18, 2020 - V[config.version]"
    new "2020年06月18日 - V[config.version]"
    old "{size=86}Start Reading{/size}"
    new "开始游戏"
    old "{size=86}Bookmarks{/size}"
    new "的书签"
    old "{size=86}Load{/size}"
    new "载入游戏"
    old "{size=86}Archives{/size}"
    new "的档案室"
    old "{size=86}DLC&MOD{/size}"
    new "{font=gui/fonts/YiSunShinBold.ttf}DLC&MOD{/font}"
    old "{size=86}Configuration{/size}"
    new "环境设定"
    old "{size=86}Characters{/size}"
    new "人物"
    old "{size=86}Concept{/size}"
    new "解说集"
    old "{size=86}Diary{/size}"
    new "佳妍的日记"
    old "{size=86}Quit{/size}"
    new "退出游戏"
    old '{size=[gui.quick_button_text_size]}Config{/size}'
    new '{size=[gui.quick_button_text_size]}环境设定{/size}'
    old '{size=[gui.quick_button_text_size]}Play{/size}'
    new '{size=[gui.quick_button_text_size]}播放{/size}'
    old "{font=[gui.fontawesome]}{/font} Play"
    new "{font=[gui.fontawesome]}{/font} 播放"
    old '{size=[gui.quick_button_text_size]}Skip{/size}'
    new '{size=[gui.quick_button_text_size]}快进模式{/size}'
    old "{font=[gui.fontawesome]}{/font} Archives"
    new "{font=[gui.fontawesome]}{/font} 的档案室"
    old '{size=[gui.quick_button_text_size]}Archives{/size}'
    new '{size=[gui.quick_button_text_size]}的档案室{/size}'
    old "{font=[gui.fontawesome]}{/font} History"
    new "{font=[gui.fontawesome]}{/font} 脚本"
    old '{size=[gui.quick_button_text_size]}History{/size}'
    new '{size=[gui.quick_button_text_size]}脚本{/size}'
    old '{size=[gui.quick_button_text_size]}Hide{/size}'
    new '{size=[gui.quick_button_text_size]}隐藏{/size}'
    old '{size=[gui.quick_button_text_size]}Save{/size}'
    new '{size=[gui.quick_button_text_size]}储存游戏{/size}'
    old "{font=[gui.fontawesome]}{/font} Credits"
    new "{font=[gui.fontawesome]}{/font} 主创者"
    old "{font=[gui.fontawesome]}{/font} Unlocked"
    new "{font=[gui.fontawesome]}{/font} 解锁"
    old '{size=[gui.interface_text_size]}Healing{/size}'
    new '{size=[gui.interface_text_size]}治疗{/size}'
    old '{size=[gui.interface_text_size]}Onlooking{/size}'
    new '{size=[gui.interface_text_size]}旁观{/size}'
    old '{size=[gui.interface_text_size]}Back home{/size}'
    new '{size=[gui.interface_text_size]}回家{/size}'
    old '{size=[gui.interface_text_size]}Road not taken{/size}'
    new '{size=[gui.interface_text_size]}未走过的路{/size}'
    old "{image=gui/controllers/[persistent.controllers]/grip_r.webp} {size=86}Start Reading{/size}"
    new "{image=gui/controllers/[persistent.controllers]/grip_r.webp} 开始游戏"
    old "{image=gui/controllers/[persistent.controllers]/guide.webp} {size=86}Start Reading{/size}"
    new "{image=gui/controllers/[persistent.controllers]/guide.webp} 开始游戏"
    old "{image=gui/controllers/[persistent.controllers]/shoulder_r.webp} {size=86}Load{/size}"
    new "{image=gui/controllers/[persistent.controllers]/shoulder_r.webp} 载入游戏"
    old "{image=gui/controllers/[persistent.controllers]/button_start.webp} {size=86}Load{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_start.webp} 载入游戏"
    old "{image=gui/controllers/[persistent.controllers]/shoulder_r.webp} {size=86}Bookmarks{/size}"
    new "{image=gui/controllers/[persistent.controllers]/shoulder_r.webp} 的书签"
    old "{image=gui/controllers/[persistent.controllers]/button_start.webp} {size=86}Bookmarks{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_start.webp} 的书签"
    old "{image=gui/controllers/[persistent.controllers]/button_b.webp} {size=86}Archives{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_b.webp} 的档案室"
    old "{image=gui/controllers/[persistent.controllers]/button_b.webp} {size=86}Characters{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_b.webp} 人物"
    old "{image=gui/controllers/[persistent.controllers]/button_x.webp} {size=86}Concept{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_x.webp} 解说集"
    old "{image=gui/controllers/[persistent.controllers]/button_y.webp} {size=86}Diary{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_y.webp} 佳妍的日记"
    old "{image=gui/controllers/[persistent.controllers]/button_x.webp} {size=86}DLC&MOD{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_x.webp} {font=gui/fonts/YiSunShinBold.ttf}DLC&MOD{/font}"
    old "{image=gui/controllers/[persistent.controllers]/button_y.webp} {size=86}Configuration{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_y.webp} 环境设定"
    old "{image=gui/controllers/[persistent.controllers]/shoulder_l.webp} {size=86}Quit{/size}"
    new "{image=gui/controllers/[persistent.controllers]/shoulder_l.webp} 退出游戏"
    old "{image=gui/controllers/[persistent.controllers]/button_select.webp} {size=86}Quit{/size}"
    new "{image=gui/controllers/[persistent.controllers]/button_select.webp} 退出游戏"
    old "Track 1. Pandemic"
    new "Track 01。 Pandemic"
    old "Track 2. Sigh day"
    new "Track 02。 Sigh day"
    old "Track 3. Mare tranquillitatis"
    new "Track 03。 Mare tranquillitatis"
    old "Track 4. CCCanon"
    new "Track 04。 CCCanon"
    old "Track 5. Let's game"
    new "Track 05。 Let's game"
    old "Track 6. Peace"
    new "Track 06。 Peace"
    old "Track 7. Unknown mist"
    new "Track 07。 Unknown mist"
    old "Track 8. Lush garden"
    new "Track 08。 Lush garden"
    old "Track 9. Jormungandr"
    new "Track 09。 Jormungandr"
    old "Track 10. Nyx"
    new "Track 10。 Nyx"
    old "Track 11. Summit showdown"
    new "Track 11。 Summit showdown"
    old "Track 12. Love song"
    new "Track 12。 Love song"
    old "Track 13. Sea of nectar"
    new "Track 13。 Sea of nectar"
    old "Track 3. Mare tranquillitatis\nTrack 7. Unknown mist"
    new "Track 3。 Mare tranquillitatis\nTrack 7。 Unknown mist"
    old "Track 8. Lush garden\nTrack 9. Jormungandr"
    new "Track 8。 Lush garden\nTrack 9。 Jormungandr"
    old "Credits"
    new "主创者"
    old "Discouraged Workers ©2020 YGGDRASIL STUDIO Co, Pte. All Rights Reserved. All literary works/trademarks are property of their respective owners. Do not distribute our program or any alterations of our program files. For the End User License Agreement, please view the EULA.txt file in the licenses directory, or visit {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/blob/gh-pages/EULA.txt}here{/a}.\n\nThe source code of Discouraged Workers is covered by the terms of the GNU Lesser General Public License v3.0. The source code can be found {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/tree/source-codes}here{/a}.\n"
    new "Discouraged Workers (c)2020 YGGDRASIL STUDIO Co, Pte。拥有所有权利。失望失业者的著作权归YGGDRASIL STUDIO所有。所有的著作/商标都属于所有者的财产。请禁止传播本公司的程序(program)及利用本公司程序(program)进行变更的程序(program)文件。最终用户的使用权合同请参考licenses目录的EULA.txt文件或{a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/blob/gh-pages/EULA.txt}请访问此处。{/a}\n\n可根据GNU宽通用公共许可证v3.0条款使用失望失业者的源代码(source code)。源代码(source code)下载地址{a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/tree/source-codes}请访问此处。{/a}\n"
    old "This program contains free font software under a number of licenses, including the SIL Open Font License. A complete list of font software, including links to download can be found {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}here{/a}, or please view the fonts-LICENSE.txt file in the licenses directory.\n\nThis program contains a number of assets that are covered by the terms of the Creative Commons License. For a list of assets, and a location where the original assets can be downloaded from, please view the assets-LICENSE.txt file in the licenses directory or visit {a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}here{/a}.\n"
    new "在包括SIL开源字体授权在内的多种使用权下，本作品含有免费字体软件。使用的项目(project)目录和下载地址请参考licenses目录的fonts-LICENSE.txt文件或{a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}请访问此处。{/a}\n\n本作品使用了适用创作共用授权条款的各种资产。使用的资产目录和下载地址请参考licenses目录的assets-LICENSE.txt文件或{a=https://github.com/YGGDRASIL-STUDIO/Discouraged-Workers/wiki/about#licenses}请访问此处。{/a}\n"
    old "This program contains Xbox 360 Controller/Button images. The asset pack can be found {a=http://xbox.create.msdn.com/en-us/education/catalog/utility/controller_buttons}here{/a}.\n"
    new "本作品使用了Xbox 360控制器/按键图片。下载地址{a=http://xbox.create.msdn.com/en-us/education/catalog/utility/controller_buttons}请访问此处。{/a}\n"
    old "©2020 Valve Corporation. Steam and the Steam logo are trademarks and/or registered trademarks of Valve Corporation in the U.S. and/or other countries.\n\n©2020 Valve Corporation. Steamworks and the Steamworks logo are trademarks and/or registered trademarks of Valve Corporation in the U.S. and/or other countries."
    new "(c)2020 Valve Corporation。Steam 和 Steam 徽标均为 Valve Corporation 在美国和/或其他国家（地区）的商标和/或注册商标。\n\n(c)2020 Valve Corporation。Steamworks 和 Steamworks 徽标均为 Valve Corporation 在美国和/或其他国家（地区）的商标和/或注册商标。"
    old "{font=[gui.fontawesome]}{/font} Basic Settings"
    new "{font=[gui.fontawesome]}{/font} 基本设置"
    old "{font=[gui.fontawesome]}{/font} About"
    new "{font=[gui.fontawesome]}{/font} 信息"
    old "{font=[gui.fontawesome]}{/font} Help"
    new "{font=[gui.fontawesome]}{/font} 帮助文档"
    old "{font=[gui.fontawesome]}{/font} Characters"
    new "{font=[gui.fontawesome]}{/font} 人物"
    old "{font=[gui.fontawesome]}{/font} Concept"
    new "{font=[gui.fontawesome]}{/font} 解说集"
    old "{font=[gui.fontawesome]}{/font} Diary"
    new "{font=[gui.fontawesome]}{/font} 佳妍的日记"
    old "{font=[gui.fontawesome]}{/font} Gallery"
    new "{font=[gui.fontawesome]}{/font} 美术馆"
    old "{font=[gui.fontawesome]}{/font} Music"
    new "{font=[gui.fontawesome]}{/font} 音乐厅"
    old "{font=[gui.fontawesome]}{/font} Replay"
    new "{font=[gui.fontawesome]}{/font} 重播"
    old "{font=[gui.fontawesome]}{/font} Medals"
    new "{font=[gui.fontawesome]}{/font} 奖牌"
    old "{font=[gui.fontawesome]}{/font} Refresh"
    new "{font=[gui.fontawesome]}{/font} 刷新"
    old "{font=[gui.fontawesome]}{/font} Window"
    new "{font=[gui.fontawesome]}{/font} 窗口"
    old "{font=[gui.fontawesome]}{/font} Fullscreen"
    new "{font=[gui.fontawesome]}{/font} 全屏幕"
    old "{font=[gui.fontawesome]}{/font} Save"
    new "{font=[gui.fontawesome]}{/font} 存游戏"
    old "{font=[gui.fontawesome]}{/font} Start Reading"
    new "{font=[gui.fontawesome]}{/font} 开始游戏"
    old "{font=[gui.fontawesome]}{/font} Load"
    new "{font=[gui.fontawesome]}{/font} 载入游戏"
    old "{font=[gui.fontawesome]}{/font} Configuration"
    new "{font=[gui.fontawesome]}{/font} 环境设定"
    old "{font=[gui.fontawesome]}{/font} DLC&MOD"
    new "{font=[gui.fontawesome]}{/font} {font=gui/fonts/YiSunShinBold.ttf}DLC&MOD{/font}"
    old "{font=[gui.fontawesome]}{/font} End Replay"
    new "{font=[gui.fontawesome]}{/font} 退出重播"
    old "{font=[gui.fontawesome]}{/font} Main Menu"
    new "{font=[gui.fontawesome]}{/font} 标题画面"
    old "{font=[gui.fontawesome]}{/font} Quit"
    new "{font=[gui.fontawesome]}{/font} 退出游"
    old "{font=[gui.fontawesome]}{/font} Done"
    new "{font=[gui.fontawesome]}{/font} 确认"
    old "{font=[gui.fontawesome]}{/font} Return"
    new "{font=[gui.fontawesome]}{/font} 返回"
    old "{font=[gui.fontawesome]}{/font} Yes"
    new "{font=[gui.fontawesome]}{/font} 是"
    old "{font=[gui.fontawesome]}{/font} No"
    new "{font=[gui.fontawesome]}{/font} 否"
    old "Created with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\nThis program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license/}here{/a}.\n"
    new "本作品以视觉小说(Visual Novel)引擎{a=https://www.renpy.org/}Ren’Py{/a} [renpy.version_only]制作而成。\n\nRen'Py包含了由数个许可证授权的免费软件，包括 MIT 许可证和 GNU 宽通用公共许可证。完整软件列表及源代码链接，{a=https://www.renpy.org/l/license}请访问此处。{/a}\n"
    old "empty slot"
    new "空存档位"
    old "Page {}"
    new "第{}页"
    old "Automatic saves"
    new "一个自动保存的页面"
    old "Quick saves"
    new "一个快速保存的页面"
    old "{font=[gui.fontawesome]}{/font} Display"
    new "{font=[gui.fontawesome]}{/font} 显示模式"
    old "{font=[gui.fontawesome]}{/font} Rollback Side"
    new "{font=[gui.fontawesome]}{/font} 回滚方向"
    old "{font=[gui.fontawesome]}{/font} Enable"
    new "{font=[gui.fontawesome]}{/font} 活动的"
    old "{font=[gui.fontawesome]}{/font} Disable"
    new "{font=[gui.fontawesome]}{/font} 不活动的"
    old "{font=[gui.fontawesome]}{/font} Left"
    new "{font=[gui.fontawesome]}{/font} 左"
    old "{font=[gui.fontawesome]}{/font} Right"
    new "{font=[gui.fontawesome]}{/font} 右"
    old "{font=[gui.fontawesome]}{/font} Skip"
    new "{font=[gui.fontawesome]}{/font} 快进模式"
    old "{font=[gui.fontawesome]}{/font} Seen Text"
    new "{font=[gui.fontawesome]}{/font} 看过"
    old "{font=[gui.fontawesome]}{/font} After Choices"
    new "{font=[gui.fontawesome]}{/font} 选项后"
    old "{font=[gui.fontawesome]}{/font} Transitions"
    new "{font=[gui.fontawesome]}{/font} 转场特效"
    old "{font=[gui.fontawesome]}{/font} Text Speed"
    new "{font=[gui.fontawesome]}{/font} 文字显示速度"
    old "{font=[gui.fontawesome]}{/font} Auto-Forward Time"
    new "{font=[gui.fontawesome]}{/font} 自动模式等待时间"
    old "{font=[gui.fontawesome]}{/font} Music Volume"
    new "{font=[gui.fontawesome]}{/font} 音乐音量"
    old "{font=[gui.fontawesome]}{/font} Sound Volume"
    new "{font=[gui.fontawesome]}{/font} 音效音量"
    old "{font=[gui.fontawesome]}{/font} Test"
    new "{font=[gui.fontawesome]}{/font} 测试"
    old "{font=[gui.fontawesome]}{/font} Voice Volume"
    new "{font=[gui.fontawesome]}{/font} 语音音量"
    old "{font=[gui.fontawesome]}{/font} Mute All"
    new "{font=[gui.fontawesome]}{/font} 声音关"
    old "The dialogue history is empty."
    new "对话历史是空的。"
    old "{font=[gui.fontawesome]}{/font} Total"
    new "{font=[gui.fontawesome]}{/font} 总"
    old "{font=[gui.fontawesome]}{/font} Characters +2"
    new "{font=[gui.fontawesome]}{/font} 人物 +2"
    old "{font=[gui.fontawesome]}{/font} Music +1"
    new "{font=[gui.fontawesome]}{/font} 音乐厅 +1"
    old "{font=[gui.fontawesome]}{/font} Replay +1"
    new "{font=[gui.fontawesome]}{/font} 重播 +1"
    old "{font=[gui.fontawesome]}{/font} Replay +3"
    new "{font=[gui.fontawesome]}{/font} 重播 +3"
    old "{font=[gui.fontawesome]}{/font} Characters +1"
    new "{font=[gui.fontawesome]}{/font} 人物 +1"
    old "{font=[gui.fontawesome]}{/font} Concept +1"
    new "{font=[gui.fontawesome]}{/font} 解说集 +1"
    old "{font=[gui.fontawesome]}{/font} Gallery +3"
    new "{font=[gui.fontawesome]}{/font} 美术馆 +3"
    old "{font=[gui.fontawesome]}{/font} Gallery +2"
    new "{font=[gui.fontawesome]}{/font} 美术馆 +2"
    old "{font=[gui.fontawesome]}{/font} Music +2"
    new "{font=[gui.fontawesome]}{/font} 音乐厅 +2"
    old "{font=[gui.fontawesome]}{/font} Gallery +1"
    new "{font=[gui.fontawesome]}{/font} 美术馆 +1"
    old "{font=[gui.fontawesome]}{/font} Gallery +5"
    new "{font=[gui.fontawesome]}{/font} 美术馆 +5"
    old "{font=[gui.fontawesome]}{/font} Concept +2"
    new "{font=[gui.fontawesome]}{/font} 解说集 +2"
    old "{font=[gui.fontawesome]}{/font} Diary +15"
    new "{font=[gui.fontawesome]}{/font} 佳妍的日记 +15"
    old "{font=[gui.fontawesome]}{/font} Diary +1"
    new "{font=[gui.fontawesome]}{/font} 佳妍的日记 +1"
    old "Back to the bridge!"
    new "请返回到生命之桥！"
    old "Extras"
    new "的额外"
    old "{font=[gui.fontawesome]}{/font} Open"
    new "{font=[gui.fontawesome]}{/font} 开"
    old "{font=[gui.fontawesome]}{/font} Gift"
    new "{font=[gui.fontawesome]}{/font} 礼品"
    old "{font=[gui.fontawesome]}{/font} Delete"
    new "{font=[gui.fontawesome]}{/font} 删"
    old "{font=[gui.fontawesome]}{/font} Install"
    new "{font=[gui.fontawesome]}{/font} 安装"
    old "{font=[gui.fontawesome]}{/font} Add to cart"
    new "{font=[gui.fontawesome]}{/font} 添加到购物车"
    old "{font=[gui.fontawesome]}{/font} Start"
    new "{font=[gui.fontawesome]}{/font} 开始游戏"
    old "Original Sound Track"
    new "原声大碟"
    old "{font=[gui.fontawesome]}{/font} Manual"
    new "{font=[gui.fontawesome]}{/font} 手册"
    old "Digital Art Book"
    new "数字艺术书"
    old "{font=[gui.fontawesome]}{/font} View"
    new "{font=[gui.fontawesome]}{/font} 视图"
    old "Digital Concept Book"
    new "数字概念书"
    old "MOD Creator Development Kit"
    new "MOD开发工具包"
    old "Back to the Basic"
    new "回到基本"
    old "Tarot PNP Pack"
    new "塔罗 PNP Pack"
    old "Please wait for more update."
    new "请等待更多的更新。"
    old "Skipping"
    new "在跳过"
    old "{font=[gui.fontawesome]}{/font} Language"
    new "{font=[gui.fontawesome]}{/font} 语言"
    old "{font=[gui.fontawesome]}{/font} Vibrate"
    new "{font=[gui.fontawesome]}{/font} 颤动"
    old "{font=[gui.fontawesome]}{/font} Controller"
    new "{font=[gui.fontawesome]}{/font} 控制器"
    old "{font=[gui.fontawesome]}{/font} Disable"
    new "{font=[gui.fontawesome]}{/font} 不活动的"
    old "Do not display any Controller images."
    new "未标示控制器按键图片。"
    old "{font=[gui.fontawesome]}{/font} Steam Controller"
    new "{font=[gui.fontawesome]}{/font} Steam控制器"
    old "Display the Steam Controller images."
    new "标示Steam控制器按键图片。"
    old "{font=[gui.fontawesome]}{/font} General Gamepad"
    new "{font=[gui.fontawesome]}{/font} 一般控制器"
    old "{font=[gui.fontawesome]}{/font} {s}OUYA Controller{/s}"
    new "{font=[gui.fontawesome]}{/font} {s}OUYA控制器{/s}"
    old "Display the Xbox Controller images."
    new "标示Xbox控制器按键图片。"
    old "Display the OUYA Controller images."
    new "标示OUYA控制器按键图片。"
    old "{font=[gui.fontawesome]}{/font} Tic disorder"
    new "{font=[gui.fontawesome]}{/font} 抽动障碍"
    old "This will activate Ga-yeon's tic disorder."
    new "激活佳妍的抽动障碍(Tic disorder)。"
    old "This will deactivate Ga-yeon's tic disorder."
    new "关闭佳妍的抽动障碍(Tic disorder)。"
    old "{font=[gui.fontawesome]}{/font} Epilepsy-friendly"
    new "{font=[gui.fontawesome]}{/font} 关怀癫痫"
    old "This will disable some screen effects for people who have epilepsy or similar photosensitive disorders."
    new "为患有癫痫或类似感光性疾病的人群，关闭部分画面效果。"
    old "{font=[gui.fontawesome]}{/font} Blind-friendly"
    new "{font=[gui.fontawesome]}{/font} 关怀视觉障碍"
    old "This will activate the blind-friendly features with the self-voicing feature."
    new "激活关怀视觉障碍功能和语音支持功能。"
    old "This will disable the blind-friendly features."
    new "关闭关怀视觉障碍功能和语音支持功能。"
    old "Reset"
    new "重置"
    old '{font=[gui.fontawesome]}{/font} Old Version'
    new '{font=[gui.fontawesome]}{/font} 旧版'
    old "{font=[gui.fontawesome]}{/font} Authors"
    new "{font=[gui.fontawesome]}{/font} 版权所有者"
    old "{font=[gui.fontawesome]}{/font} Photographers"
    new "{font=[gui.fontawesome]}{/font} 摄影师"
    old "{font=[gui.fontawesome]}{/font} Contributors"
    new "{font=[gui.fontawesome]}{/font} 赞助"
    old "{font=[gui.fontawesome]}{/font} Rooters"
    new "{font=[gui.fontawesome]}{/font} 欢呼"
    old '{font=[gui.fontawesome]}{/font} Special Thanks To'
    new '{font=[gui.fontawesome]}{/font} Special Thanks To'
    old "{b}Choi Ga-yeon{/b}"
    new "{b}崔佳妍{/b}"
    old "{b}Birth:{/b} April 19th, 1986"
    new "{b}出生日期：{/b} 1986年4月19日"
    old "{b}Blood Type:{/b} A(RH+)"
    new "{b}血型：{/b} A型(RH+)"
    old "{b}Height / Weight:{/b} 165cm / 48kg"
    new "{b}身高/体重：{/b} 165cm / 48kg"
    old "{b}Bio:{/b} Discouraged worker, Temporary absence from Health Administration of Yonsei University"
    new "{b}经历：{/b} 失望失业者、延世大学 保健科学大学 保健行政专业 休学"
    old "{b}Bio:{/b} Discouraged worker, Temporary absence from Health Administration of ○○ University"
    new "{b}经历：{/b} 失望失业者、OO大学 休学"
    old "{b}Certificates:{/b} 1st class Hospital Coordinator, Hospital Administrator"
    new "{b}资格证：{/b} 1级 医院协调专员、医院行政人员"
    old "{b}Likes:{/b} Bagels, Margherita pizza, Sweet rice bun"
    new "{b}喜欢的食物：{/b} 芝麻江米面包、玛格丽特披萨、贝果"
    old "{b}Dislikes:{/b} Capitalism, Doctors, Members of Parliament"
    new "{b}不喜欢的：{/b} 国会议员、医生、资本主义"
    old "{b}Choi Hye-na{/b}"
    new "{b}崔慧娜{/b}"
    old "{b}Birth:{/b} June 17th, 1989"
    new "{b}出生日期：{/b} 1989年6月17日"
    old "{b}Blood Type:{/b} O(RH+)"
    new "{b}血型：{/b} O型(RH+)"
    old "{b}Height / Weight:{/b} 168cm / 48kg"
    new "{b}身高/体重：{/b} 168cm / 48kg"
    old "{b}Bio:{/b} Karaoke helper, Graduated in Tourism Food & Beverage of Korea Hotel Technical College"
    new "{b}经历：{/b} KTV服务员、韩国酒店旅游专门学校 旅游食品饮料专业 毕业"
    old "{b}Bio:{/b} Karaoke helper, Graduated in Tourism Food & Beverage of ○○"
    new "{b}经历：{/b} KTV服务员、OO学校 旅游食品饮料专业 毕业"
    old "{b}Certificates:{/b} 2nd class Barista"
    new "{b}资格证：{/b} 2级 咖啡师"
    old "{b}Likes:{/b} Money, Photography, Ga-yeon, Drinking"
    new "{b}喜欢的食物：{/b} 钱、照相、姐姐、唱歌、饮酒"
    old "{b}Dislikes:{/b} Oryide, Sweet rice bun, Nightclub"
    new "{b}不喜欢的：{/b} 芝麻江米面包、夜总会、耍酒疯"
    old "{b}Lee Seol-ah{/b}"
    new "{b}李雪雅{/b}"
    old "{b}Birth:{/b} December 7th, 1986"
    new "{b}出生日期：{/b} 1986年12月7日"
    old "{b}Died:{/b} October 3rd, 2006"
    new "{b}享年日期：{/b} 2006年10月3日"
    old "{b}Height / Weight:{/b} 158cm / 55kg"
    new "{b}身高/体重：{/b} 158cm / 55kg"
    old "{b}Bio:{/b} Maid of Lauah"
    new "{b}经历：{/b} Lauah 的侍女"
    old "{b}Certificates:{/b} Craftsman Piano Tuner"
    new "{b}资格证：{/b} 钢琴调音技能师"
    old "{b}Likes:{/b} Ga-yeon, Herself, Papa, Taejin"
    new "{b}喜欢的食物：{/b} 爸爸、自己、崔佳妍、崔泰镇"
    old "{b}Dislikes:{/b} Kelial, Mother, Tobacco, Truck"
    new "{b}不喜欢的：{/b} Kelial、妈妈、烟、卡车"
    old "{b}Staff{/b}"
    new "{b}兼职{/b}"
    old "{b}Clerk{/b}"
    new "{b}员工{/b}"
    old "{b}Park Misun{/b}"
    new "{b}朴美仙{/b}"
    old "{b}Birth:{/b} April 28th, 1974"
    new "{b}出生日期：{/b} 1974年4月28日"
    old "{b}Height / Weight:{/b} 168cm / 47kg"
    new "{b}身高/体重：{/b} 168cm / 47kg"
    old "{b}Bio:{/b} Conductor of Business Management in Arno Restaurant franchise, Essayist, Graduated in SNU Business School"
    new "{b}经历：{/b} 亚诺河连锁餐厅经营管理部 次长、首尔大学经营大学院 毕业、散文家"
    old "{b}Bio:{/b} Conductor of Business Management in Arno Restaurant franchise"
    new "{b}经历：{/b} 亚诺河连锁餐厅经营管理部 次长"
    old "{b}Certificates:{/b} Doctor of Business Administration, Advanced level of TEPS, Special level of TESAT, Top level of MK TEST"
    new "{b}资格证：{/b} 经营专业博士、《每日经济》TEST 最优秀成绩、 高级TEPS 、TESAT S级"
    old "{b}Likes:{/b} Acoustic guitar, Challenge, Taejin, Writing"
    new "{b}喜欢的食物：{/b} 写文章、挑战、崔泰镇、桶吉他"
    old "{b}Dislikes:{/b} Electronic products, Game, Mantis, Sloth"
    new "{b}不喜欢的：{/b} 游戏、懒惰、病毒疣、电子产品"
    old "{b}Interviewer{/b}"
    new "{b}面试官{/b}"
    old "{b}Birth:{/b} Top Secret"
    new "{b}出生日期：{/b} 一级机密"
    old "{b}Height / Weight:{/b} Top Secret"
    new "{b}身高/体重：{/b} 一级机密"
    old "{b}BWH:{/b} Top Secret"
    new "{b}BWH:{/b} 一级机密"
    old "{b}Bio:{/b} Conductor of Business Management in ○○"
    new "{b}经历：{/b} OO连锁餐厅经营管理部 次长"
    old "{b}Kim Yunwoo{/b}"
    new "{b}金允宇{/b}"
    old "{b}Birth:{/b} January 19th, 1986"
    new "{b}出生日期：{/b} 1986年1月19日"
    old "{b}Blood Type:{/b} AB(RH+)"
    new "{b}血型：{/b} AB型(RH+)"
    old "{b}Height / Weight:{/b} 172cm / 58kg"
    new "{b}身高/体重：{/b} 172cm / 58kg"
    old "{b}Bio:{/b} Bassist of The Ghost Crying"
    new "{b}经历：{/b} 鬼哭声乐队贝斯手"
    old "{b}Bio:{/b} Bassist of ○○"
    new "{b}经历：{/b} OO乐队贝斯手"
    old "{b}Likes:{/b} Bob Dylan, Choi Ga-yeon, Yu Jaeha"
    new "{b}喜欢的食物：{/b} 鲍勃·迪伦、柳在夏、崔佳妍"
    old "{b}Dislikes:{/b} Auditions, Management, Soju"
    new "{b}不喜欢的：{/b} 管理、烧酒、试镜"
    old "{b}Choi Taejin{/b}"
    new "{b}崔泰镇{/b}"
    old "{b}Birth:{/b} March 28th, 1986"
    new "{b}出生日期：{/b} 1986年3月28日"
    old "{b}Blood Type:{/b} B(RH+)"
    new "{b}血型：{/b} B型(RH+)"
    old "{b}Height / Weight:{/b} 182cm / 73kg"
    new "{b}身高/体重：{/b} 182cm / 73kg"
    old "{b}Bio:{/b} Lead Guitarist of The Ghost Crying, Graduated in Seoul Institute of the Arts"
    new "{b}经历：{/b} 贵哭声乐队领队 吉他手、首尔艺术大学 实用音乐学部 毕业"
    old "{b}Bio:{/b} Lead Guitarist of ○○, Graduated in ○○"
    new "{b}经历：{/b} OO领队 吉他手、OO大 毕业"
    old "{b}Certificates:{/b} Bachelor of Arts Degree in Gebrauchsmusik"
    new "{b}资格证：{/b} 实用音乐艺术学士"
    old "{b}Likes:{/b} Marylin Manson, NIN, Rammstein, Shin Junghyeon,\nShin Haechul"
    new "{b}喜欢的食物：{/b} 九寸钉乐团、德国战车、玛丽莲曼森、申重鉉、申海澈"
    old "{b}Dislikes:{/b} Eggplant, Ginger, Idol"
    new "{b}不喜欢的：{/b} 茄子、生姜、偶像"
    old "{b}Park Hyeongsik{/b}"
    new "{b}朴炯植{/b}"
    old "{b}Birth:{/b} December 17th, 1979"
    new "{b}出生日期：{/b} 1979年12月17日"
    old "{b}Bio:{/b} Physician, Graduated in School of Medicine of Sungkyunkwan University"
    new "{b}经历：{/b} 内科医生、成均馆大学 医科大学 毕业"
    old "{b}Bio:{/b} Physician, Graduated in ○○"
    new "{b}经历：{/b} 内科医生、OO大学 毕业"
    old "{b}Certificates:{/b} Medical Licence"
    new "{b}资格证：{/b} 医师执照"
    old "{b}Likes:{/b} Fame, Money, Power"
    new "{b}喜欢的食物：{/b} 权利、钱、名誉"
    old "{b}Dislikes:{/b} Capitalism, Members of Parliament, Soju"
    new "{b}不喜欢的：{/b} 国会议员、烧酒、资本主义"
    old "{b}Doctor{/b}"
    new "{b}内科医生{/b}"
    old "{b}Bio:{/b} Physician"
    new "{b}经历：{/b} 内科医生"
    old "{font=[gui.fontawesome]}{/font} Stop"
    new "{font=[gui.fontawesome]}{/font} 停"
    old "{font=[gui.fontawesome]}{/font} Shuffle"
    new "{font=[gui.fontawesome]}{/font} 无序播放"
    old "{font=[gui.fontawesome]}{/font} Loop"
    new "{font=[gui.fontawesome]}{/font} 重复"
    old "{font=[gui.fontawesome]}{/font} Previous"
    new "{font=[gui.fontawesome]}{/font} 上一页"
    old "{font=[gui.fontawesome]}{/font} Next"
    new "{font=[gui.fontawesome]}{/font} 下一页"
    old "{font=[gui.fontawesome]}{/font} Random"
    new "{font=[gui.fontawesome]}{/font} 随机"
    old "{font=[gui.fontawesome]}{/font} Add to cart"
    new "{font=[gui.fontawesome]}{/font} 添加到购物车"
    old '{size=[gui.quick_button_text_size]}Stop{/size}'
    new '{size=[gui.quick_button_text_size]}停{/size}'
    old '{size=[gui.quick_button_text_size]}Previous{/size}'
    new '{size=[gui.quick_button_text_size]}上一页{/size}'
    old '{size=[gui.quick_button_text_size]}Next{/size}'
    new '{size=[gui.quick_button_text_size]}下一页{/size}'
    old '{size=[gui.quick_button_text_size]}Loop{/size}'
    new '{size=[gui.quick_button_text_size]}重复{/size}'
    old '{size=[gui.quick_button_text_size]}Shuffle{/size}'
    new '{size=[gui.quick_button_text_size]}无序播放{/size}'
    old "Prologue"
    new "概要"
    old "Discouraged Worker"
    new "失望失业者"
    old "Depressive Disorder"
    new "抑郁症"
    old "Reclusive Outsider"
    new "宅男、宅女"
    old "IMF Crisis"
    new "IMF经济危机"
    old "Anxiety Disorder"
    new "焦虑症"
    old "Medical Referral"
    new "诊疗委托书"
    old "Bridge of the Life"
    new "生命之桥"
    old "Epilogue"
    new "结局"
    old "Accident"
    new "事件发生"
    old "Flowery Mornings and Moonlit Nights"
    new "花朝月夕"
    old "Red Dialogue Window"
    new "红色指纹窗口"
    old "Seohae Grand Bridge"
    new "西海大桥 29辆 追尾事故"
    old " A discouraged worker is a person of legal employment age who is not actively seeking employment, or who can not find employment after long-term unemployment. This is usually because an individual has given up looking or has had no success in finding a job, hence the term \"discouraged\".\n\n{a=https://en.wikipedia.org/wiki/Discouraged_worker}Wikipedia{/a}\n\n Discouraged workers are classified as an economically inactive population and not included in the unemployment rate, although they are actually unemployed.\n\n And this artificially causes a decrease in the unemployment rate in official statistics, in spite of an actually higher unemployment rate. In the case of Korea, the Subsidiary Employment Index, which includes the not-calculated unemployed, was reported first in November, 2014, and accordingly, the hidden problems in Korea's employment-population ratio and discouraged workers have surfaced."
    new " 失望失业者的词典意义是虽然有求职的欲望，但是因为无法找到合适的工作而放弃求职的人。 这些人虽然在法律规定的工作年龄范围内，但大部分因为放弃求职或没有成功而不再寻找工作，或长时间处于失业状态后不再进行求职活动。 因此出现了\"失望失业者\"这一单词。\n\n 失望失业者本质上应该是失业者，但是因为不满足失业者的条件而被分类到非经济活动人口，并不包含在失业者统计范围内。\n\n 所以，虽然我们感觉失业率再上升，但统计数据却显示失业率下降的现象。2014年11月，韩国首次发表了包括了隐藏失业者的辅助就业指标，韩国的就业率和失望失业者的问题也便浮出了水面。"
    old " Reclusive outsider is the phenomenon of reclusive adolescents or adults who withdraw from social life, often seeking extreme degrees of isolation and confinement. The term reclusive outsider refers to both the sociological phenomenon in general as well as to people belonging to this societal group.\n\n{a=https://en.wikipedia.org/wiki/Hikikomori}Wikipedia{/a}\n\n Choi Ga-yeon, a heroine of \"Discouraged Workers\", suffered from depressive disorder because of the sudden firing from her job and breaking-up with her lover.\n\n In addition, with her continuous failure to get a job, her anxiety disorder symptoms only became worse. And she naturally has become a hikikomori(a person who becomes a recluse and gives up any social life) after she gave up trying to get a job."
    new " 宅男、宅女是指呆在屋内或家里等特定的空间内，无法走出去或不出去的人和这样的现象。 2005年日本精神科医生斋藤真希通过自己的著作，首次发表了宅男宅女的概念。\n\n{a=https://zh.wikipedia.org/wiki/%E9%9A%B1%E8%94%BD%E4%BA%BA%E5%A3%AB}维基百科{/a}\n\n \"失望失业者\"的主人公崔佳妍在工作过程中被解雇后，患有与恋人分手后遗症引发的抑郁障碍，持续的求职失败，加重了这种不安的情绪，使她的症状越发严重了。\n\n 自从放弃求职后，与周围人的关系变得越来越疏远，自然而然的成了宅男宅女的一员。"
    old "Lee Yunseok -YGGDRASIL STUDIO"
    new "李允錫 -YGGDRASIL STUDIO"
    old " Generally, a medical referral is issued by a hospital when sending a patient to another hospital. Ga-yeon has received medical treatment from a psychiatrist since she was fired from the hospital where she was working as a coordinator. In spite of long treatment, her condition did not improve at all, and the hospital issued a medical referral to another hospital. But Ga-yeon refused the referral as she felt the psychiatrist gave up on her, and this made her fall into despair. So she didn't seek any more psychiatric treatment.\n\n Since many people still think negatively about seeking psychiatric treatment, and have unfavorable perceptions about those who seek it, often, people who need help with their problems, tend to avoid getting the help they need, both here in Korea and elsewhere in the world.\n\n Also in the case of Ga-yeon, she hasn't talked about it, regarding it as her embarrassing secret. The medical referral Yunwoo found in Ga-yeon's mailbox was actually a referral that Hye-na arranged for her.\n\n Actually, the description shown in the medical referral in the \"Ga-yeon and Yunwoo\" part of the story, is almost the same as the one commonly issued in a real hospital in Korea."
    new " 诊疗委托书是一般在将患者从一个医院转送到其他医院时开的单据。 佳妍在内科做协调专员过程中被解雇后，从那时就开始去神经精神科接受治疗，但并没有好转现象。 医院开了委托其他医院进行治疗的委托书。 但是佳妍认为医生已经放弃了对她的治疗，并对此感到失望以及绝望，便拒绝了委托书。而且从那以后再也没有去过精神科。\n\n  在韩国，直到目前还有很多人仍带着有色眼镜看待神经精神科。 仍然有很多人害怕对方知道自己在神经精神科接受过治疗的事实，担心会产生不好的印象，因此大部分想去治疗的患者也产生了抗拒心理。\n\n 佳妍也认为这个是自己缺点而没有告诉任何一个人，就这样隐瞒着。 允宇在信箱中发现的诊疗委托书是慧娜放进去的。\n\n 描述\"佳妍和允宇\"诊疗委托书的内容和实际韩国神经精神科开的是一样的。"
    old " Anxiety disorders are a category of mental disorders characterized by feelings of anxiety and fear, where anxiety is a worry about future events and fear is a reaction to current events. These feelings may cause physical symptoms, such as a racing heart and shakiness.\n\n{a=https://en.wikipedia.org/wiki/Anxiety_disorder}Wikipedia{/a}\n\n My mother had suffered from panic disorder for almost eight years, and she used to complain of pain and hyperpnea in certain and sometimes new and unexpected situations(Hyperpnea is the need to breathe more deeply because the person experiencing it feels light headed or otherwise feels they need more oxygen for various reasons.).\n\n And someone whom I know had anxiety disorder, and she suffered from a tic disorder including repetitive eye blinking and apnea when she feels anxiety in those same kinds of situations. She was even very dependent on alcohol and showed symptoms of caffeine addiction as well. Standing by my mother's and her side, and watching their pain and experiencing it with them, I hoped to help set them free from those painful days. But as time went by, I found I was getting numb with their pain, and at that moment, I felt extremely ashamed as a human being."
    new " 焦虑症的词典意义是病态忧虑引起的，过度的心理痛苦或难以适应现实的种种现象。\n\n  我的妈妈患了8年的恐慌障碍。在特定或不特定的任何情况下，伴随着痛苦的呼吸，抱怨着疼痛。 还有一个人也是焦虑症患者。 在特定或不特定的任何情况下，随着焦虑出现眨眼睛和无呼吸的症状。 后来还出现了酒精中毒和咖啡因上瘾症状。\n\n 每次遇到这样的情况，我都有一种想要治好他们的想法。 但是随着时间的流逝，我发现我自己也被他们的痛苦变得麻木了，作为人类便陷入了 的自责。"
    old " Depressive disorder is a mental disorder characterized by a pervasive and persistent low mood that is accompanied by low self-esteem and by a loss of interest or pleasure in normally enjoyable activities. The term \"depression\" is used in a number of different ways. It is often used to mean this syndrome but may refer to other mood disorders or simply to a low mood. Major depressive disorder is a disabling condition that adversely affects a person's family, work or school life, sleeping and eating habits, and general health.\n\n{a=https://en.wikipedia.org/wiki/Major_depressive_disorder}Wikipedia{/a}\n\n Choi Ga-yeon, a heroine of \"Discouraged Workers\", suffered from depressive disorder because of the sudden firing from her job and breaking-up with her lover. In addition, with her continuous failure to get a job, her anxiety disorder symptoms only became worse. And she naturally has become a hikikomori(a person who becomes a recluse and gives up any social life) after she gave up trying to get a job."
    new " 抑郁症的词典意义是指病态程度的抑郁状态。 与暂时性感到的忧郁情绪是不同的。 \"失望失业者\"的主人公崔佳妍在工作过程中被解雇后，患有与恋人分手后遗症引发的抑郁障碍， 持续的求职失败，加重了这种不安的情绪，使她的症状越来越严重了。 自从放弃求职后，与周围人的关系越来越疏远，自然而然的成了宅男宅女的一员。"
    old " \"Bridge of the life\" was actually a sort of attempt using advanced technological methods to prevent suicide. By trying to have a conversation with a pedestrian through hopeful words and changing their desperation into hope, the designers thought suicidal people might be encouraged not to end their lives, but, in the event that failed, there was still the traditional physical anti-suicide barrier. The sensors mounted on every section of the bridge detects the exact location of a pedestrian as she/he walks by and the bridge lights the hopeful word up in the right position for a pedestrian to read.\n\n The very first bridge of life opened on Mapo Bridge, Korea on September 26, 2012, and was sponsored by Seoul City and Samsung Life Insurance. Mapo Bridge was chosen as the first installation of this new technology because it has been notorious as the place with the highest suicide rate. And the second one opened on Hangang Bridge, Korea on November 5, 2013, sponsored by Korea Health Promotional Foundation.\n\n And the ad for \"Bridge of the life\" received 39 awards in the International Advertising Festival and obtained excellent advertising effects. But regardless of this successful record, the rate of suicides by death leap has steadily increased. According to statistics, installing closed circuit television on the public bridges was more helpful in preventing suicide jumps and rescuing suicide jumpers who actually did jump than the bridge of life technology.\n\n As a result of the Samsung Life Insurance's decision to discontinue their operational support for \"Bridge of the Life\" on Mapo Bridge in September 2015, the automatic detection sensor has not worked since December 1, 2015 and the website of Bridge of the Life was also closed.\n\n In fact, Hangang Bridge wasn't yet built at the time that the \"Discouraged workers\" story takes place. But in the game, it was set as a background to let Yunwoo try to think where Ga-yeon disappeared to."
    new " 生命之桥是超越现有的物理性防止自杀手段， 通过带有希望的语句，与步行者形成沟通，将悲观转换成希望，为了防止自杀尝试的尖端方式。 每个区间设置的传感器，按照步行者的步行幅度感应位置后，点亮设置在该位置的希望语句照明的一种方式。\n\n 2012年9月26日，麻浦大桥被人们称为自杀率第1位的称号。首尔特别市和三星生命共同在有这种否定印象的麻浦大桥首次开通了生命之桥。 2013年11月5日，韩国健康增进财团也助一臂之力，在汉江大桥开通了生命之桥。\n\n 生命之桥视频在国际广告节上获得了39个部门的大奖，虽然展现出了优秀的广告效果，但自杀率却与它毫无关系的渐渐增加。 反倒闭路电视的安装和普及更有助于防止自杀或解救自杀的人。\n\n  2015年9月，随着三星生命终止支援麻浦生命之桥的运营， 从2015年12月1日开始，自动感应传感器不再启动，而且也关闭了生命之桥的官网。\n\n 失望失业者舞台的真正时期虽然是在开通汉江大桥的生命之桥前， 但是为了让允宇产生失踪的佳妍会去哪里的苦恼而存在的设定。"
    old " The Asian financial crisis was a period of financial crisis that gripped much of East Asia beginning in July 1997 and raised fears of a worldwide economic meltdown due to financial contagion.\n\n The crisis started in Thailand with the financial collapse of the Thai baht after the Thai government was forced to float the baht due to lack of foreign currency to support its fixed exchange rate, cutting its peg to the U.S. dollar, after exhaustive efforts to support it in the face of a severe financial over-extension that was in part real estate driven.\n\n{a=https://en.wikipedia.org/wiki/1997_Asian_financial_crisis#South_Korea}Wikipedia{/a}\n\n At the time, Thailand had acquired a burden of foreign debt that made the country effectively bankrupt even before the collapse of its currency. As the crisis spread, most of Southeast Asia and Japan saw slumping currencies, devalued stock markets and other asset prices, and a precipitous rise in private debt.\n\n Indonesia, South Korea and Thailand were the countries most affected by the crisis. Hong Kong, Laos, Malaysia and the Philippines were also hurt by the slump. Brunei, China, Singapore, Taiwan and Vietnam were less affected, although all suffered from a loss of demand and confidence throughout the region."
    new " 大韩民国的IMF救济贷款请求是面临国家破产危机的韩国，从IMF获得资金支持的签订谅解备忘录的事件。 发生在1997年12月3日。 企业连续倒闭，外汇储备金额骤减，向IMF要求了20亿美金的紧急融资请求。 外汇危机中的大韩民国，外汇储备金额一时骤减到39亿美金。 但从IMF获得195亿美金的救助贷款而幸免了国家破产的事态。\n\n 泰国、香港、马来西亚、菲律宾、印度尼西亚等东南亚的连续\‘外汇危机\’中，大韩民国政府外汇管理政策的不成熟和失败成了\"IMF汇乱\"的直接原因。 1997年11月10日， 大韩民国第14届总统金泳三在和 姜庆植经济副总理的通话前，还不知道外汇危机的严重性。\n\n 很多公司出现了倒闭及经营危机现象。 在这个过程中，因大量的解雇和经济恶化，大韩民国的国民经历了很大的困难和挫折。 发生事件后不久的1997年12月18日，大韩民国的第15届总统选举会开始了。 这次选择中，执政党败给反对党后，发生了政权交替。\n\n 1998年12月，以向IMF紧急保管金融偿还18亿美金作为转折点，大韩民国渐渐的摆脱了金融危机。 2000年12月4日，金大中总统公开发表\"偿还了所有的国际货币基金组织的贷款， 我们国家从\‘IMF危机\’完全摆脱出来了。\" 2001年8月23日，结束了对大韩民国的\"IMF管理体制\"。"
    old " \"Accident\" tells what happens after \"Epilogue\" which is the basic ending of \"Discouraged Workers\".\n\n Ga-yeon reached out her hand toward Yunwoo, but at that moment, she blacked out and fell off the bridge. And Yunwoo threw himself into the river to save her. A few days later, they rose to the surface, and one passerby's report told their deaths to the world.\n\n If Yunwoo hadn't found his wallet, Ga-yeon would die alone while he was haggling over the taxi fare."
    new " \"事件发生\"是在 \"结局\"上连接的\"失望失业者\"的基本结局。\n\n 佳妍虽然向允宇伸出了手，但是很快昏迷而坠落到大桥底下。 因此，允宇为了救她，也跳进了江里。 几天后，两个人的尸体浮出了江面，路过的行人报警后，两个人的死亡才被世人知晓。\n\n 如果允宇在佳妍的房间内没有找到钱包，那么就会在因为出租费与司机争执的时间，佳妍则会死亡。"
    old " As a hospital coordinator, Ga-yeon fell in love with a doctor at the hospital she was working in and they had an affair even though the doctor was a married man. When the director found out, she was fired. For over a year she tried to find another job, but her mental uneasiness eventually made her give up and she became a recluse.\n\n A year later, in the spring of 2013, her younger sister, Hye-na, and her first love Yunwoo come to her.\n\n A story about the dark side of today's youth and serious life events happening around Ga-yeon."
    new " 作为医院协调专员的佳妍爱上了自己医院的医生。但这个医生却是有妇之夫，所以两人的爱情是不能被人所接受的。虽然被知道了实情的院长解雇之后尝试找了其他工作，但因为精神的不稳定和现实的屏障，一年内没有找到任何工作，最后她放弃了就业。\n\n 然后又过了一年，到了2013年春天，已经成了一个宅女的她，身边出现了她的妹妹慧娜和初恋允宇。\n\n 生活在这个时代的年轻人阴暗的一面和以佳妍为中心展开的并不简单的日常生活。"
    old " \"Flowery Mornings and Moonlit Nights\" is the true ending which assumes that Ga-yeon didn't faint and grabbed Yunwoo's hand in \"Epilogue\". Originally \"Discouraged Workers\" was intended to end with the \"Accident\" story as the true ending. But after deciding to release it in the market, this was chosen as the true ending.\n\n Ga-yeon finds the culprit who spread the video, with the help of Yunwoo, and reports him to the police. After that, she tries to find a job, but it's still not easy for her. Even some interviewers who know her, hurt her.\n\n Yunwoo just stays by her side and tries to protect her without saying anything, and Hye-na helps Ga-yeon to work part-time at the cafe where she's working. Ga-yeon works hard every day, grateful for being allowed to work there. One day, the cafe manager gives her a letter of recommendation from the general manager of the head office, and Ga-yeon gets an opportunity to have an interview for a large affiliated store run by the head office. And by chance, the interviewer she meets with for the job is her old boss, who during her schooldays, originally gave her the idea of her dream job being a restaurant manager. Ga-yeon passes the interview with ease, and finally, she starts to move towards her dream."
    new " \"花朝月夕\"是在\"结局\"中，佳妍没有昏迷前抓住允宇手的时候假设的真实结局。 失望失业者本来的结局是\"事件发生\"，但决定商业用出版后，采纳了这个为真正的结局。\n\n 佳妍在允宇的帮助下，对视频传播者进行拘留。 此后，努力寻找工作，但是并不简单， 佳妍从认出他的人和面试官那里受到了深深的伤害。\n\n 允宇在这样的佳妍旁边，默默的守候着她。 慧娜帮助佳妍，能够在自己工作的咖啡店里工作。 虽然是小时工，但是能够有工作就已经很感激的佳妍，通过她的认真工作，咖啡店经理将总部次长的推荐书转达给了佳妍。 佳妍拿着推荐书，去了总部正准备的大型加盟店面试。 恰巧遇到了学生时代让她抱有快餐业经理梦想的队长，就是她的面试官。 堂堂正正面试合格的佳妍，朝着自己的梦想方向走去。"
    old " A chain reaction collision, involving 29 vehicles, happened at 7:50am on October 3, 2006, Korean time, on Seohae Grand Bridge in South Korea. This collision happened due to a thick fog, and it left 12 people dead and about 50 injured. According to the investigation, the accident occurred not only because of bad weather, but also because some drivers were speeding as well as shoulder riding. But whatever the reason was, the damage was almost 4 billion won, which was the most awful and costly accident in Korean car insurance history.\n\n \"Lee Seol-ah\" is a fictitious character who died in this accident. This woman, who died at the age of 21, still in the flower of her youth, visits the world she used to live in after she died, and watches people whom she loved and shared friendships with. One day, she meets Ga-yeon who helped her in the past. To prevent her death, she decides to help Yunwoo."
    new " 西海大桥29辆追尾故事发生在韩国标准时间2006年10月3日上午7时50分左右。 大雾造成29辆汽车连锁追尾事故，12人死亡、50人受伤。 除了气象情况外，司机的超速、部分司机的路边行驶也是事故的原因。 受害金额为约40亿元左右，是韩国车辆保险中，历史上最大的事故记录。\n\n \"李雪雅\"是重大故事中死亡的假设人物。 21岁青春时代死亡的这个女性，决定访问自己生活过的世界，关注与人们分享爱情和友情的人。 过去佳妍有帮助过她，所以为了阻止佳妍的死亡，决定帮助允宇。"
    old " In \"Discouraged Workers\", a word box in red color is used to show the words and thoughts of Ga-yeon and a clerk Because when the basic scenario was developed, they are actually not alive.\n\n But when Ga-yeon is talking with her mom on the phone, the black box is used out of consideration for her mother."
    new " 失望失业者的红色指纹窗口是用在表达主人公佳妍和职员的想法和意见的时候使用。 因为这些在基本剧本中，按照实际世界时间为标准时，处于已经死亡状态。\n\n 与佳妍母亲通话的时候，为了考虑到她的母亲，使用了黑色指纹窗口。"
    old "{font=[gui.fontawesome]}{/font} Find the diary in the room."
    new "{font=[gui.fontawesome]}{/font} 找到房间里的日记。"
    old "{font=[gui.fontawesome]}{/font} The information is unknown at this time."
    new "{font=[gui.fontawesome]}{/font} 目前这些信息是未知的。"
    old "My cool captain!"
    new "出色的队长姐姐"
    old "My captain's tear"
    new "队长姐姐的眼泪"
    old "Went to see Yunwoo"
    new "探望"
    old "I rejected him"
    new "拒绝了他的告白"
    old "As a friend"
    new "做朋友吧"
    old "My days in hospital"
    new "医院生活"
    old "Observing a doctor"
    new "观察医生"
    old "His wife"
    new "他的妻子"
    old "Farewell"
    new "离别"
    old "I miss him"
    new "想念"
    old "Sign"
    new "征兆"
    old "A lunatic"
    new "精神病患者"
    old "My friend, Eunju"
    new "和朋友一起"
    old "Getting a job"
    new "就业活动"
    old "Rubbish and rubbish can"
    new "垃圾和垃圾桶"
    old "Dying message"
    new "临终留言"
    old " It's been more than a month since I started working in a family restaurant. In the beginning, it was really hard to carry a tray and I even broke a few dishes. But now, I feel like I'm getting better and better. Sometimes, customers tip me as well, and also the other staff often praises my work. I'm especially good at…. hmmm…. well, it's too many to write them all down here! Later!\n\n However, the captain looks really cool. She's beautiful, smart, and also good at her work. Oh, she seems to be strong as well, as she usually carries heavy things by herself!\n\n I saw her carrying two metal trays stacked with dishes with just her two hands. It is hard even for men, but she's such a superwoman. How the hell can she do that? I hope I can do work as well as her someday."
    new " 时间过得真快，在家庭餐馆打工的日子已有一个多月了。刚开始，因为抓不住托盘的中心，打碎了好几个碟子，不过现在呢，我自己看起来都认为做得很不错。偶尔会收到客人们给的小费，也经常听到周围的同事夸我。我做得比较好的事情，具体来说主要有….嗯….，要是想一一记录，那真的太多了，所以PASS!\n\n 啊！顺便说一句，我们大堂的队长姐姐真的很厉害。长得好看不说，人又聪明办事又利索。很重的东西 也可以自己拿来拿去的，装满碟子的托盘，也可以用一只手来托住，男人应该也很难做到吧，这个姐姐真像怪物一样。怎么把活做的那么好？我也真心想像队长姐姐那样，把事情做的那么干净利索。"
    old " Today the section chief of the head office visited the restaurant. I thought the chief would be a man, but she was a young woman. She came to our restaurant and called the captain to the locker room. She passed by me while I was working there, and I saw her nametag. And I found she has the same name as a famous comedian. Funny!\n\n As the captain was not in the hall, I tried to look for her, and when I opened the door of the locker room, she looked at me in surprise and turned her face hurriedly. And she said leave her alone for a while, forcing me out of the room. She was crying.\n\n Probably the section chief made her cry. That bitch! What did the captain do wrong? Hey, I'll get even with her!! Shit!"
    new " 今天家庭餐馆里来了总部的科长，本来以为会是个大叔，来的却是看起来挺年轻的一个女人，叫了我们的队长姐姐，进了更衣室。我工作的时候，她正好经过我的旁边，我挑眼一看胸牌上的名字。和著名的女笑星名字一样，记起来蛮容易的。\n\n 但是，我在大堂里没有看见队长姐姐，于是去了更衣室。打开门的瞬间，在里面的姐姐看我到以后，慌张的把头转过去说让我出去呆着，边推我边把门关上了。\n\n 姐姐哭了，是那个女人把我们的队长姐姐弄哭了。以为自己是科长了不起吗? 队长姐姐到底做错了什么，至于弄哭吗？呃，朴美仙科长！我一定会替队长姐姐报仇!嗯！！"
    old " I went to Cheolwon, with Eunyoung to see Yunwoo today. I didn't realize it was that cold, but when I got off the bus, I was just shocked as it was literally freezing. It didn't snow, and the wind didn't blow, but cold air made even my eyes freeze. Eunyoung and I hurried into the visitor's room to wait for Yunwoo.\n\n A few minutes later, a soldier came in - actually I recognized that he was Yunwoo as soon as I saw him! And I got the giggles. His camouflage patterned muffler looked pretty cool, but his earmuffs reminded me of a once famous singer, and I couldn't stop laughing!\n\n I told him about that singer, and he got embarrassed. Eunyoung took his earmuffs away and danced, and all of us burst into laughter.\n\n However, since we said goodbye to Yunwoo, I've felt somewhat lonesome, and I still feel that way even as I'm writing this…. why do I feel this way?"
    new " 今天为了去探望允宇，我和恩英去了铁原。坐在车上的时候并没有察觉到，但下车后发现实在太冷了。也不是下雨，风也不大，可是空气太寒冷了，以致于我的眼睛都凉飕飕的。我和恩英抓紧时间进了会面所，等着和允宇见面。\n\n 过了几分钟后，会面所进了一位军人大叔-虽然一眼就看出了那是允宇-但还是喷出了笑声。迷彩围脖倒觉得很好看，但是看到耳包以后，突然想起了上中学时候的歌手严正花，于是忍不住的笑了出来。允宇酷酷地坐了下来，当我把刚才脑海里飘过的想法说了出来，恩英便把允宇的耳包抢了过来，戴上以后跳起了舞蹈，我们又笑得前仰后合的。\n\n 结束了探望后回家的路上，从在车上写日记开始到现在，我突然觉得有一点点寂寞，这是什么样的感情呢…。"
    old " After I parted with him, and while I was coming home, I tried really hard to fight back tears. But when I arrived in my room, I just burst into tears. Why? Why was I so mean to him? I raged at him, and told him to quit music. Why the hell did I do that?\n\n Today he told me what I've really looked forward to hearing from him, but why…. why couldn't I accept him? And why did I hurt him? I can't stop crying…."
    new " 和他分开后回家的一路上，一直忍住的眼泪，一回到家就控制不住了。怎么了呢？为什么对他那么残忍了呢？最后我还发了火，跟他说不要再搞音乐了。\n\n 到底是怎么了？我从他嘴里听到了等了这么久的话，为什么没有接受反而给他伤害了呢，就这样眼泪总是往下掉。"
    old " I had a long conversation with Yunwoo today;\n\n You've just been discharged from the army, and I'm a student without a job. So what can we do now? You really think we can get married and start our home? Seriously? How?\n\n Besides, we're not romantically involved with each other. We're just friends. I think of you as my friend, and hope we could get along well with each other for a long time. That's all….\n\n I think I probably said it like that…. but of course it's not true that I think of him just as a friend, but…. To get back to our relationship as usual, I had to say it that way.\n\n I also said sorry that I hurt him.\n\n However, unexpectedly, it seemed he doesn't care about it. He said he was actually kidding when he asked me to marry him. And since I already refused his proposal anyway, there's nothing hard about getting along with me simply as a friend.\n\n What he said made me a little bit regretful, but anyway, we decided to leave as good friends as we've always been."
    new " 和允宇聊了很长时间。\n\n 刚刚退伍的你和大学生的我，现在还没有工作的我们用什么结婚，靠什么生活呢？ 我对他说，你觉得这个现实吗？接着我还对他说，我们也不是恋人关系，我一直把你当作朋友，希望以后也一直保持好朋友的关系。\n\n 当然，说把他当作朋友是谎话，但是为了回到我们以前的关系，我认为我只能这么说，对于我给他的伤害，我真心的向他道了歉。\n\n 万万没想到他并不介意的回答道，虽然说要结婚的事情并不是开玩笑的，但是已经被拒绝了，根本不影响我和你做朋友的关系。你要是不觉得尴尬，那我们可以继续做朋友。\n\n 虽然听了那句话，有点伤心，但是后来我们决定依旧做好朋友。"
    old " It's been almost a year since I started working in this hospital. I work as a coordinator of the hospital. I had my salary raised, and also I'm pretty satisfied with my job. My savings account with the balance which gets bigger and bigger makes me feel really happy.\n\n When I had to quit the university temporarily, I was just stunned. But now that I think about it, it was rather smart to do that, actually. Because of that choice, I was able to pay Hye-na's university tuition, without a loan.\n\n I'll save more money to send Mom and Daddy to travel on, and also support Hye-na until she gets married someday. Jeez, why is time passing so fast today? Until tomorrow, I'm going to bed!\n\n Ga-yeon, just keep it up as you've done so far!"
    new " 在医院的工作都已经一年了，我现在在做医院协调专员。工资也比刚开始涨了很多，对现在的工作也比较满意。看到存折上一点一点攒起来的工资，我感到很幸福。\n\n 要休学时，当时眼前一片漆黑，不过现在仔细想想，我倒觉得更好。因为不用贷款，我也能解决慧娜的学费问题。\n\n 就这样一直攒钱下去，也能够让爸爸妈妈去旅游，慧娜结婚时，也能够帮她一些，天呀，都这么晚了！\n\n 为了明天的崔佳妍，加油！"
    old " Oh, my god…. how could he look like him that much? His face, way of talking, character, and even that he can't hold liquor well…. everything is just like him. He reminds me of Yunwoo a lot. And it makes me feel sad. And this keeps bothering me so much. These days, I'm often trying to speak to him, or be around him. He also seems to be interested in me, and sometimes talks to me, or brings some snack or drink. He looks like a pretty good man."
    new " 怎么会长得这么像？长相、语气、性格、甚至不能喝白酒的这一点也是如此地相像。每次看到他的时候，就会想起允宇，心隐隐约约开始痛起来。所以我总是关注着他。能多说一句就多说一句，总是徘徊在他的周围。或许他也意识到了，所以偶尔也故意来我身边搭上两句话，或者给点零食饮料什么的。觉得他人蛮不错的。"
    old " His wife visited the hospital. Though the Director and my lover prefer a simple and plain style, she dressed up too much, with luxurious dress and accessories. She looked just full of vanity. When I saw she's coquetting with him arm in arm, she really looked like an old fox. I can't imagine she's the Director's sister, and my lover's wife. She really makes me feel sick.\n\n When he and I were left alone because of night duty. he talked to me as if he was just working, because he knew we were being recorded on a CCTV.\n\n After finishing work, I got out of the hospital, and sat alone on the bench in front of the building. After a while, all lights were off in the hospital except one—Light from his office, coming through the blinds."
    new " 他的妻子来医院了。和简朴的院长还有他比起来，身穿着价格不菲的衣服和贵重的首饰，能够看出内心里充满了虚荣心。看到挎着他的胳膊撒娇的样子，只能用老狐狸来形容她了。就这样的女人也能是院长的妹妹、他的妻子，真是又郁闷又不痛快。\n\n 医院里，只有剩下值班的我和他，能察觉到他意识CCTV的存在，所以装着工作的样子，来到服务台和我搭起话来。\n\n 终于到下班的时间了，我向他打完招呼，便从医院出来坐在前面的休息椅上。过了一会儿，医院的所有灯都灭了，只有他诊疗室的灯照亮了百叶窗。"
    old " The director seemed to be trying hard not to hurt me, controlling his feelings. I understand he would feel betrayed as he has trusted me a lot, but he never swore at me at all, and treated me human to human. And now, I've finally realized what the hell I did. I felt really sorry for his wife, as she has never thought about this, and also felt sorry for the director who has always truly taken care of me. At the request of the Director, I decided to quit the hospital. I also said to him I would definitely break off my affair with the Doctor.\n\n After I packed up my stuff and got out of the hospital, I saw him running after me, but I just came out of the building and got into a taxi. In the running taxi, I just cried and cried. I could never see my colleagues there and the Director anymore…. and also him…. whom I made love with…. goodbye, everyone…. My greed has screwed up everything. Thank you all, and sorry…."
    new " 能看出院长为了不伤害我，尽全力抑制住自己的感情。这段时间，她对我付出了真心，那么地喜欢我，所以应该会有我背叛她的感觉。但是直到最后也没有骂我一句，尊重了我的人格。直到今天，我才知道我犯下了天大的错误。对于毫不知情的他的妻子感到愧疚，也对一直关心我的院长感到对不起。我按照院长的话，决定离开医院。也答应把和他的关系整理清楚。\n\n 我对这个医院已经产生了不少感情，最后拿着收拾好的东西出来的时候，正好看到他跑出来的场景，但我毫不犹豫的出门后打车离开了医院。\n\n 在车上我哭了，以后再也不能和医院同事还有院长见面了，还有相爱过的那个人…，现在再见…我的野心毁了我的一起。感谢大家，对不起…。"
    old " Every single day, I cry, sleep, and wake from sleep, remember my good old days, especially with him, and then, cry, and fall asleep again. Beginning with a few days ago, I sometimes burst into laughter, and sometimes, burst into a fit of anger. I feel like I can't breathe well from time to time.\n\n I miss him. I miss him looking at me with a gentle smile. Thinking this makes me weepy, and it becomes hard to breathe. Also at this moment I'm writing this, I'm feeling really suffocated."
    new " 最近每天都是哭着哭着就入睡了，一起来满脑子都是和他一起度过的时间，又开始掉眼泪，掉着掉着又睡着了。从几天前开始，突然有时候想笑，又有时候很愤怒，甚至有时候连呼吸都觉得很困难。\n\n 我很想他，我怀念对我眉开眼笑的他。想着想着眼睛又湿润了，呼吸也变得困难。正在写日记的现在心里也堵得慌。"
    old " Even though I had no interview today, I sat in front of my dressing table to put on makeup. But as soon as I saw my face, I was frightened, as it suddenly looked awful and disgusting. I fell backward, and managed to crawl to the bed. And I trembled and trembled. Then, I called Hye-na and begged her to save me.\n\n Soon, Hye-na came to my home, and I said to her I was probably going crazy, crying loudly in her arms. After I cried for a good while, I told her everything and taking her suggestion, I decided to see a doctor tomorrow. Hye-na is drinking a can of beer now.\n\n When I'm glancing at her, I feel my wrist, wrapped with bandages, is stinging.\n\n Okay, I'll finish today's diary here and go to bed after having some more conversations with Hye-na. Good night."
    new " 虽然今天没有面试，但也想化妆。于是起来坐到了化妆台镜子前，我被镜子中的自己吓得倒了过去，好不容易才起来爬上床，抱着枕头浑身颤抖着。一边哭着一边给慧娜打电话，哀求一定要来救我。\n\n 几天后，我抱着来单间找我的慧那痛哭起来，和她说我觉得我要疯了。哭了很久以后，我向慧娜一一叙述了之前发生的一切，最后决定明天一起去医院。慧娜坐在床边，好像没有什么事情的人一样喝着啤酒。\n\n 看着慧娜，感觉到缠着绷带的手脖子又开始疼了。 日记就写到这里吧，打算再和慧娜聊会天，然后去睡觉。"
    old " Today, I visited a neuropsychiatric clinic, with Hye-na. I was pretty afraid to go there, but as I was with my sister, I could do it. The doctor asked me a number of things, from trivial questions to what is happening to me now and what I don't want to tell others as well.\n\n He also asked whether I have some physical problems, and I told him I hurt myself several times, and especially when I looked at my face yesterday, I was really frightened, as my eyes continuously blinked. The doctor asked me to have a medical checkup. So I filled out the questionnaire and had a blood test as well.\n\n And the result said I had 'anxiety disorder' and 'depressive disorder'. I asked the doctor if I was going to be a mental patient. But he said no.\n\n He just told me my condition and tick disorder would get better soon, if I try hard to improve my life pattern and steadily get counseling."
    new " 今天，我和慧娜一起去神经精神科了。一想到真的要去，心里挺害怕的。但是因为妹妹在身边，所以有了勇气。医生从身边小事开始询问起来，包括我身边发生的事情和我不想谈起的事情。\n\n 当问到有没有过身体问题的时候，我回答有过几次自杀的经历，还有昨天看镜子的时候，眼睛总是眨来眨去的，我自己都很害怕。医生要求系统的检查一下，所以填写了调查问卷后，便验了血。\n\n 出来的结果是焦虑症和抑郁症。我问医生，我成了精神病吗？医生说那倒不是。\n\n 医生说改善现在的生活，坚持上门就诊治疗，抽动障碍也会有所好转。"
    old " Today, I met Eunju. It's been a really long time since I've seen her. She used to be my best friend when we were high school students, but she is not single anymore. She said she's really worried as she hasn't lost any weight in spite of her steady diet since she gave birth to her baby. So I told her that she still looks good. Eunju worried about me saying I'm so bony, and she said to take her fat from her, shaking her potbelly. It was hilarious.\n\n Eunju has become a master of a Japanese fencing school. I think she probably heard about my situation from Hye-na, because she has never asked me about my job or marriage.\n\n She just kept talking about our school days, or her travel. Like other mamas, her voice was louder than it used to be, and also she speaks so fast Anyway, I'm happy she is having a good life.\n\n Ga-yeon, no more negative thinking! Okay?"
    new " 见了好几年没见过面的恩洙，高中时闺蜜的恩洙如今变成了大妈，她说生孩子后虽然每天都有减肥，但就是减不下来。我说看起来胖胖的很好看呀，她边说你怎么这么瘦，边抓着自己肚子上的肉说，把我的肉给你点吧。看着这样的她觉得很有意思。\n\n 听说，恩洙已经成了剑道场的教练。可能是因为从慧娜那里听到了我的近况，没有问我有关工作和婚姻的事情。大部分时间都讲了上学时期自己旅游的经历。\n\n 生怕别人不说她已经是孩儿妈，以前大嗓门现在变得更大了，说话的速度也变快了。能看出她过的不错，我也跟着开心起来。\n\n 不要再想消极的想法！"
    old " These days, I receive mental health treatment, and also try hard to get a job. I didn't want to close my installment savings account, but I did, to have some reserved money for myself and also give some of it to my parents. I can't stop sending money to my parents because I have to make them believe I live well without any problem as always.\n\n However, getting a new job is harder than I expected. Because I worked mostly in restaurants, I have failed several times already, although I had a number of interviews for general office jobs.\n\n Besides, I never wrote my mental health-related matter in the resume, but some interviewers seemed to recognize my problem, as my tick disorder appeared even during the interview.\n\n I'm trying really to keep the steam up, but…. I'm getting tired of living…."
    new " 最近，一边进行精神治疗一边在找工作。虽然很可惜，但是我还是把存死期的钱找了出来，准备给父母的零花钱和我的生活费。不管有什么事情，都要记得给父母寄零花钱，因为只有这样，他们才会放心，会认为我没有出现什么其他事情。\n\n 但是，找一个新工作也并不是简单的事情。由于以前主要经历是快餐业，所以我面试一般的办公室或者经理工作，但是每次都以失败而告终。\n\n 接受精神科治疗的事情，我并没有写在简历上，偶尔在面试中，出现抽动现象，面试官就会问我身体有没有什么残疾。\n\n 我安慰自己要加油…,但是从各个方面都让我感到无比的艰难…。"
    old " I gave up. I gave up finding a new job, meeting people, receiving medical treatment, and everything. All are just useless. What I have now is…. only this tiny space. Where nothing happens unless I stir it.\n\n In spite of heaps of attempts to get a job, what I had was only frustration and discouragement. The hospital where I've received the treatment suggested I transfer to another hospital. Sometimes, the nebulizer which Hye-na presented me to soothe myself didn't work at all.\n\n I feel like my room is a rubbish can, and I'm just rubbish."
    new " 我已经全部放弃了。找工作的事情、男朋友的事情、精神科治疗的事情，把这些没有用的事情都放弃了。剩下的就是这小小的空间，如果我不做什么动作，就不会发生任何事情的地方。\n\n 持续的就业活动带来的只有挫折，坚持治疗的医院也建议我换一家医院再进行治疗，说他们已经没有别的办法了。呼吸困难的时候，慧娜送的喷雾器也已经起不到安神的作用了。\n\n 我的房间就是垃圾桶，我就是垃圾。"
    old " Go die, you bitch. How dare you want to live on! You're such a hooker who tried to take another's husband! Why are you still alive? You know well what a useless thing you are. You're just a whore. Now are you going to cling to him, instead of your previous lover? You don't deserve to live anymore. Go away. Go away and die.\n\n Someone keeps whispering in my ears. Okay. Alright. Just stop it, please. Please. I'm sorry. I go and die now. So, please shut up!"
    new " 去死吧，你这个没有用的东西，一个想抢别人丈夫的人，你以为自己能过的很好吗？你连活着的资格都没有，去死吧，快消失吧。\n\n 不知道是谁，总在我的耳边说这样的话。知道了，不要再说了。我也知道，所以千万不要再说了。嗯，对不起，我去死，去死好吧？千万，千万不要再说了！"
    old 'Help….'
    new '帮帮我吧…。'
    old 'Hmm….'
    new '呃….'
    old 'My bed.'
    new '我的床。'
    old 'There is no plastic bag.'
    new '那儿没有塑料袋。'
    old 'There is no jam on the bookshelf.{w=.3} And toilet…?'
    new '桌子上没有果酱。{w=.3}难道不会在洗手间吧？'
    old 'My room is very small.'
    new '我的房间非常小。'
    old "It seems to be around…."
    new "在附近…。"
    old "It seems to be around.{w=.3} But it's not in the refrigerator."
    new "在附近。{w=.3}但不是冰箱。"
    old 'I stare at my reflection in the mirror.{w=.3} Are you happy now?'
    new '注视着镜子里的我。{w=.3}你幸福吗？'
    old "It's near."
    new "变近了。"
    old 'The water coming out of well.'
    new '水出来得很正常。'
    old "It's me."
    new "这个不是。"
    old 'Please….'
    new '拜托…。'
    old 'Somebody…, help me….'
    new '拜托谁…。{w=.3}快来救救我吧…。'
    old 'Not there!'
    new '不是那里！'
    old "It's a washing machine,{w=.3} and a gas stove."
    new "是洗衣机和燃气灶。"
    old 'Open it!'
    new '打开看看！'
    old "I don't have any kitchen tools."
    new "没有任何厨房工具。"
    old 'Take out it!'
    new '把那个拿出来！'
    old "It's a cat plastic bag."
    new "是一个猫模样的塑料袋。"
    old 'ACOC, Aiman Sharul, Axel Mertes, Bgame, Brandon Tanimoto, Brian Connors, BRISAK Kim Doohyeon, cheif.choi, Choi Irang, Choi Jihye, cloture, Danielle Bell, Edward N Puckering, Gary King, Gwak Jaeryeol, Han Ihyeong, Hoe Namyoon, Hong Eunki, Hwang Daehoon, Hyojoon, James Emmerson, Jeong Dongwon, Jeong Wookjin, Jeong Yoonsoo, Jianmin Zhang,\nKarina Schulze, Keira Val\'Azr, Kim Hanseol, Kim Hyeoncheol, Kim Jaeseong, Kim Jeongwoong, Kim Myeongwook,\nLee Changki, Lee Eunji, Lee Gunhae, Lee Hyejin, Lee Jaewi, Light Twins, Lim Jisoo, Maddy Wootton,\nMarshall Proudfoot, Mirumu, Mojaeng, Oh Hyeonjun, Park Hyeonjun, Park JoonKoo, Rewind, Sander Tieleman, srwss, Sung Chanaul, YottaCho, Zerial.net'
    new 'ACOC, Aiman Sharul, Axel Mertes, Bgame, Brandon Tanimoto, Brian Connors, BRISAK Kim Doohyeon, cheif.choi, Choi Irang, Choi Jihye, cloture, Danielle Bell, Edward N Puckering, Gary King, Gwak Jaeryeol, Han Ihyeong, Hoe Namyoon, Hong Eunki,\nHwang Daehoon, Hyojoon, James Emmerson, Jeong Dongwon, Jeong Wookjin, Jeong Yoonsoo, Jianmin Zhang,\nKarina Schulze, Keira Val\'Azr, Kim Hanseol, Kim Hyeoncheol, Kim Jaeseong, Kim Jeongwoong, Kim Myeongwook,\nLee Changki, Lee Eunji, Lee Gunhae, Lee Hyejin, Lee Jaewi, Light Twins, Lim Jisoo, Maddy Wootton, Marshall Proudfoot,\nMirumu, Mojaeng, Oh Hyeonjun, Park Hyeonjun, Park JoonKoo, Rewind, Sander Tieleman, srwss, Sung Chanaul, YottaCho, Zerial.net'
    old 'Caz Woolley, Game Dev Robot, Gamsadev, Indie GameDev Bot, Indie Game Lover, Indie Games Devel, IndieVideoGames, Joachim Dimitri Jensen, Kim Kyeongtae, Kim Younghwan, Kurt Simon, Linda Lee King, Peter Christiansen, Sakimichi, Sebastian Haba, Spero Mcgee, The Indie Sloth, Vrachos, Xin Liu, Yu Shinhyeon'
    new 'Caz Woolley, Game Dev Robot, Gamsadev, Indie GameDev Bot, Indie Game Lover, Indie Games Devel, IndieVideoGames,\nJoachim Dimitri Jensen, Kim Kyeongtae, Kim Younghwan, Kurt Simon, Linda Lee King, Peter Christiansen, Sakimichi,\nSebastian Haba, Spero Mcgee, The Indie Sloth, Vrachos, Xin Liu, Yu Shinhyeon'
